### ISSUE TITLE
What's the correct way to create PIXI primitives, such as Container?

### ISSUE THREAD

**Issue by sfentress** [inlet/react-pixi#102]
I am looking to include [Pixi-Particles](https://github.com/pixijs/pixi-particles) in my app. To do so, I need to create a PIXI.Container, add it to the stage, and reference it directly.

```
var emitter = new PIXI.particles.Emitter(
    // The PIXI.Container to put the emitter in
    container,
    ...
)
```
I thought perhaps I could do
```
render() {
    const emitterContainer = <Container />
    var emitter = new PIXI.particles.Emitter(emitterContainer, ...)

    return (
      <Stage>
        { emitterContainer }
      </Stage>
    );
}
```
but of course `<Container>` is not a `PIXI.Container`.

Any help appreciated, thank you.

### Additional info

- `@inlet/react-pixi` version: 0.5.7
- `React` version: 16.0.11
- `ReactDOM` version: 16.0.11

**Comment by inlet** [comment]
You can easily create React components from PIXI primitives using [Custom Components](https://reactpixi.org/#/#custom-components).

**Comment by inlet** [comment]
I've created an example here:
https://codepen.io/inlet/pen/feddc8fa71e3b5afc6c3e4eda9cc83df

**Comment by sfentress** [comment]
That's perfect, thank you!
