### ISSUE TITLE
Correct way for accessing PIXI primitive instance

### ISSUE THREAD

**Issue by alexandr-bbm** [inlet/react-pixi#103]
Hi, I can you please advise me on correct way of accessing PIXI primitives while using this library.

Assume I have a `Sprite` and I want to animate it by using the function from `pixi-sprite-utilities` which needs the `Sprite` instance.

Currently, I see the way of accessing it via `app` which does not seem to be a good solution, e.g. `this.app.stage.children[1]`

Is there a better way of doing this? I thought the instance should be accessible by passing a callback to some prop of `Sprite`. Or should I use a custom component to achieve this?

Thanks.

**Comment by inlet** [comment]
Hi @alexandr-bbm, yes you can use React's `ref` (which is the preferable way):

```jsx
import { Sprite } from '@inlet/react-pixi';
import { useRef, useEffect } from 'react';

function MyComponent() {
  const sprite = useRef();

  useEffect(() => {
    const spriteInstance = sprite.current; 
    // spriteInstance === PIXI.Sprite
  }, []);

  return <Sprite ref={sprite} />
}
```

**Comment by alexandr-bbm** [comment]
@inlet sorry I was sure I tried this, but I rechecked and it seems to work

Thank you for the fast reply!

**Comment by inlet** [comment]
Awesome! you're welcome
