### ISSUE TITLE
v 0.7.0 doesn't work with latest version react and pixi

### ISSUE THREAD

**Issue by Tilican** [inlet/react-pixi#111]
### Description

v 0.7.0 doesn't work with latest version react and pixi

```
Uncaught TypeError: callback is not a function
    at flushFirstCallback (scheduler.development.js:348)
    at flushWork (scheduler.development.js:441)
    at MessagePort.channel.port1.onmessage (scheduler.development.js:188)
flushFirstCallback @ scheduler.development.js:348
flushWork @ scheduler.development.js:441
channel.port1.onmessage @ scheduler.development.js:188
```
and

```
PixiJS Deprecation Warning: PIXI.Texture.fromImage method is deprecated, use PIXI.Texture.fromDeprecated since v5.0.0
```

### Steps to reproduce

1. go here : [codepen](https://codepen.io/anon/pen/ydxyej)

### Additional info

- `@inlet/react-pixi` version: 0.7.0
- `React` version: 16.8.6
- `ReactDOM` version: 16.8.6
- `PIXI` version: 5.0.4

Thx for your work

**Comment by inlet** [comment]
Thanks for pointing out.

It seems that the new reconciler is still in alpha and breaks hooks in particular with this host config. I've set back the react-reconciler to the stable one and it should work again.

**Comment by inlet** [comment]
Update to latest patch and it should work:

```
yarn upgrade @inlet/react-pixi@latest
```

**Comment by Tilican** [comment]
@inlet actually don't crash but don't display things ...[here](https://codepen.io/anon/pen/ydxyej)

**Comment by inlet** [comment]
The default ReactPIXI components are built for PIXI `v4`. We need to upgrade them, should be to much work. They have a slightly different API.

Recommended is to use PIXI v4, but if you really want to use PIXI v5 features you can use [custom components](https://reactpixi.org/#custom-components). Here's an example with PIXI's new display API: https://codepen.io/inlet/pen/mvzzLb.

**Comment by inlet** [comment]
And here's your working codepen with the latest patch: https://codepen.io/inlet/pen/a0d6f2c6f2040ebcb80597fbcf5aaa73

**Comment by Tilican** [comment]
Awesome :)
thx for your work @inlet  !!!

**Comment by inlet** [comment]
Welcome, and if you're up to it feel free to contribute!
