### ISSUE TITLE
0.7.1 cannot render Text

### ISSUE THREAD

**Issue by Tilican** [inlet/react-pixi#113]
### Description

It's again me !
0.7.1 cannot render <Text x={30} y={90} text="Basic text in pixi" /> L43

### Steps to reproduce

1. [https://codepen.io/anon/pen/qzMbqe](https://codepen.io/anon/pen/qzMbqe?editors=0011)

### Additional info

- `@inlet/react-pixi` version: 0.7.1
- `React` version: 16.8.6
- `ReactDOM` version: 16.8.6
- `PIXI` version: 4.8.8

thx

**Comment by inlet** [comment]
You're running the production version of React and ReactDOM, but using the development version of ReactPIXI. It seems that the react-reconciler [appears to blow up](https://github.com/diegomura/react-pdf/issues/336) if it doesn't match the custom renderer environment.

Make sure to use the production of ReactPIXI and it works.

**Comment by inlet** [comment]
Also don't forget to import the Text from ReactPIXI 😉
