### ISSUE TITLE
UnMount component manully

### ISSUE THREAD

**Issue by lorenzocadamuro** [inlet/react-pixi#117]
### Description
HI, first of all thank you for the work you've done in these months.

I have a problem in removing a component rendered with the ```render``` method.

The code below should help you in understanding what I'm doing:

```jsx
componentDidMount () {
  const renderTexture = PIXI.RenderTexture.create(100, 100)

  const container = new PIXI.Container()

  this.myComponent = <MyPIXIReactComponent />

  render(this.myComponent, container)

  app.ticker.add(() => {
    app.renderer.render(container, renderTexture, true)
  });
}
```

My problem is that I'm not able to unmount the component when the parent is removed; It continues to be alive.

Is there any way to do it?

Something like:

```jsx
componentWillUnmount () {
  unMount(this.myComponent)
}
```

Thanks!

### Additional info

- `@inlet/react-pixi` version: ^0.4.3
- `React` version: ^16.6.3
- `ReactDOM` version: ^16.6.3
- `PIXI` version: ^4.8.5

**Comment by inlet** [comment]
Hi @lorenzocadamuro, could you please create an example on codepen or codesandbox? 
Btw make sure you’re using the latest versions 😉

**Comment by lorenzocadamuro** [comment]
Unfortunately I can't use the last version because is not a new project.

Anyway, my question is not about a problem, but about knowing if that feature exists.

Since ```this.myComponent``` is not rendered as Component by React, but with the render function provided by ```@inlet/react-pixi```, I don't know how to unmount it when needed.

I hope it's more clear now.

**Comment by inlet** [comment]
Ah I see you're using the custom render method here. I notice that we need to provide a way to clear the Fiber container from https://github.com/inlet/react-pixi/blob/19bbd6305067f2cfd399edec39f21b425b5486cf/src/render/index.js#L6

However there's a quick fix, use `PixiFiber` and create your own render method. This way you clean up the Fiber container as well.

And make sure you component opts-in on garbage collection. 

```jsx
 // never do this 👇
app.ticker.add(() => {
  app.renderer.render(container, renderTexture, true)
});
```

make sure to clean up the listener on unmount, something like this:

```jsx
onTick = () => {
  // ticker logic
}

componentDidMount() {
  this.props.app.ticker.add(this.onTick);
}

componentWillUnmount() {
  this.props.app.ticker.remove(this.onTick);
}
```

**Comment by inlet** [comment]
Hope this helps you. Hence using the `<Stage />` component in the recommended way.
