### ISSUE TITLE
Can't update very well the resolution of a stage

### ISSUE THREAD

**Issue by macabeus** [inlet/react-pixi#127]
### Description

I'm adding a feature to user can select the resolution of the image. So I added at `Stage` component the `resolution` option, `onMount` prop to save the `pixiApplication` and I updated the width/height to grow proportionally with the resolution:

```diff
  <Stage
-  width={width * 4}
-  height={height * 4}
+  width={width * 4 * resolution}
+  height={height * 4 * resolution}
+  options={{ resolution }}
+  onMount={setPixiApplication}
  >
```

And I added a function to be called when the resolution is changed, to update the resolution on the `pixiApplication`:

```js
if (
  pixiApplication !== null &&
  pixiApplication.renderer.resolution !== resolution
) {
  pixiApplication.renderer.resolution = resolution
  pixiApplication.render()
}
```

But with this code, the stage grows up more than the I expected. The height grown up from 240 to 375, but the expected value is 300.

![image](https://user-images.githubusercontent.com/9501115/61586485-b63f2800-ab4b-11e9-8932-580b9792c5a7.png)

After much attempts, I found a "solution". For some reason, I need to set a new and small value at `width` and `height` to my `Stage`, for example:

```diff
  <Stage
-  width={width * 4 * resolution}
-  height={height * 4 * resolution}
+  width={(width * 4) + resolution}
+  height={(height * 4) + resolution}
```

So it "fixes" my code... but it is a very strange for me...

[You can check my code here.](https://github.com/macabeus/klo-gba.js/pull/56/files#diff-8e706ddceb15e5eba36b748de01415e9R51)

### Additional info

- `@inlet/react-pixi` version: `1.0.0`
- `React` version: `16.8.2`
- `ReactDOM` version: `16.8.2`
- `PIXI` version: `5.0.4`

**Comment by inlet** [comment]
Oh yes.. well the `resolution` part is not implemented in ReactPixi yet, simply because I don't know how to implement it correctly.

Here's a snippet from an old project (based on PIXI v4):

```ts
updateResolution(
  resolution: number, 
  width: number, 
  height: number
) {
  // change PIXI settings
  PIXI.settings.RESOLUTION = resolution

  // update renderer's res
  this.renderer.resolution = resolution
  this.renderer.rootRenderTarget.resolution = resolution

  // create new interaction manager based on new res
  this.renderer.plugins.interaction.destroy()
  this.renderer.plugins.interaction = new PIXI.interaction.InteractionManager(this.renderer)

  // resize the renderer accordingly
  this.renderer.resize(width, height)
}
```

I know what you think haha, there must be a better way of doing this. (that's why I left out the resolution part)

And the injection point in `Stage` would be:

https://github.com/inlet/react-pixi/blob/fcdee48e430588e89b556bd072dbb15c95da61af/src/stage/index.js#L144

Please feel free to create a PR with the correct implementation.

Thanks!
