### ISSUE TITLE
Pixi peer dependency needs updating

### ISSUE THREAD

**Issue by Adamfsk** [inlet/react-pixi#132]
### Description
The latest version has the peer dependency for pixi set to pixi.js@5.0.4. There's now a new version out, so we now get unnecessary warnings for incorrect peer dependencies.

warning " > @inlet/react-pixi@1.0.0" has incorrect peer dependency "pixi.js@5.0.4".

It would be best to simplify this to something like pixi.js@^5.1.0

**Comment by inlet** [comment]
Thanks @Adamfsk,

Fixed in this patch: https://github.com/inlet/react-pixi/releases/tag/v1.0.1
Now accepting minor and patch versions for peer dependencies.
