### ISSUE TITLE
Support enable flag in type of useTick

### ISSUE THREAD

**Issue by scrmea** [inlet/react-pixi#134]
Hi, 
I think the following line

https://github.com/inlet/react-pixi/blob/bd2ae9f467e1942c71db7efaa039f4d4555177a0/index.d.ts#L280

should be changed to 

`export const useTick: (tick: (delta?: number) => void, enabled?: boolean) => void;`

to support passing the enabled flag to the useTick hook. 
Could you change the line? I'm using the flag in a TS project.
Thanks!

**Comment by inlet** [comment]
Thanks for letting me know, fixed in df2d78e1445fedf33ffac8e99e5c57b27d8f578e
