### ISSUE TITLE
PixiComponent not exported by modules.js

### ISSUE THREAD

**Issue by Adamfsk** [inlet/react-pixi#139]
### Description
When trying to create a custom PixiComponent in typescript and compile using Es modules, the compiler reports that PixiComponent is not exported by modules.js

### Steps to reproduce

1. Create a typescript component targeting ESNext and create a custom Pixi component 
2. Try to run the typescript compiler

### Additional info

React 16.8
Typescript 3.6
Pixi 5.0.4

**Comment by inlet** [comment]
Cannot reproduce. Can you create a codesandbox example perhaps?

This works:

`tsconfig.json`: 

```json
{
  "compilerOptions": {
    "moduleResolution": "node",
    "target": "esnext",
    "jsx": "react",
    "skipLibCheck": true
  },
  "include": ["src/index.tsx"]
}
```

`src/index.tsx`:

```tsx
import { Graphics } from "pixi.js";
import * as React from "react";
import { Stage, PixiComponent } from "@inlet/react-pixi";

interface RectangleProps {
  x: number;
  color: number;
}

const Rectangle = PixiComponent<RectangleProps, Graphics>(
  "Rectangle",
  {
    create: () => {
      return new Graphics();
    },
    applyProps: (ins, _, props) => {
      ins.x = props.x;
      ins.beginFill(props.color);
      ins.drawRect(0, 0, 100, 100);
      ins.endFill();
    }
  }
);

const App = () => (
  <Stage width={800} height={600} options={{ height: 600 }}>
    <Rectangle x={100} color={0xff0000} />
  </Stage>
);
```

**Comment by Adamfsk** [comment]
Will create a sandbox. My colleague also replicated the issue. Might be related to rollup possibly

**Comment by Adamfsk** [comment]
Closing this for now, suspect it’s rollup causing the issue

**Comment by sanbornhilland** [comment]
@Adamfsk Did you ever solve this problem? I'm also having issues with rollup + react-pixi. E.g. `Error: 'Text' is not exported by node_modules/@inlet/react-pixi/module.js`

**Comment by Adamfsk** [comment]
@sanbornhilland I did find a way eventually but don’t remember the solution, but I then encountered various issues with the react-Pixi typings that made it impossible for me to use for what I wanted. Maybe something has improved in the typings now. There was an open ticket with improved but still not fully working typings back then.

**Comment by inlet** [comment]
@Adamfsk can you let me know what typings are not working correctly?

**Comment by Adamfsk** [comment]
@inlet I don’t remember the exact details now, but  the main issue was when making my own custom objects, typescript was throwing errors all over the place. The few solutions I found made it break at runtime instead. One of my colleagues also tried and failed to get it working. It has been months since this happened now though.

**Comment by Jtfinlay** [comment]
About two years late to the party, but the following worked for me using `"@inlet/react-pixi": "^6.6.5",`, typescript, and rollup. Will hopefully help others.

```
import pixi from '@inlet/react-pixi/index';

return (
    <pixi.Stage {...stageProps}>
        <pixi.Graphics draw={draw} />
    </pixi.Stage>
);
```

Trying to load from `import { Stage, Graphics } from '@inlet/react-pixi/index';` leads to export errors with rollup.
