### ISSUE TITLE
Feature request: GSAP support.

### ISSUE THREAD

**Issue by ayeQ** [inlet/react-pixi#140]
### Description
Suggested implementation of GSAP animation library.
https://github.com/bitworking/react-gsap

**Comment by inlet** [comment]
Hi @ayeQ what are you suggesting? What issue are you trying to solve?

**Comment by ayeQ** [comment]
Thanks for your response. There is no error. It was me.. 
Here is a working example: https://codesandbox.io/s/react-pixi-nightowllogic-9uv77
It wasn't working previously and must have been a late night gremlin in the code.
