### ISSUE TITLE
GPU keeps increasing

### ISSUE THREAD

**Issue by ayeQ** [inlet/react-pixi#141]
### Description
I have a sample project using a video camera, animated text and graphics.

The GPU starts below 20% and keeps increasing to over 50% within 5 minutes.  Is there a memory leak somewhere that I'm creating?

https://codesandbox.io/s/react-pixi-nightowllogic-q2vq5

**Comment by inlet** [comment]
There are no known leaks, but can you try the following:

- Don't use the `draw` prop on `Graphics`. See https://reactpixi.org/components/graphics#props
- Run it in isolated context, not in a codesandbox as there are other resources consuming your memory and GPU.

**Comment by ayeQ** [comment]
The issue was the draw prop on Graphics. Ok, so WebGL likes sprites. I'll generate a texture with the graphics and apply that to a sprite. Thanks again. GPU is stable for me. Closing.

**Comment by ayeQ** [comment]
Thanks again!
