### ISSUE TITLE
Work pixi-viewport with react-pixi

### ISSUE THREAD

**Issue by gespispace** [inlet/react-pixi#143]
### Description
I try connect [pixi-viewport](https://github.com/davidfig/pixi-viewport) and `react-pixi` for work together, but can't.
In my [codesandbox](https://codesandbox.io/s/proud-smoke-x0v9u) work event on `drag-start`, but image won't move or zoom.

Help me get to work together these packages

### Steps to reproduce

1. try move image
2. see `drag-start` event in console 

### Additional info

- `@inlet/react-pixi` version: 1.1.0
- `React` version: 16.8.6
- `ReactDOM` version: 16.8.6
- `PIXI` version: 5.1.5
- `pixi-viewport` version 4.2.3

**Comment by warrenseymour** [comment]
@gespispace How odd that I am looking at the exact same combination for the first time. Thank you providing a sandbox, it's been very useful.

I was able to get your demo to work by making the `<Text />` component a child of the `<Viewport />` - I've forked your sandbox with the required changes here: https://codesandbox.io/s/elated-liskov-pdcd6

**Comment by gespispace** [comment]
@warrenseymour Thank you very much.

**Comment by inlet** [comment]
Awesome guys!

**Comment by Heilemann** [comment]
@wms @inlet @gespispace In this setup—which I've copied and gotten to work—how do I run methods on the viewport?
