### ISSUE TITLE
onUnMount for Stage

### ISSUE THREAD

**Issue by scottkunkel** [inlet/react-pixi#15]
### Description
Please provide an unmount hook to clean up resources

### Steps to reproduce

1.
2.

### Additional info

- `@inlet/react-pixi` version: 
- `React` version:
- `ReactDOM` version:
- `PIXI` version:

**Comment by scottkunkel** [comment]
Sure, I am doing

export class App extends React.Component<AppProps>{

  stageMount(app: any, container: HTMLElement){
    const width =  Number(window.getComputedStyle(container).width.replace("px",""));
    const height = Number(window.getComputedStyle(container).height.replace("px",""));
    const scale = width / APP_DEFAULT.canvasWidth < height / APP_DEFAULT.canvasHeight ?
      width / APP_DEFAULT.canvasWidth : height / APP_DEFAULT.canvasHeight;
      app.renderer.resize(APP_DEFAULT.canvasWidth * scale, APP_DEFAULT.canvasHeight * scale);
      app.stage.scale.set(scale, scale);
  }

  createObserver(app: any, container: HTMLElement){
    app.ResizeObserver = new ResizeObserver((entries, observer) => {
      for (const entry of entries) {
          this.stageMount(app, entry.target as HTMLElement);
      }
    });
    app.ResizeObserver.observe(container);
  }

  render(){
    return (
      <Stage 
        height={1080} 
        width={1920} 
        options={{
          backgroundColor: 0x10bb99,
          antialias: true
        }}
        onMount={ app  => {
          this.stageMount(app, this.props.container);
          this.createObserver(app, this.props.container);
        }}
      >
        <Text text="Hello World" x={200} y={200} /> 
      </Stage>
    )
  }
  
}

I'd like to unobserve in the unmount.

**Comment by inlet** [comment]
Sure we could add a `onUnmount` prop, but why not add those React life cycles to your class instead?

**Comment by scottkunkel** [comment]
yes, that's a solution.

Thanks

**Comment by inlet** [comment]
Having an unmount isn’t a bad idea, if you’re up to it you can create a PR with test ;)

**Comment by inlet** [comment]
I'll close this issue, if you'd like the unmount in `Stage` please create a PR with some tests 🤘

**Comment by inlet** [comment]
👍 The unmount prop is added in PR #16.
