### ISSUE TITLE
"pointerover" prop isn't working correctly when updates the resolution

### ISSUE THREAD

**Issue by macabeus** [inlet/react-pixi#150]
### Description
I'm developing a tilemap editor using this library, and the user can dragging some objects inside it.
The problem is that, when the user updates the zoom, the prop `pointerover` isn't called on the "new position" of the object.

**These photos explain better what is happen:**
When we doesn't set a zoom, we can to hover an object. You can see that it has a strong border when is hovered.
![image](https://user-images.githubusercontent.com/9501115/66703119-20a8d400-ed07-11e9-8031-c891272ed026.png)

But when we updates the zoom, we can't hover it as expected. We need to hover it using its "previous position".
![image](https://user-images.githubusercontent.com/9501115/66703125-29010f00-ed07-11e9-9837-bf63c6584390.png)

The code of [`pointerhover` is here](https://github.com/macabeus/klo-gba.js/blob/1db3347d58a5167184137cfc4f4178cf3cc5a871/brush/src/components/Map/Point/index.js#L54-L57). And the code to update the [resolution is here](https://github.com/macabeus/klo-gba.js/blob/5f95c4097ff5fb404a0bb21bc0b702b5fb1802dd/brush/src/components/Map/index.js#L57).

An important detail: if we starts the application using a different zoom (for example, `2` instead of the default `1`) it will works fine with the zoom `2`, but fails when updates to `1` while running the application. The bug happens when we updates the resolution.

### Steps to reproduce

I'm having this problem on my open source application: https://github.com/macabeus/klo-gba.js

### Additional info

- `@inlet/react-pixi` version: 1.1.2
- `React` version: 16.10.2
- `ReactDOM` version: 16.10.2
- `PIXI` version: 5.1.5

**Comment by macabeus** [comment]
I think that this issue is important to understand better the problem: https://github.com/inlet/react-pixi/issues/127

**Comment by inlet** [comment]
Yes this seems to be related to #127. I'll close this issue as the fix is already suggested. Again feel free to create a PR. Thanks!
