### ISSUE TITLE
Support of className attribute

### ISSUE THREAD

**Issue by paolotozzo** [inlet/react-pixi#155]
### Description

I've been working on a very useful implementation of the support of 'className' in the library, meaning that we could be able to write css or sass files to define PIXI elements properties as follow

pixi.css
`pixi.rotated {
y: 150;
rotation: 60;
...
}
pixi.button {
interactive: true;
...
}
pixi.shadow-text {
   fontFamily: Arial;
   fontSize: 36;
   fontStyle: italic;
   fontWeight: bold;
   fill: ['#FF0000', '#FFFF00'];
   dropShadow: true;
   dropShadowColor: #000000;
   dropShadowBlur: 4;
   dropShadowDistance: 6;
}
`

And then 
`<Container x={0} y={0} className={'rotated'}>
  <Text className={'shadow-text'} text="Formatted text"  />
</Container>`

Also the following will be supported:
- css mediaqueries
- animations and transitions (when gsap is a dep.) exposing `animationEnd` and `transitionEnd` events.
- `!important` to override inline props 
- styled components (https://www.styled-components.com/)

I'll be soon submitting a PR, let me know if you think it'll be a useful feature for the library

**Comment by paolotozzo** [comment]
Hi, @inlet, just to let you know that in the meantime I found myself in the flow :) and actually getting close to finish this, so I might submit a PR next week. As it is not that trivial I really hope it will be accepted

**Comment by inlet** [comment]
Hi @paolotozzo,

Looks absolutely interesting, please let me know how it progresses..

Thanks for all the effort!
