### ISSUE TITLE
withFilters is missing in typings.d.ts

### ISSUE THREAD

**Issue by adsko** [inlet/react-pixi#158]
### Description
withFilters util is missing in typings.

### Steps to reproduce

1. https://repl.it/@l12lpo1adamowsk/PeachpuffGeneralRobot
2.

### Additional info

- `@inlet/react-pixi` version:  5.1.5
- `React` version: 16.8.2
- `ReactDOM` version: 16.8.2
- `PIXI` version: 1.1.6

**Comment by inlet** [comment]
@paolotozzo Can you add typings to `index.d.ts` for `withFilters`? Thanks! #153

**Comment by paolotozzo** [comment]
@inlet Yes, I am on it.

**Comment by inlet** [comment]
Fixed in #159
