### ISSUE TITLE
Sprite mark property does not work correctly

### ISSUE THREAD

**Issue by ximing** [inlet/react-pixi#160]
### Description
Sprite mask not work

### Steps to reproduce
use the following demo to reproduce
https://codesandbox.io/s/romantic-browser-ddqho

### Additional info

- `@inlet/react-pixi` version:  1.1.8
- `React` version: 16.8.6
- `ReactDOM` version: 16.8.6
- `PIXI` version: 5.2.0

**Comment by inlet** [comment]
Hi @ximing 

The mask does work, but in your example the components (mask and masked item) are siblings and therefore it needs an extra render before you see the actual effect. You're using a ref to set the mask and refs don't trigger a render.

Here's a working example (with refs): https://codepen.io/inlet/pen/cac93cf4d47c26ba2511801b75e652b8

To solve a single render, I recommend you set the mask with state so it automatically rerenders your component, here's an example: https://codepen.io/inlet/pen/b392ac702ed6cf637bd49ccc6f3af37c

> Side note: Keep in mind that the Graphics `draw` can be a little heavy, to boost your performance you can add the `preventRedraw` prop so it doesn't rerender.

**Comment by ximing** [comment]
It is found that TS type support is missing. This PR is submitted
#162
