### ISSUE TITLE
I have a problem with responsive

### ISSUE THREAD

**Issue by limj0825** [inlet/react-pixi#163]
Hi, i'm working with a game, i want to make a 2048 with react-pixi, but i want to use responsive stage that i can play on the phone and computer both, what component should i use or what options or javescript i should add in stage or container, thank you :)!

**Comment by inlet** [comment]
Awesome! Yes it's quite easy, just set adjust the width and height of the `<Stage>` and play around with coordinates.

I've created a simple codepen example:
https://codepen.io/inlet/pen/09f6a44fb173af22a7946817ee5b834d

**Comment by limj0825** [comment]
thank you very much!

**Comment by limj0825** [comment]
Hi! i have some very easy questions again, so sorry for that.
1. how can i add sprite to stage, now i only can add in default code not use function, such like this.
`<Stage><Sprite image={require('./images/test.jpg')} x={startWidth + len * 3} y={startHeight} width={len} height={len}/>
    </Stage>`

2.when i add a sprite from function, how can i get it's id or other feature then remove it or set it's isvisable to false or set zindex to -1?

3.i want to add swipe in my cavans, but i only need to set the grid(Assumption here exist a rectangle {TopLeft: [x, y], size: [width, height]}) can listen to swipe, in the previous 
project, my code is like this.`<Swipe onSwipeLeft={this.swipeleft} onSwipeRight={this.swiperight}><Grid {...props}/></Swipe>`

4.in react-pixi, is there exist a function that can move a sprite from [x, y] to [n, m]? or i need to import other package?

thank you! :)
