### ISSUE TITLE
Hi! i have some very easy questions again, so sorry for that.

### ISSUE THREAD

**Issue by limj0825** [inlet/react-pixi#166]
Hi! i have some very easy questions again, so sorry for that.

1. how can i add sprite to stage, now i only can add in default code not use function, such like this.
`<Stage><Sprite image={require('./images/test.jpg')} x={startWidth + len * 3} y={startHeight} width={len} height={len}/>
    </Stage>`

2.when i add a sprite from function, how can i get it's id or other feature then remove it or set it's isvisable to false or set zindex to -1?

3.i want to add swipe in my cavans, but i only need to set the grid(Assumption here exist a rectangle {TopLeft: [x, y], size: [width, height]}) can listen to swipe, in the previous 
project, my code is like this.`<Swipe onSwipeLeft={this.swipeleft} onSwipeRight={this.swiperight}><Grid {...props}/></Swipe>`

4.in react-pixi, is there exist a function that can move a sprite from [x, y] to [n, m]? or i need to import other package?

thank you! :)

_Originally posted by @limj0825 in https://github.com/inlet/react-pixi/issues/163#issuecomment-553993374_

**Comment by inlet** [comment]
Hi @limj0825,

I’ll be glad to answer these kind of questions via email, but please let’s use GitHub issues for code related stuff only.

Thanks!

**Comment by inlet** [comment]
And make sure you check out the docs (Github README and https://reactpixi.org) which should give you a better understanding of ReactPixi
