### ISSUE TITLE
Spine Component

### ISSUE THREAD

**Issue by paolotozzo** [inlet/react-pixi#167]
### Description

Hi @inlet 

I'd like to add the Spine's support (http://esotericsoftware.com/) as it is a very popular tool for designers and animators in the game development world (we for example use it quite a lot) and it is already working nicely with PIXI through the pixi-spine (https://pixijs.io/examples/#/plugin-spine/dragon.js). The way is going to work it will be very easy to also add dynamic content generated in PIXI to existing Spine animations through the React compound component pattern.

I am going to submit a PR soon if you feel it'd be a good addition to the library

**Comment by inlet** [comment]
Hi @paolotozzo, wow you're on 🔥!

Love to see the PR, thanks!

**Comment by jefe-spain** [comment]
Madness @paolotozzo !! 🔥

**Comment by ascorbic** [comment]
Any progress on this, @paolotozzo? If not, I might give it a go.

**Comment by paolotozzo** [comment]
@ascorbic Hi Matt, I got slightly sidetracked last week, but planning to finish over the course of next week

**Comment by ascorbic** [comment]
I got a rough demo working yesterday. Gist is here: https://gist.github.com/ascorbic/f01009247f859f0d76b8b92d34ae87bd
Demo here: https://master.d1bkaw8b0oav5y.amplifyapp.com/

**Comment by paolotozzo** [comment]
Great, my PR is almost ready, things are a bit busier than expected but as I am now left with only to write the documentation by the end of the week I'll be able to submit it

**Comment by paolotozzo** [comment]
#174
