### ISSUE TITLE
Masking Sprite component

### ISSUE THREAD

**Issue by romanstan1** [inlet/react-pixi#170]
### Description
The image im using for the Sprite is much larger than required (910px). I need to dynamically change the height of the container, masking the image.

Does anyone know how to do this?

```
<Container
      x={x}
      y={y}
      width={width}
      height={height}>
   <Sprite
        image={image}
        anchor={[0, 0]}
        x={0}
        y={0}
        width={width}
        height={910}
        rotation={0} />
 </Container>
```

### Additional info

 @inlet/react-pixi: "^1.1.9"
 pixi.js: "^5.2.0"
 react: "^16.12.0"
 react-dom: "^16.12.0"

**Comment by romanstan1** [comment]
This doesn't work either as the texture remains static as the graphic moves around
 ```
<Graphics
      draw={(g) => {
        g.clear()
        const texture = new PIXI.Texture.from(image)
        g.beginTextureFill(texture)
        g.drawRect(x, y, width, height)
        g.endFill()
      }} />
```

**Comment by inlet** [comment]
Hi @romanstan1 I've just sent you an email.

Here's an example on how to mask a Sprite:
https://codepen.io/inlet/pen/cac93cf4d47c26ba2511801b75e652b8

Please let me know if this answers your question.

Thanks!

**Comment by romanstan1** [comment]
Thank you. It does.
