### ISSUE TITLE
Gradient background

### ISSUE THREAD

**Issue by romanstan1** [inlet/react-pixi#172]
Hey @inlet

Do you know how to make a vertical, linear gradient background to a Stage?

Thanks!
  

### Additional info

- `@inlet/react-pixi` version: 
- `React` version:
- `ReactDOM` version:
- `PIXI` version:

**Comment by inlet** [comment]
Hi @romanstan1 ,

Please use the Github issues for code related bugs/features.
Feel free to mail me if you have any other questions.

Thanks!

ps. Regarding your question, I've sent you an email how you can accomplish this.

**Comment by romanstan1** [comment]
Thank you!

**Comment by tigr1991** [comment]
@inlet, Could you write answer here, please?

**Comment by inlet** [comment]
Hi @tigr1991,

This is not really related to react-pixi, but to PIXI itself.
Unfortunately there is support in the Graphics API to draw gradients.

There are 2 things you could do:

1. Create an offscreen canvas to draw the gradient and use PIXI.Texture to wrap it in a texture:
Here's an example: https://codepen.io/inlet/pen/5614dbd8c2bf51f132d1aec1cd6cbf3d?editors=0010

2. This is more complex, is to write a shader that does the gradient.

Hope this helps
