### ISSUE TITLE
Feature request community chat

### ISSUE THREAD

**Issue by EloB** [inlet/react-pixi#173]
Do we have any chat/slack/irc for react-pixi?

Where you can write questions, discuss and talk to other react-pixi developers that doesn't fit as a issue or just want to share best practices?

For instance I would like to talk about `react-spring` like how that could be used combined with `react-pixi`. It's not a "issue" and putting it up on Stackoverflow I think this library is to small to get any response.

**Comment by inlet** [comment]
Hi @EloB 

I've just created a Slack channel (and add the invite link to the docs as well).

[Join us on Slack](https://join.slack.com/t/reactpixi/shared_invite/enQtODY0OTYzNzExMTY5LTU5Yjc0YTFhZWFjNWI5YWExZDY5N2FhODBlNTIyZWUzMGMyMDExYjFmYjBhYzM0ZTM4ZTgwMDJhODRkYWIxYTU)

**Comment by EloB** [comment]
![image](https://user-images.githubusercontent.com/476567/72543478-1528f400-3886-11ea-84c7-735dc82c2722.png)

**Comment by inlet** [comment]
Thanks for pointing out. I’ve updated the invite link

**Comment by sanbornhilland** [comment]
The link is dead again. Funny enough I got here with interest into the same thing as @EloB so I'm curious if the `react-spring` integration got off the ground.

**Comment by inlet** [comment]
Hi @sanbornhilland the link listed on https://reactpixi.org/ should work
