### ISSUE TITLE
How can I use texture.frame?

### ISSUE THREAD

**Issue by sussertod891015** [inlet/react-pixi#175]
### Description

export default function ( props ){
	const { x, y, texture, name, data, } = props;
	console.log( data, name );

	const Rectangle = PixiComponent( 'Rectangle', {
		create: () => new Graphics(),
		applyProps: ( g, _, props ) => {
			console.log( props, 'props' );
			const { x, y, width, height, } = props;

			g.clear();
			g.beginFill( 0xff700b, 1 );
			g.drawRect( x, y, width, height );
			g.endFill();

			texture.frame = g;
		}
	} );

	const frameData = data.frames[ name ].frame;

	return (
		<Container position={[ x, y, ]}>
			<Rectangle x={frameData.x} y={frameData.y} width={frameData.w} height={frameData.h}/>
			<Sprite texture={texture}/>
		</Container>

	);
};

It did not work when I change "x" and "y" in "applyProps", components show the first image all the way
### Additional info

- `@inlet/react-pixi` version: 1.1.11
- `React` version:16.8.6
- `ReactDOM` version:16.8.6
- `PIXI` version:5.2.0

**Comment by inlet** [comment]
Can you please create a codepen/codesandbox example?

**Comment by inlet** [comment]
I'll close this issue for now, please let me know if you think we should reopen this issue.

Here's an example of a custom component icm graphics:
https://codepen.io/inlet/pen/RMLJKm

As you can see the props are passed through correctly.

Btw, you can use react-pixi's [`Graphics.draw`](https://reactpixi.org/components/graphics) as well to achieve something similar.
