### ISSUE TITLE
Cannot change scale mode

### ISSUE THREAD

**Issue by balgruuf** [inlet/react-pixi#178]
There is no way of changing the scale mode from pixi settings.

In my old code I change the scale mode like this

```js
PIXI.settings.SCALE_MODE = PIXI.SCALE_MODES.NEAREST;
```

**Comment by inlet** [comment]
Can you provide an example? You should be able to set the scale mode, here’s a codepen demo: https://codepen.io/inlet/pen/NYazPq

**Comment by balgruuf** [comment]
@inlet my bad. Thanks for the reply

**Comment by inlet** [comment]
No worries, btw here's an example of applying different scale modes to the same image:
https://codepen.io/inlet/pen/267f0bb56683a5d1102911a23ebae76a?editors=0010
