### ISSUE TITLE
Can't access other Context inside components rendered by Stage

### ISSUE THREAD

**Issue by AlexPoirier1** [inlet/react-pixi#184]
### Description
The library appears to be rendering the `Context.Provider` at the root of the virtual DOM instead of as a child to the `Stage` component which makes me unable to access my other providers such as theme provider for anything that is rendered by `Stage`.
![image](https://user-images.githubusercontent.com/7539455/72459447-ce110500-3798-11ea-8c95-c5c3a08d122b.png)
In this screenshot we can see that my app is usually wrapped by `StoreProvider` which holds all my global values but react-pixi rendered it's context provider outside of the app.

### Steps to reproduce

1. Have an app with more than one Context
2. Try to access another Context inside of a component that was rendered by the `Stage` component
3. Notice how it can only access Context values from Pixi's context

### Additional info

- `@inlet/react-pixi` version: 1.1.11
- `React` version: 16.12.0
- `ReactDOM` version: 16.12.0
- `PIXI` version: 5.2.0

**Comment by inlet** [comment]
Related to #77. Limitation by the React Context API. A possible workaround is creating a bridge between the contexts.

If you have think this should be possible and I’m wrong, please contribute by creating a PR. Thanks!

**Comment by AlexPoirier1** [comment]
Thanks for the quick update! However I am not sure I see the limitations you speak of.

I believe I have an idea for a resolution on that issue. I will try something later this week and update with my findings.

**Comment by inlet** [comment]
Awesome! Yes please keep me updated on this

**Comment by inlet** [comment]
Hi @AlexPoirier1, did you find a solution?
