### ISSUE TITLE
Confusing error: PixiFiber does not support text instances.

### ISSUE THREAD

**Issue by mimshwright** [inlet/react-pixi#189]
### Description

While creating a custom component I got the error...

"PixiFiber does not support text instances. Use `<Text /> component` instead."

I found this error very confusing. I thought it meant that you cannot use pixi's Text elements within a custom component and that I should only use <Text /> if I need to create a text-based component. Took me a long time to realize this is just referring to the use of text nodes as children of a component. 

Also, regarding the mention of PixiFiber, I almost posted this on the react-pixi-fiber github because I thought maybe it was a dependency. I then looked more closely and saw it is internal to this project. Since it's not used outside this project, it might be clearer not to reference it in this way. 

Thank you!

### Possible fix:
"react-pixi does not support text nodes as children of a Pixi component. To pass a string value to your component, use a property other than `children`. If you wish to display some text, you can use `<Text text={string} />` instead."

### Steps to reproduce

1. Create a custom component with a children property.
2. Declare an instance of the custom component with a text note as the child. 

### Additional info

- `@inlet/react-pixi` version:  1.2.0
- React version: 16.12.0
- ReactDOM version: 16.12.0
- PixiJS version: 5.2.1

**Comment by inlet** [comment]
Hi @mimshwright,

Thanks for posting this issue. Yes text (string) as child prop is not allowed, maybe we need to add a more appropriate warning.

> Since it's not used outside this project, it might be clearer not to reference it in this way.

What do you mean by reference it?

Thanks

**Comment by inlet** [comment]
React internals regarding reconciliation are called Fiber nodes, see https://blog.logrocket.com/deep-dive-into-react-fiber-internals/ that’s why it’s called ‘PixiFiber’

**Comment by inlet** [comment]
Feel free to create a PR that shows a better warning regarding text nodes, thanks 🙏

**Comment by mimshwright** [comment]
Regarding the name PixiFiber, all that makes sense to me. I just got a little confused because as a user, I wasn't familiar with the sub-components of the package. 

I'll make a PR.
