### ISSUE TITLE
Wrong typing for withFilter

### ISSUE THREAD

**Issue by zenios** [inlet/react-pixi#191]
After the recent changes to withFilter hoc typing where not updated 

filters?: Array<any> 

should be changed to

filters?: { [key: string]: any }

https://github.com/inlet/react-pixi/blob/3132f97a3262641d16d614220b0853bd61082489/index.d.ts#L403

**Comment by inlet** [comment]
Oh you’re right, totally forgot to update the type def

Will update these later today, thanks for pointing out

**Comment by inlet** [comment]
🙌 Just pushed a patch (`v1.2.2`), typings are now working as expected! 

1. With correct Wrapper component props:

![image](https://user-images.githubusercontent.com/232559/75338174-96fd3b80-588e-11ea-9c03-08afe743ea70.png)

> in this case the `Container`

2. And with correct filter props:

![image](https://user-images.githubusercontent.com/232559/75338348-daf04080-588e-11ea-82e4-122d9af5c7d3.png)
