### ISSUE TITLE
Cannot restart AnimatedSprite

### ISSUE THREAD

**Issue by zenios** [inlet/react-pixi#197]
With the recent changes
https://github.com/inlet/react-pixi/blob/0140c253877e0727603320c9606deb103084381b/src/components/AnimatedSprite.js#L20

There is not way to start the animation from the beginning.

I have to manualy mount / unmount component

**Comment by inlet** [comment]
I believe this is hard to achieve without writing imperative js. Can you tell me how the API should look like? Maybe get rid of the `initialFrame` and add `startFrame` ad/or `endFrame`? If `startFrame` is set then the `isPlaying=true` starts from that frame?

**Comment by zenios** [comment]
In my opinion when initialFrame is provided is like specifiying that when start go to that frame when stop also go to that frame.

If initial frame is not provided then we can use the default which is what you have now.

**Comment by ldd** [comment]
I'd also like to know how to handle this. I ended up using a ref:

```jsx
    <AnimatedSprite
      isPlaying
      loop={false}
      // NOTICE ME
      ref={a => a?.gotoAndPlay(0)}
      onComplete={someFunction}
      textures={textures}
    />
```

Let me know if there's a better way

**Comment by inlet** [comment]
Use `initialFrame`

```jsx
<AnimatedSprite
  isPlaying={true}
  textures={frames}
  initialFrame={0}
  loop={false}
  onComplete={someFunction}
/>
```
