### ISSUE TITLE
Remove componentWillMount

### ISSUE THREAD

**Issue by zenios** [inlet/react-pixi#198]
Unsafe_componentWIllMount warns when running under strict mode.
https://github.com/inlet/react-pixi/blob/6617cbd4b8f2e9f3a0b1eefbfd38f0a5f6a1d801/src/stage/index.js#L104

I understand that its there just for checks but its better to be removed and either move the invariant to the constructor or componentDidMount

**Comment by inlet** [comment]
You’re right! Feel free to create a PR 👌
