### ISSUE TITLE
Typedefs issue

### ISSUE THREAD

**Issue by zenios** [inlet/react-pixi#203]
After the latest update to typedefs i keep getting errors

![Screenshot from 2020-03-28 20-15-11](https://user-images.githubusercontent.com/89569/77830420-f621ca80-7130-11ea-9d25-97b12b6124a1.png)

**Comment by inlet** [comment]
Oh I haven’t type tested the `anchor` will look into it as soon as possible, thanks!

**Comment by spassvogel** [comment]
`anchor={new PIXI.Point(0.5, 0.5)}` does that work?

**Comment by zenios** [comment]
Yes

**Comment by inlet** [comment]
I'll push a fix later today! Thanks for testing it @zenios

**Comment by inlet** [comment]
Fixed in `v1.2.9`
