### ISSUE TITLE
Pixi viewport

### ISSUE THREAD

**Issue by spassvogel** [inlet/react-pixi#204]
Hi, great work on the library. It looks very promising so far.

one thing I've been wondering is how would I go about implementing something like 'pixi-viewport' (https://github.com/davidfig/pixi-viewport) using react-pixi?

**Comment by ygorlf** [comment]
Hi @spassvogel, you can find a example here: #143

**Comment by spassvogel** [comment]
Great! Thanks. I got it working! 

A small thing, to use the `useApp` hook I had to create a wrapping functional component. I was wondering if it would be possible to get a reference to the `PIXI.Application` (app) from within the `PixiComponent` directly? if not, it's not a huge deal, again, it's working like this.

```
import React from "react";
import { Viewport as PixiViewport} from "pixi-viewport";
import { PixiComponent } from "@inlet/react-pixi";
import { useApp } from '@inlet/react-pixi'

interface Props {
  children: React.ReactNode;
  screenWidth: number,
  screenHeight: number,
  worldWidth: number,
  worldHeight: number,
}

const Viewport = (props: Props) => {
  const app = useApp();
  return <PixiComponentViewport app={app} {...props} />;  
};

interface PixiComponentProps {
    app: PIXI.Application;
}

const PixiComponentViewport = PixiComponent("Viewport", {
  create: (props: PixiComponentProps & Props) => {
    const viewport = new PixiViewport({
      screenWidth: props.screenWidth,
      screenHeight: props.screenHeight,
      worldWidth: props.worldWidth,
      worldHeight: props.worldHeight,
      ticker: props.app.ticker,
      interaction: props.app.renderer.plugins.interaction 
      // the interaction module is important for wheel to work properly when renderer.view is placed or scaled
    });
    //viewport.on("drag-start", () => console.log("drag-start"));
    //viewport.on("drag-end", () => console.log("drag-end"));

    viewport
      .drag()
      .pinch()
      .wheel()
      .clamp({ direction: 'all' })
      .clampZoom({ minScale: 0.5, maxScale: 1 })
      .decelerate();

    viewport.clamp({ direction: 'all' });

    return viewport;
  },
  applyProps: (instance, oldProps, newProps) => {
    console.log("applyProps");
  },
  didMount: () => {
    console.log("didMount");
  },
  willUnmount: () => {
    console.log("willUnmount");
  }
});
export default Viewport;

```

**Comment by ygorlf** [comment]
@spassvogel, I use the same way, creating a wrapper functional component

**Comment by spassvogel** [comment]
Okay thanks!

**Comment by inlet** [comment]
@spassvogel unfortunately you cannot access the `PIXI.Application` in your `PixiComponent`. Having a wrapper is a solid solution though. 

I'll close this issue as the suggestion solution works. 

Thanks!

**Comment by Heilemann** [comment]
@spassvogel Can you show what your usage of this implementation looks like? I'm trying to get it running but so far it renders, but there's no interaction on the viewport as far as I can tell.

**Comment by cjds** [comment]
@Heilemann I just tried the exact implementation and it works including dragging. A caveat maybe not mentioned is that the dragging doesn't seem possible if all the elements are in the part of the viewport you can see on screen
