### ISSUE TITLE
Need not-bundled module for compatibility

### ISSUE THREAD

**Issue by cometkim** [inlet/react-pixi#207]
Hi @inlet, Thank you for the nice library!

I'm really having fun with PIXI.js in React syntax :D

# Description

react-pixi will be broken when using `react@experiemental`.

![image](https://user-images.githubusercontent.com/9696352/78297738-2cb17800-756b-11ea-9327-3edb4929c3a9.png)

because some internal signatures on React have [recently been changed](https://github.com/facebook/react/commit/2ba43edc2675380a0f2222f351475bf9d750c6a9)

So I wanna change the resolution of react for modules avoiding issues, but cannot do that for react-pixi, because another version of React internal (shared) already bundled in by react-reconciler dependency.

Can you provide the module without bundling? just babel transpile would enough for these cases.

Maybe my configuration would help: https://github.com/cometkim/cometjs/blob/master/packages/core/package.json

### Steps to reproduce

1. `yarn add react@experimental react-dom@experimental`
2. render stage

### Additional info

- `@inlet/react-pixi` version: 1.2.10
- `React` version: v0.0.0-experimental-d7382b6c4
- `ReactDOM` version: v0.0.0-experimental-d7382b6c4
- `PIXI` version: 5.2.1

**Comment by cometkim** [comment]
FYI, I made [a fork](https://github.com/devsisters/react-pixi) to experiment react-pixi with concurrent react, suspense for resource loaders, etc.

**Comment by inlet** [comment]
Hi @cometkim 

Thanks, would love to see a PR once you have a fix  :)
Yes, the `react-reconciler` updates quite often and is always a step ahead of React stable version.

If you are not able to make it work as you suggested, we can always create a npm dist `@experimental` for this.

**Comment by cometkim** [comment]
Sure, I will post here if I make anything in the folk :)

I'm currently managing a separate bundle in the folk. unbundled version works strangely in Webpack.
