### ISSUE TITLE
Allow DOM element via Portal

### ISSUE THREAD

**Issue by cometkim** [inlet/react-pixi#209]
### Description

Hi again! I'm currently doing research using react-pixi, and it works pretty well :)

However, I wanna build a UI layer separately using ReactDOM and communicating via custom Portal element.

Building UI in DOM and CSS is a good way to build responsive, constraint UI. But react-pixi seems doesn't allow ~~dom element~~ only text nodes inside of `<Stage/>`.

Is it possible to allow elements wrapped in Portal as an exception? Or provide prebuilt UI Portal?

**Comment by cometkim** [comment]
I've confirmed that we can use it as intended by simply adding a handle to createTextInstance.

The rootContainerInstance is passed to the dom node as is passed to ReactDOM.createPortal(), so I can use ReactDOM's implementation if the node is DOM element.

**Comment by inlet** [comment]
Awesome, feel free to create a PR. Thanks!

**Comment by cometkim** [comment]
I have tried yesterday, for all interfaces accessible via React and ReactDOM internals but I haven't found a way to delegate the remaining work to ReactDOM. (It was only possible to get rid of the error.)

It doesn't seem to be implemented yet.

https://github.com/facebook/react/issues/13332

This issue is an important part of the custom renderer usability, so I need to keep following.

there are a couple of potentially possible ways to use DOM in react-pixi:
- Embedding tiny reconciler implementation of DOM rendering.
- Notify every change to external ReactDOM through "Bridge".

But closing this because I don't think these are react-pixi's.

**Comment by inlet** [comment]
Bummer, yes I think the "Bridge" option might be a good fit.  Keep me posted once you've found a good solution.

Thanks!

**Comment by cometkim** [comment]
@inlet Just implemented a simple bridge to outside root, and works well 👍 

https://github.com/devsisters/react-pixi#ui-portal

I'll post a codepen demo soon after modifying the deployment settings a bit.

**Comment by cometkim** [comment]
Hmm... context or suspense still doesn't work via a bridge. I'm still looking for a way to pass it from React internals.

**Comment by inlet** [comment]
Context simple doesn’t work, this is a limitation of the React Context API. Not sure if the Suspense API is part of ReactDOM, but my first guess would be that is should work with custom renderers

**Comment by cometkim** [comment]
https://codesandbox.io/s/react-pixi-portal-lsgh1?file=/src/index.js

@inlet I added shared context implementation for the Portal API.

Demo: https://codesandbox.io/s/react-pixi-portal-lsgh1?file=/src/index.js

```tsx
import React from "react";
import ReactDOM from "react-dom";
import { Portal, createBridge } from "@devsisters/react-pixi";
import { CountContext } from "./countContext";

const $uiRoot = document.getElementById("ui-root");
const uiRoot = ReactDOM.createRoot($uiRoot);
const uiBridge = createBridge(uiRoot, {
  sharedContext: [CountContext],
});

const UIPortal = ({ children }) => {
  return <Portal bridge={uiBridge}>{children}</Portal>;
};

export default UIPortal;
```

So users can optionally specify the contexts to "capture" on the bridge, and these context values will automatically be forwarded when rendering.

**Comment by inlet** [comment]
Nice work @cometkim !

**Comment by cometkim** [comment]
There are some limitations in reading the context.

- As long as it is done (semi-)automatically, it might not be optimized through observedBits.
- Context values can only be read during component (portal) rendering (cannot be any other place like inside hooks, etc.)

I am wondering if there is a better interface than this. @inlet Do you have any opinion here?
