### ISSUE TITLE
Pixi react how to create Sprite component with a polygon as texture

### ISSUE THREAD

**Issue by Camelot93** [inlet/react-pixi#210]
I am trying to create a sprite component that takes a drawn polygon as texture, how can I achieve this? thanks. Below is a link to what I've posted on stackoverflow

https://stackoverflow.com/questions/61113737/pixi-react-how-to-create-sprite-component-with-a-polygon-as-texture

**Comment by inlet** [comment]
Hi @Camelot93,

Please use Github issues for code related issues, you can ask for these kind of questions in our Slack channel: https://reactpixi.org/#were-on-slack

To answer your question, there are 2 ways:

- Preferred way, use `Graphics` and draw the polygon
- Or if you'd like to map a texture from the graphics, you can use: https://pixijs.download/dev/docs/PIXI.Graphics.html#generateCanvasTexture

**Comment by Camelot93** [comment]
Hello Patrick,

I'm sorry for that, I wasn't aware, Because I will bee implementing
multiple graphics and animating them I believe implementing them as sprites
will optimize its performance ( correct me if I'm mistaken).
Would it be possible to have a small example if it is not asking for too
much, the link you sent is not clear enough.

Thanks

**Comment by inlet** [comment]
I've created an example:

https://codepen.io/inlet/pen/7db008b0c461b3baaa58ff529951f9d1

This one uses an offscreen canvas to generate the texture from.

But an easier way is to use the `PIXI.Graphics` instead and use `cacheAsBitmap`:

```jsx
<Stage>
  <Graphics draw={drawStar} preventRedraw={true} cacheAsBitmap={true} />
</Stage>
```

**Comment by Camelot93** [comment]
Is it as efficient as using sprite, in short, will it support multiple
shapes and will the animation be fast?

I'm asking this because I have read this lately


*Use with caution, the draw method is costly. If the component needs to
update frequently it might be better to use a cached texture instead.*

*Make sure to call g.clear() if you'd like to redraw the graphics.
Alternatively, you can set preventRedraw to true to force the component to
be drawn only once*


*link:*https://reactpixi.org/components/graphics


it does say to use cached texture instead so I really want to make sure
that this can be optimized fully since I am on the verge of building a
heavy software.

Please let me know what you think


By the way thanks a lot for the effort I truly appreciate it :)

**Comment by Camelot93** [comment]
I was just reading this,
I do not know to what extent "element does not change often" is measured,
in my case there are drag and drops, resizes as well as limited animations,
looped animations and sequenced animations

 cacheAsBitmap boolean overrides
<http://pixijs.download/dev/docs/PIXI.Container.html#cacheAsBitmap>

When cacheAsBitmap is set to true the graphics object will be rendered as
if it was a sprite. This is useful if your graphics element does not change
often, as it will speed up the rendering of the object in exchange for
taking up texture memory. It is also useful if you need the graphics object
to be anti-aliased, because it will be rendered using canvas. This is not
recommended if you are constantly redrawing the graphics element.

**Comment by inlet** [comment]
> Is it as efficient as using sprite, in short, will it support multiple
shapes and will the animation be fast?

Yes.

> I do not know to what extent "element does not change often" is measured,
in my case there are drag and drops, resizes as well as limited animations,
looped animations and sequenced animations

It refers to redrawing a `Graphics` instance. For sequenced animations I'd suggest using an `AnimatedSprite` instead.

**Comment by Camelot93** [comment]
Thanks a lot Patrick thats really nice of you, I hope you don't mind if I
keep your contact, its my 4th day learning Pixi I've just been programming
for a year now and with this project I will be having a lot on my hands.

**Comment by Camelot93** [comment]
Sorry to disturb you again Patrick but using cachedBitmap prevents
options={{resolution}} from working, is there a workaround?
