### ISSUE TITLE
Lifetime of PIXI app

### ISSUE THREAD

**Issue by spassvogel** [inlet/react-pixi#211]
Hello,

What is the lifetime of the PIXI.Application in `react-pixi`? Does it get created when a `<Stage>` element is mounted? Is there some way to persist it?

https://codepen.io/spassvogel/pen/gOaOWZR?editors=1111

I'm wondering because in my app  I'm creating and tearing down PIXI stages all the time. It would be nice to persist the loader cache for example. This pen seems to suggest there is a new PIXI.Application on each mount, because ` app.loader.resources[spritesheet]` returns `undefined` after toggling the stage off and on. 

But then I do get this warning , 

`BaseTexture added to the cache with an id [https://pixijs.io/examples/examples/assets/spritesheet/fighter.json_image] that already had an entry`

 which seems to contradict that?

**Comment by inlet** [comment]
Hi @spassvogel 

As you can see in the source:

https://github.com/inlet/react-pixi/blob/69781938004cb58ed2e4c85034b51d2b180306e2/src/stage/index.js#L105-L110

the `PIXI.Application` is created on mount and killed on unmount. Use [custom options](https://pixijs.download/dev/docs/PIXI.Application.html) to your needs. 

If you'd like to persist the loader cache, I'd suggest to use the shared loader instead (see options).

**Comment by spassvogel** [comment]
Thanks! Setting `sharedLoader` to `true` did the trick.
