### ISSUE TITLE
(typescript) expose IContainer

### ISSUE THREAD

**Issue by spassvogel** [inlet/react-pixi#212]
Im using typescript to create a new PixiComponent. However I can't figure out how to set the types of the Pixi component I'm exposing.

Here I have my `ParticleEmitter`, it's on top of a `PIXI.ParticleContainer` so I want  all the properties of `Props` and `PIXI.ParticleContainer` to be known. I got it to work by duplicating the types `PointLike`, `WithPointLike`, `InteractionEvents`, `Container` and `IContainer` from the react-pixi typings but I'm thinking it would be much easier if I could just import those from 'react-pixi'. Or is there some other way?

```
interface Props {
    image: string;
    config: particles.OldEmitterConfig | particles.EmitterConfig;
}

type PointLike = PIXI.Point | PIXI.ObservablePoint | [number, number] | [number] | number;
type WithPointLike<T extends keyof any> = { [P in T]: PointLike };
type InteractionEvents = {
  [P in PIXI.interaction.InteractionEventTypes]?: (event: PIXI.interaction.InteractionEvent) => void;
};
type Container<T extends PIXI.DisplayObject> = Partial<Omit<T, 'children'>> &
Partial<WithPointLike<'position' | 'scale' | 'pivot' | 'anchor'>> &
InteractionEvents;
type IContainer = Container<PIXI.ParticleContainer>;

const ParticleEmitter = PixiComponent<Props & IContainer, PIXI.ParticleContainer>("ParticleEmitter", {
    create() {
      return new PIXI.ParticleContainer();
    },

    applyProps(instance, oldProps: Props, newProps: Props) {
      const { image, config, ...newP } = newProps;
  
      // apply rest props to PIXI.ParticleContainer
      applyDefaultProps(instance, oldProps, newP);
    }
```

**Comment by cometkim** [comment]
@spassvogel You can extract the props type from the component definition.

Here's example:
```ts
type OverrideProps<T1, T2> = Omit<T1, keyof T2> & T2;
type PropsOf<T> = T extends React.ComponentType<infer P> ? P : never

type PaticleEmitterProps = OverrideProps<PropsOf<typeof Container>, {
    image: string;
    config: particles.OldEmitterConfig | particles.EmitterConfig;
}>;

PixiComponent<ParticleEmitterProps, ...>()
```

Or use a type library for it `yarn add @cometjs/react-utils`

https://github.com/cometkim/cometjs/blob/master/packages/react-utils/src/common.ts

**Comment by spassvogel** [comment]
Thanks @cometkim !

**Comment by inlet** [comment]
@spassvogel 

That does work indeed. Actually @cometkim type `PropsOf` is so commonly used that React has this baked in (does practically the same): 

```ts
type ContainerProps = React.ComponentProps<typeof Container>;
```
