### ISSUE TITLE
TypeScript IntrinsicElements

### ISSUE THREAD

**Issue by cometkim** [inlet/react-pixi#213]
### Description

I recently working on improving React library type definition on DefinetlyTyped. 

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43759

And this also affects react-pixi.

TypeScript has its own logic that references the IntrinsicElements declaration for host elements. So custom renderers should provide a definition for the default tag provided by host under `JSX.IntrinsicElements`.

After those changes are merged and react-pixi provides the `JSX.IntrinsicElements`, so utility types like `React.ElementRef<T>` are additionally compatible.

**Comment by inlet** [comment]
Hi @cometkim 

Can you point out what should be fixed in react-pixi? 

Thanks

**Comment by cometkim** [comment]
@inlet react-pixi should provide information about host elements under JSX.IntrinsicElements namespace.

for example:

```ts
declare global {
  namespace JSX {
    interface IntrinsicElements {
      // Consider replace host elements name to cameCase instead of CapitalCamelCase
      // Just a pseudo code
      Container: ReactPIXI.ContainerProps & React.RefAttributes<ReactPIXI.ContainerClass>;
      Sprite: ReactPIXI.SpriteProps & React.RefAttributes<ReactPIXI.SpriteClass>;
      ...
    }
  }
}
```

So ts user can use `ElementRef<typeof Container>` to infer `ReactPIXI.ContainerClass` instance type. (and more use cases available with intrinsic types)

For more information: https://www.typescriptlang.org/docs/handbook/jsx.html#intrinsic-elements

**Comment by cometkim** [comment]
An example in react-three-fiber: https://github.com/react-spring/react-three-fiber/blob/9b18a52fef/src/three-types.ts#L65-L293

**Comment by cometkim** [comment]
Using a ref in react-pixi seems to give the pixi object, not a react element. It is better to provide such information through type.

**Comment by inlet** [comment]
Hi @cometkim,

Thanks for pointing out.

However there's a difference in comparison with the react-three-fiber lib. 

By declaring the `IntrinsicElements` you don't have to import the named JSX and elements will be automatically be resolved based on its type:

Example `react-three-fiber`:

```tsx
import ReactDOM from 'react-dom'
import React from 'react'
import { Canvas } from 'react-three-fiber'

ReactDOM.render(
  <Canvas>
    <ambientLight />
    <pointLight position={[10, 10, 10]} />
    <Box position={[-1.2, 0, 0]} />
    <Box position={[1.2, 0, 0]} />
  </Canvas>,
  document.getElementById('root')
)
```

> `ambientLight`, `pointLight`, `Box`, etc are have typed support via the `IntrinsicElements` but are not imported via ES module import.

However, with `react-pixi` you need to import them, there are no `IntrinsicElements`:

```tsx
import { Container, Sprite } from '@inlet/react-pixi';
const App = () => (
  <Container x={200}>
    <Sprite x={123} anchor={0.5} />
  </Container>
);
```

Correct me if I'm wrong, but I believe there's no need for `IntrinsicElements`declaration for `react-pixi` at the moment. Although maybe it would be a nice addition to support it in the future so you wouldn't need to import it manually.

**Comment by cometkim** [comment]
React uses IntrinsicElements for more purposes. For example:

```tsx
import React from 'react';
import { Container, Sprite } from '@inlet/react-pixi'

const App = () => {
  // This will be `never` at this moment.
  const containerRef = React.useRef<React.ElementRef<typeof Container>>(null);
  React.useEffect(() => {
    if (containerRef.current) {
      return;
    }

    // $ExpectType ???
    console.log(containerRef.current);
  }, []);

  return (
    <Container ref={containerRef} x={200}>
      <Sprite x={123} anchor={0.5} />
    </Container>
  );
}; 
```

Here, the "real" type of ref seems to be a `PIXI.DisplayObject` instance (I'm not sure if it's what you intended).

![image](https://user-images.githubusercontent.com/9696352/79116093-882d0280-7dc2-11ea-9ceb-d139aa588408.png)


This will be good to be documented and type definitions are better.

**Comment by inlet** [comment]
Maybe it's my lack of knowledge, but isn't a React `ref` for retrieving the actual instance? For ReactDOM it refers to the actual DOM element as for React-Pixi it's the actual PIXI instance.

You're right about the `useRef` part, is it as simple as adding the types to `IntrinsicElements` to solve this? Can you make a PR? 

Thanks!

**Comment by cometkim** [comment]
> Maybe it's my lack of knowledge, but isn't a React ref for retrieving the actual instance? For ReactDOM it refers to the actual DOM element as for React-Pixi it's the actual PIXI instance.

It is right because of the <Container> is the "Intrinsic elements" for react-pixi, not just a regular class/functional component (except <Stage>?) but react-pixi's components use regular module syntax for its usage, so I think it's a bit confusing.

> Can you make a PR?

Yeah, I will file a PR for it after the DefinitelyTyped/DefinitelyTyped#43759 being merged.

**Comment by inlet** [comment]
Awesome, thanks

**Comment by ferdaber** [comment]
You cannot add JSX constructors that resolve to value types (instead of strings)  into `IntrinsicElements`. What @inlet said is correct that if you need to import `Container`, it cannot go into `IntrinsicElements` because TypeScript will never look there for props comparison.

**Comment by cometkim** [comment]
> if you need to import Container, it cannot go into IntrinsicElements because TypeScript will never look there for props comparison.

@ferdaber But I still can type check for props using imported `Container` class, and React use IntrinsicElements for ElementRef right?

```tsx
import React from 'react';
import { Container } from '@inlet/react-pixi';

const ref = React.useRef<React.ElementRef<typeof Container>>(null);

<Container ref={ref} />
```

My goal is just to get this to work and react-pixi should provide IntrinsicElements for this case.

I'm referring here to more use cases of the IntrinsicElements in React, not the original intent. I think not only TypeScript core, but also React definitions would use IntrinsicElements more for utility types.

**Comment by cometkim** [comment]
I'm wondering how RN is dealing with this.

**Comment by inlet** [comment]
I'm closing this issue as `IntrinsicElements` do not apply for `react-pixi`. 

There's no way you can get `PIXI.Container` from the imported `Container` as the Container only include JSX props and is not aware of any PIXI instance.

This is how you can use refs:

```jsx
import React, { useRef } from 'react';
import { Container } from '@inlet/react-pixi';
import { Container as PIXIContainer } from 'pixi.js';

const App = () => {
  const containerRef = useRef<PIXIContainer>(null);

  return (
    <Container ref={containerRef} />
  );
};
```

**Comment by inlet** [comment]
Please let me know if you have a solid solution and we can reopen this issue.

Thanks!

**Comment by ferdaber** [comment]
@inlet when passing a ref into `Container` from react-pixi, do you get the component instance, or the instance of `PIXIContainer`? I saw in the type definitions that `Container` is a class component, so if the reconciler is similar to react-dom, then I figured that you get the component instance 🤔 

Given the above, in runtime wouldn't your above example actually give you an instance of `Container` instead of `PIXIContainer` in the ref?

**Comment by cometkim** [comment]
Ok... I didn't expect to bind PIXI types manually, but please give me a good place to document it. I will send a PR.

I still believe that type definition is a good place to clarify it. You can also hide internal props like `addChild` and `destroy` that probably break the reconciler.

**Comment by cometkim** [comment]
![image](https://user-images.githubusercontent.com/9696352/79243720-f9e37a00-7eb0-11ea-8f3e-27bccf639c04.png)

And the example will gonna fail type checking anyway.

**Comment by inlet** [comment]
> Ok... I didn't expect to bind PIXI types manually, but please give me a good place to document it. I will send a PR.

Sure, if you know how we can make this work!

**Comment by inlet** [comment]
> @inlet when passing a ref into Container from react-pixi, do you get the component instance, or the instance of PIXIContainer? I saw in the type definitions that Container is a class component, so if the reconciler is similar to react-dom, then I figured that you get the component instance 🤔

Given the above, in runtime wouldn't your above example actually give you an instance of Container instead of PIXIContainer in the ref?

The class comp in type def is just to support JSX types, as this is a custom renderer ref always returns PIXI instances

**Comment by cometkim** [comment]
@ferdaber Container is not actually a React.Component in react-pixi, it's PIXI.Container in runtime but using the component type definition for faking JSX intrinsic.

**Comment by ferdaber** [comment]
I'm more investigating what the actual type is, and just by running the codepen examples, it seems that the emitted ref type is actually a `<container>` DOM element. Some of the other components do not emit refs at all (not even invoking the ref callback that I pass in), and others are emitting class instances. So it seems to be inconsistent depending on the component. That said, even shoving the types into `IntrinsicElements`, the types are incorrect as they are now.

Sample code:
![image](https://user-images.githubusercontent.com/12239873/79244994-7f314500-7e45-11ea-87c7-e25674aa72f3.png)

Logged ref emissions (note how `BasicText` and `RichText` do not emit their refs):
![image](https://user-images.githubusercontent.com/12239873/79245037-8fe1bb00-7e45-11ea-9520-4ca3464ffa1e.png)

**Comment by cometkim** [comment]
Weird, because it was PIXI.DisplayObject in my test above

https://github.com/inlet/react-pixi/issues/213#issuecomment-612856703

**Comment by ferdaber** [comment]
In the example of your previous comment, are you using react-dom or the custom reconciler?

**Comment by inlet** [comment]
@ferdaber:

Stage is the only component that does render a `canvas` element as this is the root and rendered in ReactDOM. From there the custom renderer (react-pixi) takes over..

and all components return their PIXI instance. Just check out the codepen examples.

**Comment by cometkim** [comment]
> Sure, if you know how we can make this work!

Like I said, after https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43759 merged, extends JSX.IntrinsicElements and It will work.

Another remaining work is to find out all the types returned in the actual runtime.

**Comment by ferdaber** [comment]
Oh I see it now, I didn't realize in the examples the `Text` components were wrapped in functions.

Anyways, I disagree with adding these into `JSX.IntrinsicElements` but that's the prerogative of this library's maintainers (since these are augmentations anyways).

One issue I do see is that all of these components in this current library's type definitions are defined as classes which will conflict with how refs are checked for class components, so they will likely need to be redefined as function components with refs inside their props that point to their respective PIXI instances.

```ts
// how it's currently defined
export class Text extends React.Component<_ReactPixi.IText> {}

// if you inspect the type of `ref` you will see that it's actually `Text` instead of `PIXI.Text`
const text = <Text ref={} />

// how it should be defined
export function Text(props: _ReactPixi.IText & { ref?: React.Ref<PIXI.Text> }): JSX.Element

// or augment the `_ReactPixi.Container` inferface, whatever works:
namespace _ReactPixi {
  interface Container<T> {
    ref?: React.Ref<T>
  }
}
```

**Comment by inlet** [comment]
@ferdaber thanks! Will look into it

**Comment by inlet** [comment]
@ferdaber just pushed a patch:

https://github.com/inlet/react-pixi/blob/eebbf7657258b83e1ef9548e0f2457616962cb80/index.d.ts#L254-L264

Does work now!

![image](https://user-images.githubusercontent.com/232559/79323284-48733180-7f0e-11ea-9616-1c28d8900c8f.png)

**Comment by inlet** [comment]
@cometkim & @ferdaber 

I also added support for getting the ref instance via `PixiRef`:

https://github.com/inlet/react-pixi/blob/1ecc964d375cd2d070a432e2015eb1e72e3b0416/index.d.ts#L411-L413

![image](https://user-images.githubusercontent.com/232559/79327115-33010600-7f14-11ea-95bb-656e6c4aec63.png)

**Comment by ferdaber** [comment]
@inlet thank you for the changes, I'm assuming your test environment above is not using strict nulls?

Also the new `PixiRef` helper type may not be necessary with @cometkim's latest update to React's own types, they can just use `React.ElementRef<typeof Container>` and it should work just fine.

**Comment by inlet** [comment]
@ferdaber yes strict null checks are enabled, why?

> Also the new PixiRef helper type may not be necessary with @cometkim's latest update to React's own types, they can just use React.ElementRef<typeof Container> and it should work just fine.

Ah cool! Looking forward to the update, when is it available?

**Comment by ferdaber** [comment]
> @ferdaber just pushed an update:
> 
> https://github.com/inlet/react-pixi/blob/eebbf7657258b83e1ef9548e0f2457616962cb80/index.d.ts#L254-L264
> 
> ![image](https://user-images.githubusercontent.com/232559/79323284-48733180-7f0e-11ea-9616-1c28d8900c8f.png)

The inferred type of `c` in your screenshot is `PIXI.Container` but it should be `PIXI.Container | null`.

**Comment by inlet** [comment]
I've updated the `PixiRef` and it works with `"strictNullChecks": true` as well.

![image](https://user-images.githubusercontent.com/232559/79458402-09b6a780-7ff2-11ea-8347-4d0dc91ff2f2.png)

Any ideas when `React.ElementRef` works with this?

**Comment by ferdaber** [comment]
It should actually just work in its current version just by inspecting the changes you made to your own types. Did you try it out?

**Comment by inlet** [comment]
Unfortunately `React.ElementRef<typeof Container>` does not work. It returns `undefined`

**Comment by inlet** [comment]
Anyway, I'll leave the type `PixiRef` as it does work as it should be

**Comment by ferdaber** [comment]
Oh congrats! You found an unrelated bug in `React.ElementRef` 😅 I'll have to fix that.
