### ISSUE TITLE
Typescript issues in 1.2.17

### ISSUE THREAD

**Issue by spassvogel** [inlet/react-pixi#215]
Two things stand out to me in the 1.2.17 release,

1. `export const Sprite: _ReactPixi.ChildlessFC<_ReactPixi.ISprite>;`

It seems to me that a Sprite can have children, no? https://pixijs.download/dev/docs/PIXI.Sprite.html#addChild

2. `  type IGraphics = Container<PIXI.Sprite> & { `

This should be `Container<PIXI.Graphics>` I think.

**Comment by inlet** [comment]
Oops you are totally right, do you have time for a PR? Else I can update it tomorrow

**Comment by spassvogel** [comment]
Yeah working on it now. Actually I think all the pixi components can have children?

**Comment by inlet** [comment]
Yes I believe you’re right. Change them all and remove the `Childless` type entirely

**Comment by spassvogel** [comment]
#216

**Comment by inlet** [comment]
I’ll merge it tomorrow morning

**Comment by spassvogel** [comment]
Good night and thx!
