### ISSUE TITLE
Incorrect render for repeated pointerover/pointerout

### ISSUE THREAD

**Issue by lewispeel** [inlet/react-pixi#217]
### Description

I've create a very simple application with a custom component that changes colour when you hover over it. If you hover over then off the component everything is fine for the first 12 times but on the 13th the colour states are reversed. It's very strange... not sure if I'm doing something wrong but it's probably the simplest component I could make!

Here's a Codepen demonstrating the issue: https://codepen.io/lewispeel/pen/RwWpbEG

### Steps to reproduce

1. Create a new react app using `yarn create react-app test`
2. Install Pixi.js and ReactPixi
3. Create a simple button component that is red for `pointerout` and green for `pointerover` (see below)
4. Keep hovering over and off the button until the colours are broken (green for `pointerout` and red for `pointerover`)
5. Keep hovering and eventually it'll change back.

```
// app.js

import React from 'react';
import { Stage } from '@inlet/react-pixi';
import Button from './Button';

function App() {
  return (
    <Stage>
      <Button x={100} y={100} width={100} height={100} />
    </Stage>
  );
}

export default App;
```

```
// Button.js

import React, { useReducer } from 'react';
import { Container, Graphics } from '@inlet/react-pixi';

const BG_UP = 0xCC0000; // red
const BG_OVER = 0x00CC00; // green

const initialState = { bgColor: BG_UP };

function reducer(state, action) {
  switch (action.type) {
    case 'over':
      return { ...state, bgColor: BG_OVER };
    case 'out':
      return { ...state, bgColor: BG_UP };
    default:
      throw new Error();
  }
}

export default props => {
  const [state, dispatch] = useReducer(reducer, initialState);

  return (
    <Container
      x={props.x}
      y={props.y}
      buttonMode={true}
      interactive={true}
      pointerover={e => dispatch({ type: 'over' })}
      pointerout={e => dispatch({ type: 'out' })}
    >
      <Graphics
        draw={g => {
          g.beginFill(state.bgColor);
          g.drawRect(0, 0, props.width, props.height);
          g.endFill();
        }}
      />
    </Container>
  )

};
```

I've tried writing the button component with useReducer and useState but both result in the same error.

### Additional info

- `@inlet/react-pixi` version: 1.2.18
- `React` version: 16.13.1
- `ReactDOM` version: 16.13.1
- `PIXI` version: 5.2.2

**Comment by inlet** [comment]
This is the expected behavior. 

The `draw` call gets executed every frame, make sure to clear it first before redrawing.

**Comment by inlet** [comment]
Keep in mind that this might be an expensive operation as it gets drawn every frame. There's a PR with a fix to render it based on the React cycle here: #187

**Comment by lewispeel** [comment]
Ah ok, thanks for the explanation!
