### ISSUE TITLE
Change to container definition breaks textStyle

### ISSUE THREAD

**Issue by zenios** [inlet/react-pixi#219]
With the latest changes to typescript defintions for Container i cannot apply text style any more

![Screenshot from 2020-05-07 12-56-55](https://user-images.githubusercontent.com/89569/81281378-6f7ed800-9062-11ea-9cbc-2ac95cf6104a.png)

**Comment by aktriver** [comment]
I’m having the same problem since v1.2.19.
v1.2.18 is ok.

This commit may be causing.
https://github.com/inlet/react-pixi/commit/18a8fc7ffe411ace9fa0f181f032c009ee3eafe7

**Comment by inlet** [comment]
Thanks for letting me know, will look into this today! You can expect a fix soon

**Comment by aktriver** [comment]
Thanks.
I found that `FunctionType<IText>` returns “style”.

**Comment by inlet** [comment]
Thanks @aktriver 

![image](https://user-images.githubusercontent.com/232559/81405590-403a9a80-9138-11ea-8ab0-9fecdab7a472.png)

The idea of removing all Function members does not work if a type is assigned to `any`.
No clue why they add the `any` type here though.

Anyways, I'll remove the FunctionTypes check entirely to make it work.

**Comment by inlet** [comment]
Just pushed a fix
