### ISSUE TITLE
Reconciler implemented improperly?

### ISSUE THREAD

**Issue by AskAlice** [inlet/react-pixi#220]
### Description
I've noticed I can't access any contexts within the pixi fiber, and I managed to get this to throw when updating this component as a result of a theme preference change

react-pixi is throwing the ReactError that caused this full page exception

![image](https://user-images.githubusercontent.com/1855905/81303817-76ddbb80-9039-11ea-8619-8b1d9f171269.png)

### Steps to reproduce

this won't reproduce this exact error, but i believe the issues are related
1. add a context outside of the pixi stage
2. useContext within pixi
### Additional info

- `@inlet/react-pixi` version:  ^1.2.3
- `React` version: ^16.13.1
- `ReactDOM` version: ^16.13.1
- `PIXI` version: ^5.2.1

**Comment by inlet** [comment]
Duplicate #77. 

Limitation by the React Context API. A possible workaround is creating a bridge between the contexts.
