### ISSUE TITLE
Errors with latest updates

### ISSUE THREAD

**Issue by zenios** [inlet/react-pixi#229]
Hi i tried react-pixi 4.00 and i get the following errors

```
Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
```

After searching around looks like this issue presents when creating multiple reconcilers which is what react-pixi 4.0 is doing

Here is another project that had the exact same issue. It includes a PR on how they fixed the issue

https://github.com/vadimdemedes/ink/issues/139

Also injectDevtools should change from

```
export function injectDevtools(fiber) {
  fiber.injectIntoDevTools({
    bundleType: process.env.NODE_ENV !== 'production' ? 1 : 0,
    version: REACT_DOM_VERSION,
    rendererPackageName: PACKAGE_NAME,
    findHostInstanceByFiber: PixiFiber.findHostInstance,
  })
}

```
to
```
export function injectDevtools(fiber) {
  fiber.injectIntoDevTools({
    bundleType: process.env.NODE_ENV !== 'production' ? 1 : 0,
    version: REACT_DOM_VERSION,
    rendererPackageName: PACKAGE_NAME,
    findHostInstanceByFiber: fiber.findHostInstance,
  })
}
```

**Comment by inlet** [comment]
Thanks @zenios!

Will look into it :)

**Comment by inlet** [comment]
Thanks! Just pushed a fix and it works now!

**Comment by zenios** [comment]
This is only one part of the problem

There is still an issue with creating multiple reconcilers.

Look at the pr of the other project

**Comment by inlet** [comment]
interesting that there can only be one reconciler 🧐

Will look into it tomorrow and see if I can come up with a solution

**Comment by inlet** [comment]
Pushed a fix, I needed to rewrite some core reconciler logic.

Now it uses the same PixiFiber instance and emits changes via custom events (instead of eventMap handlers).
