### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by filipesmedeiros** [inlet/react-pixi#233]
### Description

Hey! Is there a way to use this with server side rendering? (Next.js for example)

I've tried also checking for the window object before rendering the Stage, but it just does stuff before I even get there.
Even if I do something like `{false && <Stage/>}` it throws that window is undefined, so I can't even use `useEffect` to check if I'm in the browser.

Any help? Thanks!

### Additional info

- `@inlet/react-pixi` version: ^5.0.0
- `React` version: ^16.13.1
- `ReactDOM` version: ^16.13.1
- `PIXI` version: ^5.3.0

**Comment by inlet** [comment]
Wrap a `NoSSR` around it and you’re set:

```jsx
<NoSSR>
  <Stage>
    ...
  </Stage>
</NoSSR>

**Comment by filipesmedeiros** [comment]
Amazing, thanks!

**Comment by filipesmedeiros** [comment]
On a second note, this actually isn't working for me. Wrapper in a `NoSSR` but I still get the error that:

![image](https://user-images.githubusercontent.com/26208850/85187529-19739600-b298-11ea-9151-b94ac6279759.png)

**Comment by inlet** [comment]
Importing PIXI evaluates the window object right away, dynamic importing is the way to go 👍
