### ISSUE TITLE
Typescript error with children

### ISSUE THREAD

**Issue by spassvogel** [inlet/react-pixi#234]
After updating to 6.14.5 I am experiencing a lot of TS issues with embedding react pixi elements within a container

```
(alias) const Container: React.FC<_ReactPixi.Container<PIXI.Container, {}>>
import Container
Type '{ children: ReactNode; x: number; y: number; ref: Ref<Container>; }' is not assignable to type 'InteractionEvents'.
  Property 'children' is incompatible with index signature.
    Type 'ReactNode' is not assignable to type '((event: any) => void) | undefined'.
      Type 'null' is not assignable to type '((event: any) => void) | undefined'.ts(2322)
```

- `@inlet/react-pixi` version: 6.14.5

**Comment by inlet** [comment]
Hi @spassvogel,

The latest version of `@inlet/react-pixi` is `v5.0.0`. 
Can you share your tsconfig?

**Comment by inlet** [comment]
Note that v5 is only compatible with PIXI v5.3+

**Comment by spassvogel** [comment]
Sorry about that. I thought I had updated @inlet/react-pixi but I didnt. Seems to be working now. Apologies

**Comment by inlet** [comment]
Ah, great to hear it's not broken 😓
