### ISSUE TITLE
add custom PIXI.Application passed to Stage

### ISSUE THREAD

**Issue by ldd** [inlet/react-pixi#236]
### Description
Currently, `Stage` creates its own PIXI.Application each time it is mounted. [react-pixi-fiber](https://github.com/michalochman/react-pixi-fiber) lets you pass a PIXI.Application as a parameter.

So my feature request would be to add that possibility

### Additional info

- `@inlet/react-pixi` version:  5.0.1
- `React` version: 16.13.1
- `ReactDOM` version: 16.13.1
- `PIXI` version: 5.2.6

**Comment by inlet** [comment]
👍 Feel free to create a PR, I’ll close this issue as nothing is broken
