### ISSUE TITLE
Why force autoDensity = false on users?

### ISSUE THREAD

**Issue by SukantPal** [inlet/react-pixi#238]
https://github.com/inlet/react-pixi/blob/c049ca6c52bcc765add26c88cf18eec0fca93aac/src/stage/index.js#L122

### Description

We need `autoDensity` to be true, so that calling `app.renderer.resize` works; without it, the renderer will not update the CSS dimensions of the canvas and it will be stuck at 800x600 display-size:

https://github.com/pixijs/pixi.js/blob/30f6033bf1b758c8ad7907bb57f7b8424aebade2/packages/core/src/AbstractRenderer.ts#L272

___
This is keeping us from upgrading to `@inlet/react-pixi@5.0.0`; it would be great if you can provide a workaround or accept a fix :)

**Comment by SukantPal** [comment]
The fix would be to place `autoDensity: false` before expanding the options:

```js
{
  autoDensity: false,
  ...options
}
```

But, it is `false` by default anyway in PixiJS.

**Comment by inlet** [comment]
The reason why the `autoDensity` is set to false is because the interaction manager needs to reset on resolution change.

**Comment by inlet** [comment]
However I totally agree with you that `renderer.resize` should be responsible for changing the width and height including setting the css styles. 

I’ll look into this asap. Thanks!
