### ISSUE TITLE
Plugins API

### ISSUE THREAD

**Issue by SukantPal** [inlet/react-pixi#240]
### Description

I was looking for a way to supply custom plugins for `PIXI.Application` and `PIXI.Renderer`. Do you think this will be a viable feature? I can create a PR for you if we settle the design of it.

I'm the main maintainer of [pixi-batch-renderer](https://github.com/pixijs/pixi-batch-renderer), [pixi-essentials](https://github.com/SukantPal/pixi-essentials), [pixi-ui](https://github.com/pixijs/pixi-ui) and I'd like to provide developers a way to include renderer plugins & systems without using a `ref` callback. Something as follows:

**Batch rendering**:

```jsx
const shaderFn = new BatchShaderFunction(vertexShaderSrc, fragmentShaderSrc, {}).derive();

<Renderer.Plugins> // something like this??
  <BatchRenderer // from @pixi-pbr/react-bindings
      attribSet={[{ ... }, { ... }]}
      indexProperty="indices"
      textureProperty="texture"
      texIDAttrib="aTextureId"
      shaderFunction={shaderFn}
    >

  </BatchRenderer>
</Renderer.Plugins>
```

**Pixi essentials culling:**

```jsx
<Renderer.Systems> // any ideas?
  <CullSystem recursive={true} 
        toggle="visible" 
        screen={app.screen} 
        targets={[app.stage]}> // from @pixi-essentials/react-bindings
                                               // culls display-objects outside of "app.screen"  
  </CullSystem>
</Renderer.Systems>
```

## Issues

How would systems and plugins be separated from normal display-objects? Maybe we can separate out `Renderer.Systems` & `Renderer.Plugins` as "specially handled children" of `Stage`?

We might also want to allow plugins on `PIXI.Application` as well.

**Comment by inlet** [comment]
Hi @SukantPal,

Thanks for reaching out and filing this feature request. I have zero experience with renderer/system plugins, but it seems quite powerful. 

It might be a viable feature, but I'm not sure if it should be embedded in this project. It does come with a layer of complexity, which is something I try to prevent. What do you think? Or maybe as an add-on, you can easily tap into anything with refs.

Looking forward to your reply!

Best Patrick

**Comment by SukantPal** [comment]
@inlet What are we thinking here?

**Comment by inlet** [comment]
Would you be willing to create a PR for this? Thanks!

**Comment by SukantPal** [comment]
Of course. I’ll work on this and see what I can do.

**Comment by inlet** [comment]
Awesome! Thanks for collab on this

**Comment by inlet** [comment]
I'll close this issue for now and reopen it once we work on a PR. Thanks!

**Comment by AdrienLemaire** [comment]
I'm seeing a `@pixi-essentials/react-bindings` package.  @SukantPal Does that mean that you did the integration from your library ?

**Comment by SukantPal** [comment]
@AdrienLemaire I did not actually. That package just contains a &lt;Transformer /&gt; component for the @pixi-essentials/transformer package.
