### ISSUE TITLE
Example code not working

### ISSUE THREAD

**Issue by stanecli** [inlet/react-pixi#241]
### Description
Hi, I just installed the library, hoping it would enhance my new game, only to find out that not even the examples are working.. It could be just a typins issue, but life is too short to figure out other coders' mindset, so please, if you could look at it with latest Create React App + react-pixi and mitigate the issues?

Thanks

### Steps to reproduce

1. `npx create-react-app test`, add pixijs and react-pixi, create a functional component with a react-pixi Container:
```
import React, { FC } from "react";
import { Stage, Container, Graphics } from "@inlet/react-pixi";

const MyComp: FC<Props> = (props) => {
    return (
        <Stage width={640} height={360}>
            <Container>
                <Graphics />
            </Container>
        </Stage>
    );
};

export default MyComp;
```

2. Look for type errors.
`Type '{ children: Element; }' is not assignable to type 'InteractionEvents'.
  Property 'children' is incompatible with index signature.
    Type 'Element' is not assignable to type '(event: any) => void'.
      Type 'Element' provides no match for the signature '(event: any): void'.ts(2322)`

### Additional info

- `@inlet/react-pixi` version: 5.0.3
- `React` version: 16.13.1
- `ReactDOM` version: 16.13.1
- `PIXI` version: 5.3.2

**Comment by inlet** [comment]
Unfortunately I cannot reproduce this issue. 

1. `npx create-react-app my-app --template typescript`
2. `yarn add pixi.js @inlet/react-pixi`
3. create a component `myComponent.tsx`: 

```tsx
import React from 'react';
import { Stage, Container, Graphics } from '@inlet/react-pixi';

const MyComponent = () => {
  return (
    <Stage width={800} height={600}>
      <Container>
        <Graphics />
      </Container>
    </Stage>
  );
};

export default MyComponent;
```

No type errors occur, to verify it's working the typescript compiler doesn't complain either:

`npx tsc -p . --noEmit`

**Comment by inlet** [comment]
> only to find out that not even the examples are working..

Which examples do you refer to?

**Comment by stanecli** [comment]
Thanks for the quick answer. I don't know what happened, but it started working eventually. I guess my IDE was trolling me again.

**Comment by stanecli** [comment]
The library is great btw, I love it. Cheers!
