### ISSUE TITLE
Integration with react-redux

### ISSUE THREAD

**Issue by Scipion** [inlet/react-pixi#242]
### Description

Usual project structure with react-redux in it with a `<Provider>` component, is not propagating the store to the children components.
The index.js should looks like this:
```
const store = createStore(rootReducer);
ReactDOM.render(
  <Provider store={store}>
    <App />
  </Provider>
  ,
  document.getElementById('root')
);
```

Once exists a component connected as in `connect()(MyComponent)`, react-redux throws the error:
```
connectAdvanced.js:245 Uncaught Error: Could not find "store" in the context of "Connect(Component)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(Component) in connect options.
```
The root component is actually wrapped in a `Provider` but checking the stack trace I can see how the store is not propagated through react-pixi.

### Steps to reproduce

1. Create react app
2. Install redux, react-redux and @inlet/react-pixi
3. Create a new component connected to a store

### Additional info

- `@inlet/react-pixi` version: 5.0.3
- `React` version: 16.13.1
- `ReactDOM` version: 16.13.1
- `PIXI` version: 5.3.2

#### After serveral tries

- The same react + redux + react-redux application but using divs intead of `@inlet/react-pixi` components is able to render without errors (but obviously not rendering a canvas).
- By providing a custom context I didn't see any change as it is not propagated either.
- After following the stack trace I found a workaround by adding the store field in every failing component as: `<MyComponent store={store} />` (even though this is not how react-redux should be used).

**Comment by inlet** [comment]
Duplicate #77
