### ISSUE TITLE
Unable to set Sprite size when using image data URL

### ISSUE THREAD

**Issue by mikedreambooth** [inlet/react-pixi#243]
### Description
When an image as a base 64 data url is passed to the Sprite the width and height props have no effect on the size of the sprite. 

### Steps to reproduce

Load an image from a base64 data URL and the sprite remains the original size of the image even though the width and height is set differently.

`<Sprite image = {base64DataUrl} width = {100} height={100}/>`

I get a sprite at the original image size, not 100 x 100.

**Comment by inlet** [comment]
Related to PIXI, see https://github.com/pixijs/pixi.js/issues/6229

**Comment by mikedreambooth** [comment]
> Related to PIXI, see [pixijs/pixi.js#6229](https://github.com/pixijs/pixi.js/issues/6229)

Hey @inlet . Thanks for replying. I saw that but didn't think it was related. The image loads from the URL just fine. It's just the width / height properties that don't seem to be getting applied.

**Comment by inlet** [comment]
It’s related, width and height on an image url works as expected. Creating a texture from the base64 image solves this issue. See solution in the comments
