### ISSUE TITLE
Dependency vulnerability: node-fetch Denial of Service

### ISSUE THREAD

**Issue by akryvasheyeu** [inlet/react-pixi#245]
### Description

Hi. fbjs depends on the old version of node-fetch (fbjs > isomorphic-fetch > node-fetch). Also fbjs looks dead and hasn't been updated for along time. I only found using `invariant` func from fbjs. Is it possible to move (or implement) this function to react-pixi repository and also remove fbjs dependency?

https://www.npmjs.com/advisories/1556

**Comment by inlet** [comment]
Thanks, yes I'll fix this in #246

**Comment by inlet** [comment]
Fixed
