### ISSUE TITLE
[Questions] Animation using react-spring

### ISSUE THREAD

**Issue by ajitid** [inlet/react-pixi#247]
### Description

I have few questions around using `react-pixi` with `react-spring` v9. 

1. There are multiple packages of React Spring available, which one should I pick, `@react-spring/web`, `@react-spring/core` or `@react-spring/native`?
2. When used in TypeScript, it warns that spring props are not assignable to components of this library as property coming from spring has type `SpringValue<number>` and `Sprite`'s `x` prop only accepts type `number`. I'm using `Sprite` from `@inlet/react-pixi/animated` and `useSpring` hook of version `9.0.0-rc.3`. Do we need to update types in `react-pixi`?

### Additional info

- `@inlet/react-pixi` version: 5.1.3
- `React` version: 16.13.1
- `ReactDOM` version: 16.13.1
- `PIXI` version: 5.3.3

**Comment by inlet** [comment]
Hi @ajitid,

> There are multiple packages of React Spring available, which one should I pick, @react-spring/web, @react-spring/core or @react-spring/native?

ReactPixi is web based, you'll need the web package. Just install `npm install react-spring@next` and you're set. See documentation: https://reactpixi.org/react-spring

> When used in TypeScript, it warns that spring props are not assignable to components of this library as property coming from spring has type SpringValue<number> and Sprite's x prop only accepts type number. I'm using Sprite from @inlet/react-pixi/animated and useSpring hook of version 9.0.0-rc.3. Do we need to update types in react-pixi?

Thanks for pointing out! I'll look into this, think I need the update the types for animated components :wink:

**Comment by inlet** [comment]
I've pushed an update, types are fixed in `5.1.4`.

**Comment by ajitid** [comment]
Uh oh, seems like types of components exported from `@inlet/react-pixi/animated` have got lost somehow. I can see props for `Stage` but not for rest of the components.

![Props' type of Sprite from animated package could not be inferred](https://user-images.githubusercontent.com/26769888/94154049-1b528400-fe9b-11ea-9bd2-ce10545a7d1e.png)

**Comment by inlet** [comment]
Stage is one of the components that is not wrapped in `animated()`. 

Have you installed `react-spring@next`? (currently `v9.0.0-rc.3`).

Here the typings are working correctly:

![image](https://user-images.githubusercontent.com/232559/94155282-0ec03280-fe7f-11ea-8372-23980e566f60.png)

Show type def for scale:

![image](https://user-images.githubusercontent.com/232559/94155350-239cc600-fe7f-11ea-95c2-a344dadfb6f8.png)

**Comment by ajitid** [comment]
Thanks, it worked! I had to remove `@react-spring/web` from my dependency list and install `react-spring` instead.
