### ISSUE TITLE
How to pass a fragment shader to Container component?

### ISSUE THREAD

**Issue by zeyi1** [inlet/react-pixi#248]
Say I have a fragment shader named fragShader, and I create a filter with

```
const filter = new PIXI.Filter(null, fragShader);

return (
  <Stage>
    <Container filters={filter}>
    </Container>
  </Stage>
)
```

Is this the correct way to pass the filter?

**Comment by inlet** [comment]
See https://pixijs.download/dev/docs/PIXI.DisplayObject.html#filters

Pass in an array:

```jsx

const filters = [new PIXI.Filter(null, fragShader)];

return (
  <Stage>
    <Container filters={filters}>
    </Container>
  </Stage>
)

```

**Comment by zeyi1** [comment]
Hello,
I have another question, how can I update a variable that is used in the shader with useTick? I am getting the following error: "Invariant Violation: No Context found with `PIXI.Application`. Make sure to wrap component with `AppProvider`".

`
const App = () => {
  const fragShader = 
  `
    #ifdef GL_ES
    precision mediump float;
    #endif

    uniform float time;

    void main() {
      gl_FragColor = vec4(abs(sin(time)),0.0,0.0,1.0);
    }
  `;


  const filter = new PIXI.Filter(null, fragShader);
  const uniforms = filter.uniforms;
  uniforms.time = 0.1;
  const area = new PIXI.Rectangle(5,5,100,100);

  useTick((delta) => {
    uniforms.time += 0.1 * delta;
  })

  return (
    <Stage width={200} height={200} options={{backgroundColor: 0xFFF}}>
      <Container filters={[filter]} filterArea={area}>

      </Container>
    </Stage>
  );
}
`
