### ISSUE TITLE
Stage + Sprites are 2x on 4K monitor

### ISSUE THREAD

**Issue by Habberlabber** [inlet/react-pixi#249]
### Description

I just started using react-pixi after building a crude prototype in vanilla Pixi and stumbled upon some unexpected behaviour. 
Thought I misconfigured something, but found the same behaviour on the demo page. 

Whenever I start/reload my application (or the demo page) on my 4k monitor the stage and its contents is 2x the size that I defined. On my 1080 monitor it numbers are correct. 

Same behaviour on https://reactpixi.org/stage.
Both in Safari and Chrome
Changing macOS display scale does not make any difference.

Is this intended, and if so, how can I detect when it happens, so that I can scale everything down again :) 

**Image of Code + Browser.**
<img width="1616" alt="image" src="https://user-images.githubusercontent.com/8472619/94959265-2e93ce00-04f1-11eb-92ce-2766f37d9cd8.png">
![image](https://user-images.githubusercontent.com/8472619/94959281-3489af00-04f1-11eb-98d8-da5561b98c44.png)

### Steps to reproduce

1. Create a stage
2. set height and width
3. inspect in browser on a 4k monitor

### Additional info

macOS Catalina v10.15.6 
- `@inlet/react-pixi` version: 5.1.4
- `React` version: 16.13.1
- `ReactDOM` version: 16.13.1
- `PIXI` version: 5.3.3

**Comment by Habberlabber** [comment]
And as soon as I posted I found the solution myself! 
I simply needed to pass the resolution in the options prop...

`<Stage width={100} height={100} options={{ resolution: 1 }}></stage>`

Hope this end up helping other people! :)

**Comment by inlet** [comment]
@Habberlabber Setting the resolution works, but you can always set `{ autoDensity: true }` to enable auto resolution, it even works when switching between high/low res monitors.
