### ISSUE TITLE
Not working on React 17

### ISSUE THREAD

**Issue by focux** [inlet/react-pixi#253]
### Description
When I try to render any React Pixi component using React 17, I get the following error:
```
react-pixi.es-dev.js?e177:2960 Uncaught TypeError: Cannot read property 'alternate' of undefined
```

If I use React 16 then I don't get this error, that's why I know it's related to the new React's version.

### Steps to reproduce

1. Install and use React 17
2. Render any React Pixi Component

### Additional info

- `@inlet/react-pixi` version:  5.2.0
- `React` version: 17
- `ReactDOM` version: 17
- `PIXI` version: 5.3.3

**Comment by inlet** [comment]
Thanks for letting me know, we need to update the lib to make it compatible with the newest React version.
I'll look into this later today.

**Comment by focux** [comment]
That was fast! Thank you so much for maintaining this library, I love it.
