### ISSUE TITLE
Not detecting WebGL in Firefox on Linux

### ISSUE THREAD

**Issue by willmartian** [inlet/react-pixi#255]
### Description

My browser (Firefox Developer Edition on Linux) supports WebGL, as per https://get.webgl.org/
However, when I run react-pixi I get the following error:

![image](https://user-images.githubusercontent.com/17113462/97437042-506a5000-18f9-11eb-8f8d-9e2f9b0a70c3.png)

### Additional info

- `@inlet/react-pixi` version: 6.0.0
- `React` version: 17.0.1
- `ReactDOM` version: 17.0.1
- `PIXI` version: 5.3.3

**Comment by inlet** [comment]
I'll close this issue as this is not related to ReactPixi but PIXI itself.

Check if these examples work:
https://pixijs.io/examples
https://codepen.io/inlet/pen/PoNXZvZ
