### ISSUE TITLE
TypeError: can't access property "current", container is undefined

### ISSUE THREAD

**Issue by willmartian** [inlet/react-pixi#256]
### Description

First time using this library, I am getting the attached error:

![image](https://user-images.githubusercontent.com/17113462/97437360-b9ea5e80-18f9-11eb-8619-3a30027a6666.png)

I am running the following react-pixi code in a create-react-app project:

```
import { Stage, Sprite } from '@inlet/react-pixi'

const PixiStage = () => (
    <Stage>
        <Sprite image="../images/cookie.png" x={100} y={100} />
    </Stage>
)

export default PixiStage;
```
### Additional info

- `@inlet/react-pixi` version: 6.0.0
- `React` version: 17.0.1
- `ReactDOM` version: 17.0.1
- `PIXI` version: 5.3.3

**Comment by inlet** [comment]
Hi @willmartian,

Unfortunately I cannot reproduce this issue, here's a working CRA:
https://codesandbox.io/s/react-pixi-test-tdr13

It looks like you're using an older version of ReactPixi that is not compat with React 17, make sure you have `@inlet/react-pixi@v6+`
