### ISSUE TITLE
willUnmount not called for PixiComponents that are children of a Container

### ISSUE THREAD

**Issue by femetrie** [inlet/react-pixi#257]
### Description

When unmounting a component tree, nested custom `PixiComponent`s don't have their `willUnmount` method called. This is critical for wrappers like pixi-viewport, which need to be destroyed explicitly or else they will leak event listeners that will crash on subsequent usage.

### Steps to reproduce

Run the code below and see that the "Never called" line is indeed, never called.

```tsx
import React from 'react';
import { Stage, Container, PixiComponent } from '@inlet/react-pixi';
import { render, unmountComponentAtNode } from 'react-dom';

const Rectangle = PixiComponent('Rectangle', {
  create: () => {
    return new Graphics();
  },
  willUnmount: () => {
    console.log('Never called');
  },
});

const App = () => (
  <Stage>
    <Container>
      <Rectangle />
    </Container>
  </Stage>
);

const element = document.querySelector('#content');
render(<App />, element);

setTimeout(() => {
  unmountComponentAtNode(element);
}, 1000);
```

### Additional info

- `@inlet/react-pixi` version: v5.2.0
- `React` version: v16.3.1
- `ReactDOM` version: v16.3.1
- `PIXI` version: v5.3.3

**Comment by inlet** [comment]
Hi @femetrie,

Unfortunately I cannot replicate the issue.

I've created two examples to demo this:

**Using state:** 
https://codesandbox.io/s/react-pixicustom-componentunmount-4l4nw?file=/src/App.js

**Using the unmountComponentAtNode as described above:**
https://codesandbox.io/s/react-pixicustom-componentunmount2-y2p3k?file=/src/index.js

Please note that you're using an older version of ReactPixi, this might lead to problems. Please upgrade ReactPixi to `v6+` and React to `v17+`.

Thanks! I'll close this issue for now

**Comment by femetrie** [comment]
@inlet thanks so much for making that demo, I should've done that. I was able to fork your demo and add a `<Container>` wrapper to produce the bug: https://codesandbox.io/s/react-pixicustom-componentunmount-forked-se8iy.

![2020-11-02 09 09 14](https://user-images.githubusercontent.com/8063225/97883950-1b8c3d80-1ceb-11eb-9ded-c9cba3d01d69.gif)

**Comment by inlet** [comment]
> thanks so much for making that demo, I should've done that. 
you're welcome, no worries at all.

Ah I see, so whenever you wrap it in a container it doesn't trigger the unmount.. 🤔
I'll have to dig into that, thanks for pointing out

**Comment by inlet** [comment]
Thanks so much for discovering this! It turns out we don't unmount native subcomponents, I'll will fix this!

**Comment by inlet** [comment]
Hi @femetrie I've pushed an update with the fix 🙌

**Comment by femetrie** [comment]
Amazing! Really appreciate the fix. _Loving_ react-pixi. I moved a large codebase to it and it's performing incredibly well.
