### ISSUE TITLE
Custom Component example in readme incorrect

### ISSUE THREAD

**Issue by korroktheslavemaster** [inlet/react-pixi#26]
### Description
Incorrect custom component example in readme. Should not instantiate custom component with `var x = new PixiComponent(...)`, just do `var x = PixiComponent(...)` otherwise TypeError thrown by react.

### Steps to reproduce

1. Make component eg. `var CustomComponent = new PixiComponent('MyComponent', {})`

### Additional info

- `@inlet/react-pixi` version: 0.1.0
- `React` version: 16.4.1
- `ReactDOM` version: 16.4.1
- `PIXI` version: 4.8.1

**Comment by inlet** [comment]
Thanks for pointing out! If you'd like you can create a PR for this?

**Comment by inlet** [comment]
Done! ✨
