### ISSUE TITLE
Subscription on instance events in didMount

### ISSUE THREAD

**Issue by jdim** [inlet/react-pixi#262]
Hello, first thanks a lot for creating this awesome library.

### Description
I use `pixi-viewport` and want to be able to view the current zoom value and reset it.
So I try to implement `onZoomChange` prop for component created with PixiComponent, but how call this handler?
```typescript
const MyViewport = PixiComponent<IViewportProps, PixiViewport>('Viewport', {
  create: (props) => new PixiViewport(
    ...
  ),
  didMount: (instance: PixiViewport) => {
    ...

    instance.on('zoomed-end', (viewport: PixiViewport) => {
     // ??? Somehow I need to invoke handler from props to display zoom value in a parent
      props.onZoomChange(getZoomValue(viewport));
    })
  },
  willUnmount: (instance: PixiViewport) => {
    instance.destroy()
  },
});
```
To reset the zoom value I plan to use `applyProps` with the new zoom prop. Is it the right way?

**Comment by inlet** [comment]
Hi @jdim 

> Hello, first thanks a lot for creating this awesome library.

You're welcome!

> So I try to implement onZoomChange prop for component created with PixiComponent, but how call this handler?

See https://github.com/inlet/react-pixi#custom-components, in order to handle prop updates you'll need to use the `applyProps`, example:

```jsx
const MyViewport = PixiComponent<IViewportProps, PixiViewport>('Viewport', {
  create: () => new PixiViewport(),
  willUnmount: (instance) => instance.destroy(),
  applyProps: (instance, oldProps, newProps) => {
    if (oldProps.onZoomChange !== newProps.onZoomChange) {
      instance._onZoomChange && (
        instance.removeListener('zoom-end', instance._onZoomChange)
      );
      
      instance._onZoomChange = () => {
        newProps.onZoomChange(getZoomValue(instance));
      };

      instance.on('zoom-ended', instance._onZoomChange);
    }
  },
});
```

**Comment by inlet** [comment]
btw, you can ask these kind of questions in our Slack channel and leave Github issues for bug issues and features. Thanks!
