### ISSUE TITLE
Differences with react-pixi-fiber

### ISSUE THREAD

**Issue by AdrienLemaire** [inlet/react-pixi#263]
I'm currently evaluating what game engine to integrate with my react application, and pixijs looks like a great option.

But I'm unclear as to how react-pixi and [react-pixi-fiber](https://github.com/michalochman/react-pixi-fiber) from @michalochman differ, other than react-pixi being the first to support React 17.

Can someone highlight the pros and cons of both libraries ?

**Comment by inlet** [comment]
Hi @AdrienLemaire,

There are a bunch on react pixi renderers out there, they all serve one purpose which is render pixi apps the React way. 

I’ll close this issue, we have a Slack channel where we can continue these kind of conversations. Let’s use Github issues for bug/feature reports. Thanks!

**Comment by linonetwo** [comment]
Maybe you can enable Github discussion?
