### ISSUE TITLE
Uncaught TypeError: Cannot read property 'alternate' of undefined

### ISSUE THREAD

**Issue by kafinsalim** [inlet/react-pixi#265]
### Description

Hi!, thanks for making this library.
I have an exact same error like in this example https://codesandbox.io/s/react-pixi-nightowllogic-forked-sz4fx?file=/package.json, which I got from the example here https://codesandbox.io/examples/package/@inlet/react-pixi. At first the example repo also has some error nothing works then I updated react-pixi + another dependencies to latest. Now I got the same error as what I got on my project, so maybe if I know why the error is happening I could solve the error on my project also

Can anyone guide me which part is wrong? or direct me to part of the docs that I have to read

### Additional info

- `@inlet/react-pixi` version: 6.0.2
- `React` version: 16.8.6
- `ReactDOM` version: 16.8.6
- `PIXI` version: 5.1.1

**Comment by inlet** [comment]
You'll need to upgrade to React 17 :wink:
