### ISSUE TITLE
resource hooks

### ISSUE THREAD

**Issue by AdrienLemaire** [inlet/react-pixi#266]
Creating hooks to load resources could reduce the amount of code needed.

Here's an example `useResources` I made while following [the LearningPixi tutorial](https://github.com/kittykatattack/learningPixi#creating-sprites-from-a-loaded-texture-atlas)

```tsx
const stageWidth = 512;
const stageHeight = stageWidth;
const stageOptions = { transparent: true };

/********* START HOOK *********/
function useTextures(assetPath: string): PIXI.ITextureDictionary | undefined {
  const [textures, setTextures] = React.useState<PIXI.ITextureDictionary>();
  const app = useApp();

  React.useEffect(() => {
    app.loader.add(assetPath).load((_, resource) => {
      setTextures(resource[assetPath]!.textures);
    });
  }, [app.loader, assetPath, setTextures]);

  return textures;
}
/********* END HOOK *********/

const TreasureHunter: React.FC = () => {
  const textures = useTextures("../assets/atlas/treasureHunter.json"); // <== EASY !

  return (textures) ? (
    <>
      <Sprite texture={textures["dungeon.png"]} />
      <Sprite
        texture={textures["explorer.png"]}
        x={68}
        y={stageHeight / 2 - textures["explorer.png"]!.height / 2}
      />
      <Sprite
        texture={textures["treasure.png"]}
        x={stageWidth - textures["treasure.png"]!.width - 48}
        y={stageHeight / 2 - textures["treasure.png"]!.height / 2}
      />
    </>
  ): null;
};

const Demo: React.FC = () => (
    <Stage width={stageWidth} height={stageHeight} options={stageOptions}>
      <TreasureHunter />
    </Stage>
);
```

Still learning the basics of Pixi, but I assume we could also have `useSpritesheet` and `useTexture`.

While looking at [your flying plane example](https://reactpixi.org/components/animated-sprite#example), I saw assets fetched from `resource[spritesheet].data.frames`, so a `useFrames` could also make sense? (btw, I could verify [here](https://github.com/pixijs/pixi.js/blob/af26a56140c617d9ddc93275ad1ddb2c17c25d1f/packages/spritesheet/src/Spritesheet.ts#L34) that data.frames is a `Dict<ISpritesheetFrameData>`, but in my project using pixi.js 5.3.3, [data is typed as any](https://i.imgur.com/khdG255.png
), which is very confusing (I suppose it's a pixi.js specific bug).

**Comment by inlet** [comment]
Yes hooks are amazing! However no need to implement this in react-pixi as these are decorative hooks. 

Anyway thanks for sharing!

**Comment by inlet** [comment]
I've added this to the React Pixi codepen collection: https://codepen.io/inlet/pen/wvWRLGL

Thanks!
