### ISSUE TITLE
Cannot run getting started example when creating project with create-react-app

### ISSUE THREAD

**Issue by ratinac-nikola** [inlet/react-pixi#268]
### Description
Using react-pixi out of the box with create-react-app doesn't work. I was following the guide of getting started with [react-pixi](https://reactpixi.org/). Installed the react-pixi package and modified the `App.js` to look like the one in the **Usage** section of the getting started guide and I am getting 2 errors when I run the dev server:

1. Error: WebGL unsupported in this browser, use "pixi.js-legacy" for fallback canvas2d support.
2. TypeError: container is undefined
  

### Steps to reproduce

1. Use create-react-app CLI with default template
2. Run yarn add pixi.js @inlet/react-pixi
3. Substitute the code in the App.js file with the following:
```
import { Stage, Sprite } from '@inlet/react-pixi';
const App = () => (
  <Stage>
    <Sprite image="./bunny.png" x={100} y={100} />
  </Stage>
);

export default App;
```
4. run the dev server with yarn start

### Additional info

- `@inlet/react-pixi` version: 6.0.6 
- `React` version: 17.0.1
- `ReactDOM` version: 17.0.1
- `PIXI` version: 5.3.3

Screenshots of the error screens:
![Screenshot from 2020-11-22 12-41-25](https://user-images.githubusercontent.com/56120027/99902709-1bff6f00-2cc0-11eb-83be-e43286d358e7.png)
![Screenshot from 2020-11-22 12-41-29](https://user-images.githubusercontent.com/56120027/99902710-1c980580-2cc0-11eb-9e1e-cf2d323c45ce.png)

**Comment by inlet** [comment]
Here's a working codesandbox example: https://codesandbox.io/s/cra-react-pixi-0r43d?file=/src/App.js

Make sure to include `pixi.js` to your dependency.

**Comment by iggyZiggy** [comment]
![image](https://user-images.githubusercontent.com/4414394/101221554-33f3cd00-3688-11eb-8680-88ce415d9663.png)

not really a working example on codesandbox. I'm also having this same issue locally

**Comment by inlet** [comment]
@iggyZiggy can you create a codesandbox demo? It should work

**Comment by iggyZiggy** [comment]
it's copy pasted code from the main site, under https://reactpixi.org/pixi-legacy
i have deleted pixi.js and installed pixi.js-legacy as well but it doesn't work, every example throws that error too

**Comment by inlet** [comment]
https://codesandbox.io/embed/pixi-legacy-f1ksf?codemirror=1

**Comment by iggyZiggy** [comment]
i'm giving up, i'll just use canvas directly, this is a nightmare.

For some reason, it works on that last link, but when i copy it locally, each file exactly like in the example, make sure package versions are the same, it doesn't. Tried creating new react app, tried in the old one and nothing.

**Comment by inlet** [comment]
@iggyZiggy Sorry to hear that, would love to help you but unfortunately I cannot reproduce the issue.

Thanks!
