### ISSUE TITLE
mouseover + mouseout with setState with problems

### ISSUE THREAD

**Issue by mtwzim** [inlet/react-pixi#269]
### Description

Hello guys, I have a react application that uses the Graphics component, together with the events: mouseover and mouseout, and also the setState on them, however this causes several calls on it, how can I do this correctly?

### Steps to reproduce

1. Create a react app
2. Add Graphics with mouseover and mouseout, and inside of this setState

### Prints
![image](https://user-images.githubusercontent.com/42474938/101225256-be7c0280-366f-11eb-96dc-1071161b32b5.png)
![gif](https://media1.tenor.com/images/623e525003f7a82b3e3dafd166af71b1/tenor.gif?itemid=19441043)

### Additional info

- `@inlet/react-pixi` version: ^6.0.6
- `React` version: ^17.0.1
- `ReactDOM` version: ^17.0.1
- `PIXI` version: ^5.3.3

**Comment by inlet** [comment]
Simply memoize the callbacks will solve it

**Comment by mtwzim** [comment]
You can give-me a example?

**Comment by inlet** [comment]
https://codepen.io/inlet/pen/5dda7fcdb4a9c1650766fd1d9a4a7ad5

And good to know is that you can manually change the way the interaction manager handle pointer events, see https://pixijs.download/dev/docs/PIXI.InteractionManager.html#moveWhenInside

**Comment by mtwzim** [comment]
> https://codepen.io/inlet/pen/5dda7fcdb4a9c1650766fd1d9a4a7ad5
> 
> And good to know is that you can manually change the way the interaction manager handle pointer events, see https://pixijs.download/dev/docs/PIXI.InteractionManager.html#moveWhenInside

Thank's for you response, anyway, on the weekend i got it using the **useReducer** hook, so my problems has ended.😀 
And... sorry for not update this issue.

**Comment by inlet** [comment]
no worries, glad you've worked something out!
