### ISSUE TITLE
Sprite never re-render after its texture has loaded

### ISSUE THREAD

**Issue by ash-r1** [inlet/react-pixi#272]
### Description

When I add a `Sprite` with a large-sized image by user-interaction, it never shows the image.
Because it has no-image (black) before rendering, and it never re-render after `app.loader` load the texture.

I think it's nice if it's automatically managed by react-pixi.

### Steps to reproduce

Clone & run this repo: https://github.com/ash-r1/react-pixi-repesesent-issue

### Additional info

- `@inlet/react-pixi` version: 6.0.6
- `React` version: 17.0.1
- `ReactDOM` version: 17.0.1
- `PIXI` version: 5.3.6

#### use hooks ?

I know a hooks approach mentioned here https://github.com/inlet/react-pixi/issues/266 .
But it would be crash if you add multiple sprites at the same time because `PIXI.Loader` cannot be used concurrently.

**Comment by inlet** [comment]
Hi @ash-r1 

It would be easier for me if you could create a codesandbox example :wink:

> When I add a Sprite with a large-sized image by user-interaction, it never shows the image.
Because it has no-image (black) before rendering, and it never re-render after app.loader load the texture.
>
> I think it's nice if it's automatically managed by react-pixi.

Changing the image prop should render it with the new image texture. 

> use hooks ?
> I know a hooks approach mentioned here #266 .
> But it would be crash if you add multiple sprites at the same time because PIXI.Loader cannot be used concurrently.

True, this is a limitation of PIXI's shared loader, best practise is to create a new loader.

Thanks!

**Comment by ash-r1** [comment]
Hi @inlet 

okay, I made a codesandbox one.
https://codepen.io/ash-r1/pen/MWjOzRM

btw, I mention the `Sprite` component now, but the `Text` component also has a problem.
It should show "Showing" after you clicked, but it disappears.

**Comment by inlet** [comment]
Just had a look at your code, and I see what's causing the issue.

Although you can set a width and height on a `<Container>` it is not recommended as the content in it will stretch.. the children get rendered first thats why this artifact will only appear after a second render.

Remove the width and height from the Container will solve it.

**Comment by inlet** [comment]
And for Sprite, replace your code with this and it will work as well:

```jsx
{clicked && <Sprite image={url} />}
```

**Comment by ash-r1** [comment]
Thanks a lot.
By removing height/width from `<Container>`, it works well.
