### ISSUE TITLE
could not resolve dependency: react-spring

### ISSUE THREAD

**Issue by JosephClay** [inlet/react-pixi#276]
### Description

Running an npm install results in an error resolving the peer dep `react-spring`:

```
npm WARN Could not resolve dependency:
npm WARN peer react-spring@"9.x" from @inlet/react-pixi@6.0.7
npm WARN node_modules/@inlet/react-pixi
npm WARN   @inlet/react-pixi@"*" from the root project
npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-spring@9.x.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```
peerDependencies list react-spring version "9.x" which doesn't have a target in npm: https://www.npmjs.com/package/react-spring

### Steps to reproduce

1. Run: `npm install pixi.js @inlet/react-pixi`

### Additional info

- `@inlet/react-pixi` version: 6.0.7
- `React` version: n/a
- `ReactDOM` version: n/a
- `PIXI` version: n/a
- `npm` version: 7.4.0

**Comment by inlet** [comment]
Hi @JosephClay 

Thanks! I just pushed an update (`v6.09`) where I stripped out the logs as the log statements are a bit confusing. 
You can safely ignore any `WARN` message as `react-spring` is an optional peer dependency. 

![image](https://user-images.githubusercontent.com/232559/105175380-1d181580-5b24-11eb-9fd1-7a1a1ea8a514.png)

**Comment by JosephClay** [comment]
Thank you @inlet

I've narrowed the issue to [`npm@7.x` handling of peerDependencies](https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major)

The install works using `npm i --legacy-peer-deps pixi.js @inlet/react-pixi`, but continues to break with the same error without the legacy flag

**Comment by inlet** [comment]
I'm not using npm@7 at the moment, maybe that's causing the issue. The latest version of npm, at time of writing, is `6.14.11`.   Good to know that a future release of npm might break this behaviour. Thanks for letting me know and if you find a solution please let me know.

Thanks!
