### ISSUE TITLE
Stage types are lost when using TypeScript and Dynamic Import in Next.js.

### ISSUE THREAD

**Issue by eai04191** [inlet/react-pixi#278]
First of all, thank you for maintaining this amazing library!

### Description

No problem when importing as usual.

![image](https://user-images.githubusercontent.com/3516343/107541398-6ed72b80-6c0a-11eb-9253-166f081a5af2.png)

In Next.js, needs to use Dynamic Import to prevent SSR.
Doing so will result in a Stage type loss and a type error.

![image](https://user-images.githubusercontent.com/3516343/107541886-ef962780-6c0a-11eb-9887-c8917b50be85.png)

### Steps to reproduce

See in codesandbox.
https://codesandbox.io/s/sharp-snow-u2xev?file=/pages/index.tsx

1. Install dependencies.
2. Dynamic import `Stage` from `@inlet/react-pixi`.
3. Add attributes to `Stage`.

### Additional info

- `@inlet/react-pixi` version: 6.0.9
- `React` version: 17.0.1
- `ReactDOM` version: 17.0.1
- `PIXI` version: 5.3.7

**Comment by inlet** [comment]
Thanks @eai04191 

The problem is that next's `dynamic` import doesn't preserve typings. What you could do is wrap it in a separate component, here's an example: https://codesandbox.io/s/next-js-react-pixi-jcmt1
