### ISSUE TITLE
Docs - Add warning (to use clear method) for Graphics component when updating draw

### ISSUE THREAD

**Issue by bichotll** [inlet/react-pixi#28]
### Description

We should add a warning in the Graphics component to warn the user that he may want to clear the canvas if new properties have received.

I can work on that and create a PR.

### Steps to reproduce

I created a simple example: https://codepen.io/bichotll/pen/KBYBpd?editors=0011

**Comment by inlet** [comment]
I believe this should be up to the developer. PIXI memoizes the elements to rende, clears the canvas and redraw the elements back to improve performance.

If you're using the `Graphics.draw` prop, you can simply add `g.clear()` before you draw another rectangle. See this example: https://codepen.io/inlet/pen/RMLJKm?editors=0011

![image](https://user-images.githubusercontent.com/232559/44138975-f90bc5d0-a075-11e8-94f5-262c8fcb10e5.png)

**Comment by inlet** [comment]
Closing issue now, please let me know if you think we should reopen it.

**Comment by bichotll** [comment]
Yes. I'm using `g.clear()` :)

I just think it would be helpful for the user to let them know that.
My point is: If they are not familiar enough with Pixi, they may expect that passing a new prop to the Graphics component, it would just clear the Graphics component "canvas" and write on a blank canvas (You have to explicitly call the method `.clear()` in order to have that desired behaviour).

That actually confused me - when it happened to me - until I found out what it was going on.

Again, if that make sense to you, I can create a PR (an update of the docs with the note).
It's not a big deal and it's not part of the library, but it's a good thing to know - at least for newbies.

**Comment by inlet** [comment]
Good point, would be great if you add this to the README. Thanks!

**Comment by bichotll** [comment]
Sure thing. I'll work on that soon-ish 👍

**Comment by inlet** [comment]
Hi @bichotll,

I've added a note to the `Graphics` doc, see:
https://reactpixi.org/#/components/graphics
