### ISSUE TITLE
Incorrect types

### ISSUE THREAD

**Issue by svendrendall** [inlet/react-pixi#282]
### Description
Hello! 👋
I'm unable to migrate to the PIXI v6 probably because of the incorrect library types. I get the following error for the most of components: 
> Type 'InteractionEvents'.
  Property 'any property' is incompatible with index signature.
    Type 'any type' is not assignable to type '((event: InteractionEvent) => void) | undefined'.

The error happens as soon as you add at least one property to a component.

It's really strange that my kind of an issue still wasn't opened before so I'm probably doing something wrong on my side. 

Here's a [sandbox](https://codesandbox.io/s/elegant-vaughan-we75s?file=/src/App.tsx).

### Steps to reproduce

1. `yarn add pixi.js @inlet/react-pixi`

### Additional info

- `@inlet/react-pixi` version: 6.2.0
- `React` version: 17.0.1
- `ReactDOM` version: 17.0.1
- `PIXI` version: 6.0.0

**Comment by inlet** [comment]
Yes I’m aware of this, I’ll update the types once I have the time (probably early this week). Please feel free to create a PR with the updated types, thanks!

**Comment by inlet** [comment]
Fixed in `v6.2.1`
