### ISSUE TITLE
disabled raf and optimizations

### ISSUE THREAD

**Issue by adsko** [inlet/react-pixi#283]
### Description
Hi, I've analysed an issues with a performance when a raf is disabled. Based on react-pixi code, when any component has changed, there is dispatched: '__REACT_PIXI_REQUEST_RENDER__' and there is a listener which calls render on an app.

This method generates a large perfomance issue. I've written simple react component:

```
const HandleUpdate: React.FC<{}> = (props) => {
    const hasUpdate = React.useRef(0);
    const app = useApp();
    const onEvent = React.useCallback(() => {
        hasUpdate.current = hasUpdate.current + 1;
    }, [hasUpdate]);

    React.useEffect(() => {
        window.addEventListener('__REACT_PIXI_REQUEST_RENDER__', onEvent);
    }, [onEvent]);

    useRaf(() => {
        if (!hasUpdate.current) {
            return;
        }

        console.log(hasUpdate.current);
        hasUpdate.current = 0;
        app.render();
    }, true);
    return (
        <React.Fragment>
            {props.children}
        </React.Fragment>
    );
};
```
Which calls render on PIXI ticker, if any component has changed. Based on a log in my solution, configuration:
```
raf={false}
renderOnComponentUpdate={true}
```

generates up to 131 updates on one raf iteration! And this number is small because my app is pretty small.

In general, I think disabled raf should work as my function. Should render the app only if a component has changed, but no more often than the raf iterations.

### Additional info
Config is not latest, but solution on master is the same.

"react": "^16.12.0",
"react-dom": "^16.12.0",
"pixi.js": "^5.3.3",
"@inlet/react-pixi": "^5.2.0",

**Comment by inlet** [comment]
Hi @adsko,

Firstly, in general the `__REACT_PIXI_REQUEST_RENDER__` event is only used internally and you shouldn't have to listen to it, unless you know what you're doing and want to have full control of reconciliation updates.

Secondly, the `renderOnComponentUpdate` does not exist, I think you mean `renderOnComponentChange`?

So when does the `__REACT_PIXI_REQUEST_RENDER__` event gets triggered, it gets triggered for committing updates for each component respectively, this is part of React reconciliation. 

If you use the `<Stage>` you can disable raf and choose to only render the PIXI Stage on component changes, the Stage component uses this event to perform a render, see https://reactpixi.org/stage#custom-updates

If you persist to use this `__REACT_PIXI_REQUEST_RENDER__`, here's an example that might be helpful:
https://codepen.io/inlet/pen/2077758844bee73be0b548bc659e83f7

**Comment by adsko** [comment]
@inlet 
I still think that disabled raf generates performance issues. 


Check out this code:

```
console.clear();

const { useState, useEffect, useCallback, useMemo } = React;
const { Stage, Text, Sprite, Container } = ReactPixi;
const { Texture, TextStyle } = PIXI;

const textStyle = new TextStyle({ align: 'center' });
const iterations = new Array(10).fill(1);
const stageOptions = {
  backgroundColor: 0xcccccc,
  antialias: true,
  autoDensity: true
};

let savedHub = [];
function eventHub(onEvent) {
  savedHub = [...savedHub, onEvent];
}

function callEvents() {
  savedHub.forEach(v => v());
}

// a single counter contains a
//   - Container
//   - Sprite
//   - Text
// resulting in 3 render updates
const Counter = ({ ...props }) => {
  const [count, setCount] = useState(0);
  const onUpdate = useCallback(() => callEvents(), []);
  
  useEffect(() => {
    eventHub(() => setCount(v => v + 1));
  }, []);
  
  const bgColor = useMemo(() => {
    return '0x' + Math.floor(Math.random() * 16777215).toString(16);
  }, [count]);

  return (
    <Container {...props} interactive={true} buttonMode={true} pointerup={onUpdate}>
      <Sprite texture={Texture.WHITE} tint={bgColor} width={50} height={50} alpha={0.8} />
      <Text text={count} style={textStyle} anchor={0.5} x={25} y={25} />
    </Container>
  );
};

// store pixiApp
let pixiApp;

// render pixi app
const render = () => pixiApp.renderer.render(pixiApp.stage);

// We disable the `raf` and `renderOnComponentChange`
// and keep track of each component update
const App = () => {
  const [on, setOn] = useState(true);
  
  return (
    <>
      <button onClick={() => setOn(o => !o)}>toggle</button>
      <Stage
        width={500}
        height={500}
        raf={false}
        renderOnComponentChange={false}
        options={stageOptions}
        onMount={app => (pixiApp = app)}
      >
        {on && iterations.map((_, i) => <Counter x={i * 50 % 500} y={i * 50} />)}
      </Stage>
    </>
  );
};

let updatesAll = 0;
let updatesNormalized = 0;

const debouncedUpdate = _.debounce(() => {
  updatesNormalized++;
  
  document.getElementById("updates-normalized").innerText = 'Render updates: ' + updatesNormalized;
  render();
}, 1000/ 60);

function onEvent() {
  updatesAll++;
  
  document.getElementById("updates-all").innerText = 'Reconciliation updates: ' + updatesAll;
  debouncedUpdate();
}

window.addEventListener("__REACT_PIXI_REQUEST_RENDER__", onEvent);

ReactDOM.render(<App />, document.getElementById("root"));

// render initial
render();
```

I've changed your example, and I've added an external event hub (like redux, rxjs Subject, etc).
Every click on the square generates 10x reconcilation updates. Without REACT_PIXI_REQUEST_RENDER and enabled renderOnComponentChange, it calls 10x render for every click! 

So, I think raf={false} should work differently, or there should be an official API for handling own alghorithm for calling render when the component has changed. Without it, raf={false} easily generates performance issues, and we have only unofficial API, which can be changed in the future.

**Comment by inlet** [comment]
Maybe I’m not seeing the picture here, but the fact that it’s rendering multiple times has nothing to do with ReactPixi or disabling raf. It’s just the way you use React. Can you please elaborate why you think it has performance issues? Thanks

**Comment by adsko** [comment]
@inlet I've preprared second one example based on your example (change only JS to run it):


(See that i've removed render on update event, enabled renderOnComponentChange and I've added global event hub)
```
console.clear();

const { useState, useEffect, useCallback, useMemo } = React;
const { Stage, Text, Sprite, Container } = ReactPixi;
const { Texture, TextStyle } = PIXI;

const r = PIXI.Renderer.prototype.render;

let last = null;

PIXI.Renderer.prototype.render = function() {
  let now = Date.now();
  if (last) {
    console.log("update", now - last);
  }
  last = now;
  r.apply(this, arguments);
}

const textStyle = new TextStyle({ align: 'center' });
const iterations = new Array(10).fill(1);
const stageOptions = {
  backgroundColor: 0xcccccc,
  antialias: true,
  autoDensity: true
};

let savedHub = [];
function eventHub(onEvent) {
  savedHub = [...savedHub, onEvent];
}

function callEvents() {
  savedHub.forEach(v => v());
}

// a single counter contains a
//   - Container
//   - Sprite
//   - Text
// resulting in 3 render updates
const Counter = ({ ...props }) => {
  const [count, setCount] = useState(0);
  const onUpdate = useCallback(() => callEvents(), []);
  
  useEffect(() => {
    eventHub(() => setCount(v => v + 1));
  }, []);
  
  const bgColor = useMemo(() => {
    return '0x' + Math.floor(Math.random() * 16777215).toString(16);
  }, [count]);

  return (
    <Container {...props} interactive={true} buttonMode={true} pointerup={onUpdate}>
      <Sprite texture={Texture.WHITE} tint={bgColor} width={50} height={50} alpha={0.8} />
      <Text text={count} style={textStyle} anchor={0.5} x={25} y={25} />
    </Container>
  );
};

// store pixiApp
let pixiApp;

// render pixi app
const render = () => pixiApp.renderer.render(pixiApp.stage);

// We disable the `raf` and `renderOnComponentChange`
// and keep track of each component update
const App = () => {
  const [on, setOn] = useState(true);
  
  return (
    <>
      <button onClick={() => setOn(o => !o)}>toggle</button>
      <Stage
        width={500}
        height={500}
        raf={false}
        renderOnComponentChange={true}
        options={stageOptions}
        onMount={app => (pixiApp = app)}
      >
        {on && iterations.map((_, i) => <Counter x={i * 50 % 500} y={i * 50} />)}
      </Stage>
    </>
  );
};

let updatesAll = 0;
let updatesNormalized = 0;

const debouncedUpdate = _.debounce(() => {
  updatesNormalized++;
  
  document.getElementById("updates-normalized").innerText = 'Render updates: ' + updatesNormalized;
  // render();
}, 1000/ 60);

function onEvent() {
  updatesAll++;
  
  document.getElementById("updates-all").innerText = 'Reconciliation updates: ' + updatesAll;
  debouncedUpdate();
}

window.addEventListener("__REACT_PIXI_REQUEST_RENDER__", onEvent);

ReactDOM.render(<App />, document.getElementById("root"));

// render initial
render();
```

When you check browser console. you'll see log when Renderer.prototype.render is called, and time (in ms) since last render.

See that every click on the box calls render function 10 times in a row. In addition, it's called without any delay (1ms between two calls).
![image](https://user-images.githubusercontent.com/693387/111842938-89cf4680-8900-11eb-89ae-79eb79f150b9.png)

In situation like this, disabled raf generates issues with performance when multiple components has changed, but when raf is enabled we have 60x render/sec. It would be great if we can combine it: render when needed, but no more often that 60x/sec.

**Comment by inlet** [comment]
So the performance issue only arise when setting the `renderOnComponent` to `true` right? Right now every commit request renders via a raf. I can see how I can integrate the debounce into the Stage component. That might solve the issue. What do you think?

**Comment by adsko** [comment]
@inlet Yes, combination `raf `to `false `and `renderOnComponentChange `to `true `generates that problem. I'm not sure if `debounce `(which works on `setTimeout`) will be better than local PIXI ticker. With the ticker, solution will look like:

```
window.addEventListener('__REACT_PIXI_REQUEST_RENDER__', () => this.needRender = true);
this.ticker.add(() => {
    if (this.needRender) {
        this.needRender = false;
        this.render();
    }
});
```
In my opinion the ticker is not heavy for CPU itself, but I leave a decision to you.

In addition, it would be greate to have possibility to handle it manually (as you have written:  `feel free to use it... however this API might change in the future.`, current API is not safe to use).

**Comment by inlet** [comment]
Adding a listener for ticker to render the  stage looks like a good solution indeed..

will push it later today, thanks for collab!

**Comment by inlet** [comment]
Yes I've pushed an update, this is now fixed 🙌 

Thanks for contributing!

If I now tap into the render and benchmark the performance:

```js
const origRender = PIXI.Renderer.prototype.render;

let last = 0;

PIXI.Renderer.prototype.render = function render() {
  const current = performance.now();
  console.log(current - last);
  
  last = current;
  origRender.apply(this, arguments);
}
```

you can see that the render call is optimized:

![ScreenFlow](https://user-images.githubusercontent.com/232559/111875911-72de3200-899c-11eb-8cb9-68c3104f9118.gif)
