### ISSUE TITLE
Can not re-export directly from react-pixi

### ISSUE THREAD

**Issue by sangdth** [inlet/react-pixi#288]
### Description
Re-export directly from `react-pixi` get error from vite.

### Steps to reproduce

1. Clone this project `gh repo clone sangdth/test-re-export`, run `yarn dev`
2. You will see `The requested module '/node_modules/.vite/@inlet_react-pixi.js?v=2a73f26b' does not provide an export named 'Container'` (Which does not happens with other lib like `@rmwc/button`, tested)

### Additional info

- `@inlet/react-pixi` version: 6.3.0
- `React` version: 17
- `ReactDOM` version: 17
- `PIXI` version: 6

**Comment by inlet** [comment]
That’s because pixi.js is a peer dependency

**Comment by inlet** [comment]
Please let me know if this problem persist and please make a PR with a fix 😉

**Comment by sangdth** [comment]
Thanks, I've tried to `yarn build` and the problem is still there. But I checked and saw the `react-pixi` actually had the const export with named `Container`, so I think this is the problem with `vite`.

**Comment by inlet** [comment]
And why would that be a problem?

**Comment by sangdth** [comment]
Honestly I don't know :D 

This is caused problem:
```
export { Container } from '@inlet/react-pixi'
```

But this one WORKS FINE:
```
import { Container } from '@inlet/react-pixi'

export { Container };
```

:D

**Comment by sangdth** [comment]
@inlet , may I ask, do I need to have `react-spring` in dependencies?

**Comment by inlet** [comment]
> Honestly I don't know :D
> 
> This is caused problem:
> 
> ```
> export { Container } from '@inlet/react-pixi'
> ```
> 
> But this one WORKS FINE:
> 
> ```
> import { Container } from '@inlet/react-pixi'
> 
> export { Container };
> ```
> 
> :D

Not sure why, but if the latter works stick with that right?

> @inlet , may I ask, do I need to have `react-spring` in dependencies?

It’s a peer dependency, so only include it if you’re using react-spring

**Comment by sangdth** [comment]
Thanks for your time. Big kudos to your library btw. <3
