### ISSUE TITLE
How can we extend the type of app.loader ?

### ISSUE THREAD

**Issue by AdrienLemaire** [inlet/react-pixi#289]
### Description

`app.loader.resources[0].metadata` has type **IResourceMetadata**
```ts
export declare interface IResourceMetadata extends GlobalMixins.IResourceMetadata, Resource.IMetadata, IBaseTextureOptions {
    imageMetadata?: any;
}
```
I'm using that `imageMetadata` key to store project-related informations
```ts
export type ProjectMetadata = IResourceMetadata & {
  // imageMetadata has type any by default
  imageMetadata: {
    resourceId: number;
    tilewidth: number;
    tileheight: number;;
    properties?: TiledProperty[];
  };
};
type ProjectResource = ILoaderResource & { metadata: ProjectMetadata };
```

And I'd like my loader resources to be typed with ProjectResource out of the box.
```ts
  const { loader } = useApp();
  const resource = resourceId ? loader.resources[resourceId] : null;  // type should be ProjectResource | null
```

Right now, I have to cast the type everytime I use useApp, as follow:
```ts
  const { loader } = useApp();
  const resource = resourceId
    ? (loader.resources[resourceId] as ProjectResource)
    : null;
```

Do you have any suggestion to get the types set correctly ?
Couldn't we make useApp a generic, to call as follow ?
```ts
type ProjectApp = PIXI.Application & { loader: PIXI.Loader & { resources: ProjectResource[] } };

...
  const { loader } = useApp<ProjectApp>();
  const resource = resourceId ? loader.resources[resourceId] : null;
```

### Additional info

- `@inlet/react-pixi` version: 6.2.1
- `React` version: 17.0.1
- `ReactDOM` version: 17.0.1
- `PIXI` version: pixi.js-legacy 6.0.0

**Comment by inlet** [comment]
Hi @AdrienLemaire,

I’ve been playing with this as well.

But if we have a more thorough look at metadata we can say that it’s related to a specific resource.. (not to all) but at level we don’t know what resources are available to us and potentially different resources could have different metadata set to it.

If it was intended to type resource meta I believe the types of `PIXI.Application` would be a generic (which is not).

As the metadata is project specific, I believe it’s best to have a custom `useResourcedApp` hook in your own project that you can type via a generic where you return a typed `PIXI.Application` to fit your needs.

Thanks for contributing and let me know what you came up with :)
