### ISSUE TITLE
AnimatedSprite should support FrameObject[]

### ISSUE THREAD

**Issue by AdrienLemaire** [inlet/react-pixi#290]
Error received
```
Uncaught Invariant Violation: AnimatedSprite texture needs to be typeof `PIXI.Texture
```

Documentation: https://pixijs.download/dev/docs/PIXI.AnimatedSprite.html#constructor

An AnimatedSprite can accept either a list of Texture of a list of [FrameObject](https://pixijs.download/dev/docs/PIXI.AnimatedSprite.html#FrameObject)

Please remove the invariant error when calling `<AnimatedSprite textures={frameObjectList} />`
Thanks!

**Comment by inlet** [comment]
Good point! I'll update the invariant check

**Comment by inlet** [comment]
Fixed, strangely `PIXI.AnimatedSprite.FrameObject` does not exist.. so instead I check for the owner properties to be valid

**Comment by AdrienLemaire** [comment]
Thank you !
