### ISSUE TITLE
[Feature Request] Add layout system

### ISSUE THREAD

**Issue by pynixwang** [inlet/react-pixi#294]
https://github.com/lunarraid/react-pixi-layout

this package has layout but no hook.

**Comment by pynixwang** [comment]
through `typeflex` a `yoga` port

**Comment by inlet** [comment]
Hi @pynixwang 

Thanks for sharing! I don’t have any plans for integrating layout really. This would have a huge impact on the footprint and I believe it’s better to separate the desired layout logic into another package. 

However don’t let me stop you, you can easily extend react-pixi and combine it with layout as this lib exports all the components you need. 

Please feel free to create another npm package which does purely layout, if you need anything from me let me know.

Thanks!
