### ISSUE TITLE
Uncaught Error: Could not find ID for Fiber "Canvas"

### ISSUE THREAD

**Issue by AdrienLemaire** [inlet/react-pixi#299]
### Description
We've been noticing this warning for the past couple days, but cannot figure out what this is about, what problems it's creating and how to solve it.

![](https://i.imgur.com/Y54C4ez.png)

Might you have any idea about it ?

### Additional info

- `@inlet/react-pixi` version: 6.5.2
- `React` version: 17.0.2
- `ReactDOM` version: 17.0.2
- `PIXI` version: pixi.js-legacy@6.0.4

**Comment by AdrienLemaire** [comment]
@inlet got it. The issue started after upgrading the chrome plugin [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi). 
Can you look into this ? I guess it fails to understand how to read fibers generated by react-pixi

**Comment by AdrienLemaire** [comment]
Or maybe they already fixed it here ? https://github.com/facebook/react/commit/132b72d7b668cbdabb06a44bd62979b212fc8b6d#diff-0b1d99a530095ba9262958e2fc44878dedef4e175ed45ec3df3982e5b64538c1R12

**Comment by inlet** [comment]
Thanks! I'm experiencing the same thing 😞

The react-reconciler is not updated so that cannot be the issue.. 

I've updated my extensions but react-devtools are still on `4.13.3`:
![image](https://user-images.githubusercontent.com/232559/119104079-235bc700-ba1c-11eb-9067-6fe7e7d15a3d.png)

Hopefully they fixed this in the new release

**Comment by inlet** [comment]
Just updated react devtools to `4.13.4` but no luck. 

All examples on [react-fiber-tree](https://docs.pmnd.rs/react-three-fiber) outputs the same `Could not find ID for Fiber` warning.

I guess we'll need to wait for a fix

**Comment by BasixKOR** [comment]
My components fail with warnings like below and I think this might be the cause of it, since I can see the `Could not find ID for Fiber` message too.

```
React instrumentation encountered an error: Error: Could not find ID for Fiber "Canvas"

**Comment by inlet** [comment]
Somehow the `Could not find ID for Fiber` error is gone. @AdrienLemaire can you verify it's working on your end?

**Comment by AdrienLemaire** [comment]
Looks fine. Now running react devtools 4.13.4 (5/20/2021)

**Comment by AdrienLemaire** [comment]
hmmm... I can see again warnings in my local env
![](https://i.imgur.com/HyqEVNg.png)

Still using the same packages version as mentionned above, and React Developer Tools
4.13.4 (5/20/2021)

**Comment by inlet** [comment]
It's not related to react-pixi really, I get the same error when using react-dom in conjunction with `<Suspense>`. Seems like a bug in react devtools

**Comment by inlet** [comment]
@AdrienLemaire there's been another update, I've updated to `4.13.5` and now the warning is gone. Can you verify this?

**Comment by AdrienLemaire** [comment]
LGTM
