### ISSUE TITLE
Nothing rendering when using react-spring

### ISSUE THREAD

**Issue by vocksel** [inlet/react-pixi#300]
### Description

I've been unsuccessful getting react-spring to render Sprites while following the react-pixi documentation. As such, I've dug through issues on this repo and came across the codepen example [here](https://github.com/inlet/react-pixi/issues/244#issuecomment-696749836), which works in the codepen sandbox, but copying the same code verbatim locally does not render the Sprite.

App.js
```js
import { useState } from 'react';
import { Sprite, Stage } from '@inlet/react-pixi/animated';
import { Spring } from 'react-spring';
import { Texture } from 'pixi.js';

const config = {
    size: () => ({ width: window.innerWidth, height: window.innerHeight }),
    spring: { mass: 10, tension: 1000, friction: 100 },
    stage: { antialias: true,autoDensity: true,  backgroundColor: 0xff0ff0, resizeTo: window }
};

const set = () => ({
    x: Math.random() * config.size().width,
    y: Math.random() * config.size().height,
    rotation: Math.random() * 10,
    scale: Math.max(1, Math.random() * 10)
});

const Box = (props) => (
    <Spring native to={props} config={config.spring}>
        {(props) => (
            <Sprite texture={Texture.WHITE} tint={0xaddb67} anchor={0.5} {...props} />
        )}
    </Spring>
);

const App = () => {
    const [transform, setTransform] = useState(set);
        return (
        <Stage
            {...config.size()}
            options={config.stage}
            onPointerUp={setTransform.bind(null, set)}
        >
            <Box {...transform} />
        </Stage>
    );
};

export default App
```

index.js
```js
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App.jsx';

ReactDOM.render(
    <React.StrictMode>
        <App />
    </React.StrictMode>,
    document.getElementById('root')
);
```

Examining the `props` object in the Box component gives an object of `{ x, y }` which is expected. However `x` and `y` are both objects themselves, and look to be instances from react-spring for animating the values. I would expect `x` and `y` to be the actual numeric values as they animate to their goal values, but I'm not sure if this is just how react-spring does things or if this is a problem with react-pixi.

Been pulling my hair out over this for a while, so would appreciate some insight!

### Additional info

- `@inlet/react-pixi` version:  ^6.5.2
- `React` version: ^17.0.2
- `ReactDOM` version: ^17.0.2
- `PIXI` version: ^6.0.4
- `react-spring` version: ^9.0.0-rc.3

**Comment by inlet** [comment]
It should work, here's a super simple example:

[react-spring-example.zip](https://github.com/inlet/react-pixi/files/6528497/react-spring-example.zip)

**Comment by vocksel** [comment]
Got it thank you! Was a dependency issue with react-spring.
