### ISSUE TITLE
Error when using Text components in @inlet/react-pixi/animated

### ISSUE THREAD

**Issue by ivgtr** [inlet/react-pixi#301]
### Description
When I try to use the Text component in @inlet/react-pixi/animated, an error message appears and I cannot use it.
Of course the Text component imported from @inlet/react-pixi works.

This is the simplest code to reproduce.
`App.tsx`
```tsx
import { Stage, Text } from "@inlet/react-pixi/animated";
import React from "react";

export default function App() {
  return (
    <div className="App">
      <Stage>
        <Text text={"Error when using Text components"} />
      </Stage>
    </div>
  );
}
```
- codesandbox: [link](https://codesandbox.io/s/inspiring-silence-grj88?file=/src/App.tsx)

I'm sorry if there is a problem with my implementation.

### Additional info

- `@inlet/react-pixi` version: ^6.5.2
- `React` version: ^17.0.2
- `ReactDOM` version: ^17.0.2
- `PIXI` version: ^6.0.4
-  `react-spring` version: ^9.2.1

**Comment by inlet** [comment]
Fix is on its way

**Comment by inlet** [comment]
It works in `@inlet/react-pixi@6.5.3`

**Comment by inlet** [comment]
Here's a demo https://codepen.io/inlet/pen/f926a4cbb39f6bba757cc46ee15f2245?editors=1010

**Comment by ivgtr** [comment]
Cool!!
This fix works correctly in my project.
Thank you for the quick fix, @inlet .
