### ISSUE TITLE
Error: Expected subtree parent ... with react 18 alpha

### ISSUE THREAD

**Issue by samanrnr** [inlet/react-pixi#306]
### Description
Stage component does not work with react 18

is there any way to solve this problem before releasing new update?

### Steps to reproduce

1.
2.

### Additional info

- `@inlet/react-pixi` version: 6.6.2
- `React` version: 18.0.0-alpha-73ffce1b6-20210624
- `ReactDOM` version: 18.0.0-alpha-73ffce1b6-20210624
- `PIXI` version: 6.0.4

**Comment by inlet** [comment]
This is because we depend on `react-reconciler`, once React 18 gets stable we can update the host config to meet the new `react-reconciler` api

**Comment by unicornware** [comment]
@inlet are there are any temporary solutions?

**Comment by inlet** [comment]
@unicornware I haven't got the time to make this library react 18 compatible, but please feel free to open a PR and we can work together on the implementation.

**Comment by inlet** [comment]
Great to hear you've found a workaround! I'll see if I have time the coming weeks to update this library
