### ISSUE TITLE
Incorrect type for useTick callback

### ISSUE THREAD

**Issue by CreativeTechGuy** [inlet/react-pixi#309]
### Description

The type for `useTick` as seen [here](https://github.com/inlet/react-pixi/blob/master/index.d.ts#L428) indicates that the argument to the callback function `delta` could possibly be undefined. Referencing the pixi source type [TickerCallback](https://github.com/pixijs/pixijs/blob/170e890aad69828c394417cafbb3c0a0d928e8d3/packages/ticker/src/Ticker.ts#L5) it shows that `dt` is always present.

I'd recommend using the type from pixijs to ensure that it's the same and doesn't diverge.

### Steps to reproduce

* See above

### Additional info

- `@inlet/react-pixi` version: 6.6.3
- `React` version: 17.0.2
- `ReactDOM` version: 17.0.2
- `PIXI` version: 6.1.0

**Comment by CreativeTechGuy** [comment]
Also, I think there's some missing functionality also. In `pixi` the ticker listener is called with `this === Ticker` to allow the ticker handler function to access other properties of the ticker object (such as `elapsedMS`, `FPS` and more).

In the current implementation of `useTick` the callback cannot access `this`. I'd like to have access to that to match the functionality of Pixi.

**Comment by inlet** [comment]
Good point! We can add the ticker instance as the second argument as the hook will be often used with dash array function.

Feel free to create a PR, thanks!

**Comment by inlet** [comment]
Fixed in the new release https://github.com/inlet/react-pixi/releases/tag/v6.6.4

**Comment by CreativeTechGuy** [comment]
Oh dang you are fast. I didn't get a chance to reply. haha

I was going to ask why you wanted to pass a second argument instead of using `.apply` but I see you did both! Wonderful. 😄
