### ISSUE TITLE
Expose more private types

### ISSUE THREAD

**Issue by CreativeTechGuy** [inlet/react-pixi#310]
### Description

When creating React components that wrap react-pixi components while using TypeScript, it's sometimes necessary to use Types that are currently only available in the private `_ReactPixi` namespace. For example [InteractionEvents](https://github.com/inlet/react-pixi/blob/master/index.d.ts#L161-L165) is useful when creating a component that will pass any event handlers to an interactable element.

I don't see a reason to not export many of these types for users who may want them.

### Steps to reproduce

* N/A

### Additional info

- `@inlet/react-pixi` version: 6.6.3
- `React` version: 17.0.2
- `ReactDOM` version: 17.0.2
- `PIXI` version: 6.1.0

**Comment by inlet** [comment]
Sure, feel free to create a PR with the exported types

**Comment by inlet** [comment]
Fixed in #311
