### ISSUE TITLE
A small suggestion: add a link to github repo at the documentation nav menu

### ISSUE THREAD

**Issue by lanyusan** [inlet/react-pixi#319]
I found this lib's doc site reactpixi.org by googling `react pixi` and found it a good fit for a project by going through it. It took me a while to look for the github link.

I think it would be very convenient for readers if you put an explicit link to your github repo at your nav menu.

Just a minor suggestion.

**Comment by inlet** [comment]
Thanks good one! I'll see if I can add one

**Comment by inlet** [comment]
Done, just added the link to the docs.. thanks for pointing out!
