### ISSUE TITLE
Update to pixi.js 6.3 once it updates

### ISSUE THREAD

**Issue by Specy** [inlet/react-pixi#323]
### Description
In the new 6.3 version there will be support for server side apps, not giving errors when the library is loaded server side, i'd hope you could update to that version so that it will be easier to use this module in apps that use server side rendering
https://github.com/pixijs/pixijs/pull/8050

**Comment by inlet** [comment]
Thanks for the suggestion, although I'm not planning to implement this on short term. 

However feel free to collaborate and create a PR with the implementation and tests. Thanks!
