### ISSUE TITLE
PIXI.Rectangle should have `intersects` method, but doesn't?

### ISSUE THREAD

**Issue by Heilemann** [inlet/react-pixi#324]
Here's a rectangle I made, note the methods it has do not include `intersects`, but the [pixi.js documentation lists it as a method it should have](https://pixijs.download/release/docs/PIXI.Rectangle.html#intersects). Am I doing something wrong?

<img width="432" alt="CleanShot 2022-02-15 at 19 46 10@2x" src="https://user-images.githubusercontent.com/203049/154174781-8e4d7f63-2b21-4d3c-99bd-1309c2374c92.png">

**Comment by Heilemann** [comment]
But then [this other version of the doc doesn't have `intersects`](https://pixijs.download/v6.0.0/docs/PIXI.Rectangle.html), so I'm confused. Both seem to be v6.2.2?

**Comment by inlet** [comment]
Hi @Heilemann,

Please file an issue in the Pixi.js repo, this is related to Pixi itself (not this library).
I'll close this issue, please let me know if you think we should reopen it.

Thanks!
