### ISSUE TITLE
Use GraphicsGeometry to initialise Graphics to reduce memory footprint

### ISSUE THREAD

**Issue by vijayth2-cerebras** [inlet/react-pixi#327]
### Description
Graphics component has only a draw method. It will be nice if it also accepts GraphicsGeometry object as a prop. If the prop is available, the draw function will get a Graphics object created from the GraphicsGeometry object. This helps in reducing the memory footprint.

### Steps to reproduce
Playground without optimisation - https://www.pixiplayground.com/#/edit/Oq-cKLUW9M_Ar5Vykdk-8
Playground with optimisation - https://www.pixiplayground.com/#/edit/1gOysJgodOn7sDUvJlPIx

The first one uses a memory of 250MB. The second one optimises and uses 20MB. (From the Memory tab in Chrome DevTools)

**Comment by inlet** [comment]
Hi Vijay

Thanks for contributing to the project. Yes we could add a `geometry` prop that will set `new Graphics(geometry)` in the constructor. This same graphics will then be passed to the `draw` method. 

Can you please share a snippet how you would approach this in plain PIXI/javascript, thanks!

**Comment by inlet** [comment]
Also feel free to create a PR with the fix

**Comment by inlet** [comment]
Hi @vijayth2-cerebras, any updates on this?

**Comment by vijayth2-cerebras** [comment]
Sorry got busy with something else. I will raise a PR shortly.


________________________________

**Comment by inlet** [comment]
Thanks Vijay that would be great!
