### ISSUE TITLE
Feature request onDimensionChange

### ISSUE THREAD

**Issue by EloB** [inlet/react-pixi#33]
I'm not sure if it's possible to add (maybe because of performance reasons) but it would be nice to somehow listen to a prop `onDimensionChange` or add some example how to getting the dimension from an object 😃

**Here is one use case:**
```jsx
<Text text={someDynamicString} onDimensionChange={handleResize} />
```

*How do I get the text dimension?*

**Comment by EloB** [comment]
Thanks for quick answer! I didn't know about that TextMetrics method :) Good one! Right now it's pretty hard to get the size of an object in general. I thought there was a smarter way. But now I at least know how to do it 😅

**Comment by inlet** [comment]
Totally agree! Glad it helped, I'll close this issue now 😉
