### ISSUE TITLE
How to make react-router works?

### ISSUE THREAD

**Issue by zzmingo** [inlet/react-pixi#330]
For examples:

```jsx
function App() {
  return (
    <Stage>
      <Outlet/>
    </Stage>
  )
}

function Inner() {
  return <Sprite />
}

// render
<HashRouter>
  <Routes>
     <Route path="/game" element={<App />}>
       <Route path="/inner" element={<Inner />}/>
     </Route>
  </Routes>
</HashRouter>
```

`Inner` should be render when push path to `/game/inner`,  but actually not.

**Comment by inlet** [comment]
Should work indeed, can you please create a sample on codesandbox/codepen? Thanks

**Comment by zzmingo** [comment]
After looking at ContextBridge, the issue was solved by bridging LocationContext and NavigationContext of `react-router`.
