### ISSUE TITLE
update pixi.js dep to 6.3.0

### ISSUE THREAD

**Issue by spassvogel** [inlet/react-pixi#332]
### Description
After updating pixi.js in my project to [6.3.0 ](https://github.com/pixijs/pixijs/releases/tag/v6.3.0) I'm getting a typescript error

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/985892/160303010-db89ee26-d68f-449d-9a6a-5427fa4717fa.png">

### Additional info

- `@inlet/react-pixi` version:      "@inlet/react-pixi": "^6.6.5",
- `React` version:     "react": "^17.0.2",
- `ReactDOM` version:
- `PIXI` version:     "pixi.js": "^6.3.0",

**Comment by inlet** [comment]
I think it has something to do with `PixiViewport`, can you please share a codesandbox with a demo? thanks in advance!

**Comment by spassvogel** [comment]
So weird.. the problem went away after deleting node_modules and reinstalling deps.. thx !

**Comment by inlet** [comment]
That's odd indeed, but glad the issue is resolved. Thanks!
