### ISSUE TITLE
Multiple apps rendered simultaneously

### ISSUE THREAD

**Issue by Ledzz** [inlet/react-pixi#339]
### Description
If using more than one app on the page, they all are rendered simultaneously.
I'd like to create PR to fix this behavior.
My idea is to fire `__REACT_PIXI_REQUEST_RENDER__ ` events on the canvas instead of window.
@inlet are you ok with this approach? If yes, I'll make a PR in a few days.

**Comment by inlet** [comment]
Thanks @Ledzz good point!

It does indeed make sense to move the events to the canvas element.
Thanks you for your collaboration, looking forward to review your PR. 

Please add tests for multiple scenario's. 

Thanks 🙏
