### ISSUE TITLE
Multiple console.log inside latest build that floods the console

### ISSUE THREAD

**Issue by EloB** [inlet/react-pixi#34]
It's killing my app 😄

You can search for `console.log` and you will find a bunch. One of the console.log contains es6 content that breaks non es6 browsers.
https://unpkg.com/@inlet/react-pixi@0.1.3/dist/react-pixi.development.umd.js

<img width="528" alt="screen shot 2018-08-20 at 15 51 30" src="https://user-images.githubusercontent.com/476567/44344582-5a7aa380-a491-11e8-8df1-20f3cbf4c42f.png">
<img width="999" alt="screen shot 2018-08-20 at 15 51 52" src="https://user-images.githubusercontent.com/476567/44344583-5a7aa380-a491-11e8-9187-827a61766e5a.png">

**Comment by inlet** [comment]
Oops, I accidentally pushed a modified reconciler to npm.

I just created a patch 👉 v0.1.4, please update and try again.
Sorry for any inconvenience.
