### ISSUE TITLE
Typescript error when add children to a Container component (may be related with React 18)

### ISSUE THREAD

**Issue by dcaminos** [inlet/react-pixi#341]
### Description
I'm getting a typescript error only when add children to any Container

<img width="758" alt="Screen Shot 2022-05-06 at 08 54 13" src="https://user-images.githubusercontent.com/22157341/167126544-5895cfdf-d86b-4a73-b119-ee5efd51b310.png">

### Steps to reproduce

1. Just add any kind of children to a Container component

### Posible solution

Replace `export const Container: React.FC<_ReactPixi.IContainer>;` 
for `export const Container: React.FC<PropsWithChildren<_ReactPixi.IContainer>>;` 
on this line: https://github.com/inlet/react-pixi/blob/05babb2e684905364794af861acd15e0d64ec9de/index.d.ts#L359

**Comment by dcaminos** [comment]
Yes I'm `@types/react": "^18.0.8"`

**Comment by inlet** [comment]
Yes that's causing the issue, we're working on a React 18 implementation

**Comment by inlet** [comment]
If you switch back to React 17 this will work

**Comment by inlet** [comment]
I'll close this issue as this is related to #338. Once react-pixi is working with React 18 this should also be fixed
