### ISSUE TITLE
I tried to install this package after create react-app newly, but it's been failed.

### ISSUE THREAD

**Issue by romansavchuk1** [inlet/react-pixi#344]
### Description
I tried to install this package after create react-app, but it's failed.
![image](https://user-images.githubusercontent.com/106656648/172207706-09f6b5dc-b8c7-46de-b0e1-336f7ef310ae.png)

### Steps to reproduce

1. npx create-react-app my-app
2. npm install @inlet/react-pixi --save

### Additional info

- `@inlet/react-pixi` version: 
- `React` version: 18.1.0
- `ReactDOM` version: 18.1.0
- `PIXI` version:

**Comment by mark-strudwick** [comment]
This is also failing for me. I believe it's because react is now on version 18, but this only supports 17

**Comment by inlet** [comment]
Yes this is because this lib is not yet compatible with React 18

**Comment by romansavchuk1** [comment]
I see, I solved it by changing of react version.
