### ISSUE TITLE
I tried to use useTick, but An error has been appeared.

### ISSUE THREAD

**Issue by romansavchuk1** [inlet/react-pixi#345]
### Description
I tried to use useTick, but An error has been appeared in React.
![2022-06-07_14h26_53](https://user-images.githubusercontent.com/106656648/172377458-1f8d1eff-ff01-40f9-8a29-6e94eb6aa2b1.png)
![2022-06-07_14h27_24](https://user-images.githubusercontent.com/106656648/172377470-e8943861-2a6d-4baa-8e40-e290fdd049af.png)

### Steps to reproduce

1.
2.

### Additional info

- `@inlet/react-pixi` version: 
- `React` version:
- `ReactDOM` version:
- `PIXI` version:

**Comment by inlet** [comment]
You must wrap the component with `<Stage>` as stated in the error message

**Comment by romansavchuk1** [comment]
![image](https://user-images.githubusercontent.com/106656648/172379332-f53d3327-c096-4eba-9876-aa47deafe09a.png)

But same error has been appeared.

**Comment by inlet** [comment]
You need to wrap the `NumberAnimation` component in `<Stage>`: 

```jsx
const App = () => (
  <Stage>
    <NumberAnimation />
  </Stage>
);
```

**Comment by romansavchuk1** [comment]
I got it, I solved it.
