### ISSUE TITLE
Any way to run destroy() of PIXI.Sprite?

### ISSUE THREAD

**Issue by MorookaKotaro** [inlet/react-pixi#346]
### Description
I have this following code, but it causes memory leaking only in Safari, since the Sprite is completely removed. (seems GC not working)

```jsx
return (
  <Sprite
    texture={loader.resources[images[index]].texture} // index is set constantly based on user action
  />
)
```

<img width="716" alt="image" src="https://user-images.githubusercontent.com/62707539/173523779-00e3666b-3fa9-4f12-a239-d3d0471e025c.png">

I simulated the same situation with raw PIXI.js. I guess, since the destroy method is running, the memory is not leaking.
https://codesandbox.io/s/staging-architecture-tl7v0x?file=/src/index.ts

I'd like to know how to use destroy method with react-pixi, or other way to avoid memory leaking.

### Additional info

- `@inlet/react-pixi` version: ^6.6.5
- `React` version: ^17.0.2
- `ReactDOM` version: ^17.0.2
- `PIXI` version: ^6.2.2

**Comment by inlet** [comment]
On the other hand, in your code above the Sprite never gets destroyed because it will never unmount. Which is good.. you are only changing the texture.

It might be possible that there's something else happening in your code that's causing the memory leak?

**Comment by MorookaKotaro** [comment]
Hello @inlet 

Thank you for replying.
Okay, I'll create react-pixi demo in a moment.

> Sprite never gets destroyed because it will never unmount.

Yes, that's exactly what I was thinking. 
Since only the texture changes, Sprite will never unmount.
Which means new Sprite object is created every time as the texture changes, though the older ones are not removed.
That's why I was looking for the way to run destroy method manually.

Anyway, I'm going to create the demo!

**Comment by inlet** [comment]
> Which means new Sprite object is created every time as the texture changes, though the older ones are not removed.
That's why I was looking for the way to run destroy method manually.

Only 1 Sprite object will be created only the `texture` member will be updated

**Comment by MorookaKotaro** [comment]
@inlet 

Hmm.. It seems working well with minimum demo...
https://codesandbox.io/s/frosty-darkness-wvs8ds?file=/src/index.tsx

It could be my source code's fault. 
Sorry for opening a mistaken issue :_(

I'm going to investigate more, then I will contact you if anything founded.

Thank you.

**Comment by inlet** [comment]
Sure, keep me posted so I can close this issue. Thanks!

**Comment by MorookaKotaro** [comment]
Hello @inlet 
I may found the issue. 
As the total image size is larger, the memory seems never released in Safari. 
![image](https://user-images.githubusercontent.com/62707539/173754467-f3a0147d-e00e-414f-b71e-366b9d3f9149.png)

On the other hand, in Chrome, JS Heap size works well.
![image](https://user-images.githubusercontent.com/62707539/173755855-0b8853c8-9086-4cec-b9db-baaca1dfe82f.png)

I would appreciate it if you could check my demo.

demo: https://codesandbox.io/s/jolly-water-equs3i

**Comment by inlet** [comment]
I don’t see any issues with your demo, it must have to do something with how Safari handles GPU GC. 

It might be worth filing an issue in the PIXI repo? Have you tried it with vanilla PIXI?

**Comment by MorookaKotaro** [comment]
> I don’t see any issues with your demo

It might be because of machine's speck. I'll make it load more image, then you could see the issue.

> Have you tried it with vanilla PIXI?

Yes. The first one is with vanilla.
When the destroy method is not called, the memory graph looks similar as the one with react-pixi
https://codesandbox.io/s/staging-architecture-tl7v0x?file=/src/index.ts

**Comment by inlet** [comment]
Right so we can confirm the same logic happens with vanilla PIXI. 

I’ll close this issue as it’s not related to react-pixi but with PIXI in general

**Comment by inlet** [comment]
Have you tested it out with Sprite that’s getting removed? As you can see in our reconciler tests all unmounted components are getting destroyed properly.

https://github.com/inlet/react-pixi/blob/master/test/reconciler.test.js#L309

**Comment by inlet** [comment]
In your example you’re updating the `texture` prop, please try setting a `key` prop that unmounts the old and mounts a new one

**Comment by MorookaKotaro** [comment]
@inlet 
FYI:
Although it actually works with following code to some extent, it's necessary to set a key prop on Stage component  for much heavier images..
(By the way, it didn't work to set a key prop on Sprite component)
```jsx
<Contaienr key={state}>
  <Sprite
    ...
    texture={state}
  />
</Container>
```

**Comment by inlet** [comment]
Thanks for the reference 😁
