### ISSUE TITLE
Use of SmoothGraphics

### ISSUE THREAD

**Issue by Thel27** [inlet/react-pixi#349]
### Description
Hello ! First of all, a big thanks for this library. It's really cool !
For the context : I'm a young student currently working in internship in a startup and I'm making a DXF file editor with Pixi using your library.
I use PixiViewport that I integrate in my app like [in your codepen](https://codepen.io/inlet/pen/yLVmPWv)
I would like to have very thin line like in [this example](https://pixijs.io/examples/#/plugin-graphics-smooth/thin-square.js) of SmoothGraphics plugin.

Because as you can see : 
![image](https://user-images.githubusercontent.com/33833440/176906907-ccc34c3b-a945-4fc3-80c7-a76443d47288.png)
My lines aren't really thin and precise.

Is it hard to add ?
I think I can "bypass" my problem by adding SmoothGraphics lines directly in the app stage like in the example above but It doesn't sound really clean.

Maybe I missunderstood one thing and I can already have this type of lines with your lib ?

*(Sorry for my bad english, I'm still learning)*

### Additional info

- `@inlet/react-pixi` version: 5.2.0
- `React` version: 16.13.0
- `ReactDOM` version: 16.13.0
- `PIXI` version: 5.3.3
- `PIXI-viewport` version: 4.17.1

**Comment by inlet** [comment]
Hi @Thel27,

You can achieve this with [custom components](https://reactpixi.org/custom-components), just create a custom component that creates a `PIXI.smooth.SmoothGraphics` component and you're set 😁

**Comment by Thel27** [comment]
Hello, thank you for your answer. The problem is that I have already tried but was not successful. I want to keep the same syntax as your \<Graphics\> component with the draw method because my whole application uses it...

Is it possible? If yes, how?

One of my attempts : 

```javascript
import React, { forwardRef } from "react";
import * as PIXI from "pixi.js";
import { applyDefaultProps, PixiComponent } from "@inlet/react-pixi";
import { SmoothGraphics, SmoothGraphicsGeometry } from "@pixi/graphics-smooth";

export interface SmoothGraphicsProps {
  draw?(graphics: SmoothGraphics): void;
  interactive: boolean;
  buttonMode: boolean;
  pointerdown: (event: PIXI.InteractionEvent) => void
  pointerup: (event: PIXI.InteractionEvent) => void
  pointerupoutside: (event: PIXI.InteractionEvent) => void
  pointermove: (event: PIXI.InteractionEvent) => void
}

export interface PixiComponentSmoothGraphicsProps extends SmoothGraphicsProps {
  app: PIXI.Application;
}

const PixiComponentGraphicSmooth = PixiComponent("GraphicSmooth", {
  create: (props: any) => { // using type PixiComponentSmoothGraphicsProps doesn't work
    const { app, ...smoothGraphicsProps } = props;
    const smoothgraphic = new SmoothGraphics({
      ...smoothGraphicsProps
    });

    return smoothgraphic;
  },
  applyProps: (instance: any, _oldProps: any, _newProps: any) => {
    const { plugins: oldPlugins, children: oldChildren, ...oldProps } = _oldProps;
    const { plugins: newPlugins, children: newChildren, ...newProps } = _newProps;

    Object.keys(newProps).forEach((p) => {
      if (oldProps[p] !== newProps[p]) {
        instance[p] = newProps[p];
      }
    });
  }
});

const GraphicSmooth = forwardRef((props: SmoothGraphicsProps, ref) => {
  return <PixiComponentGraphicSmooth ref={ref} {...props} />;
});

export default GraphicSmooth;
```

**Comment by Thel27** [comment]
Hi, thanks for the respond. I just can't use GraphicSmooth anyway because it's not available on pixi js v5
