### ISSUE TITLE
UglifyJs: Unexpected token: punc (})

### ISSUE THREAD

**Issue by smith-chris** [inlet/react-pixi#35]
### Description

When I try to uglify the build I'm getting this:
```
ERROR in bundle.js from UglifyJs
Unexpected token: punc (}) [./node_modules/@inlet/react-pixi/dist/react-pixi.development.es5.js:9765,19][bundle.js:59126,28] 
```
That confusingly points to line:
```      console.log({hostFiber});```

It didnt happen before i started using `@inlet/react-pixi`

### Steps to reproduce

1. clone the repo (https://github.com/smith-chris/poke/tree/d6d07a556accbef4962037789049a6cc592cb681) and follow the instructions (you probs just need to `npm i`
2. run `npm run prod` to see the error appear

### Additional info

I'll just link specific tree to reproduce: https://github.com/smith-chris/poke/tree/d6d07a556accbef4962037789049a6cc592cb681

You can also see that commit before that used `react-pixi-fiber` and it does not have the same problem: https://github.com/smith-chris/poke/tree/aa73b342232c83acb15a70abdf3e6b2150da0abb

I hope that all the info you need to reproduce that issue. BTW I really like how painless it was to switch to this lib from `react-pixi-fiber` and I find yours ~30% faster. Good stuff!

Cheers,
Chris

EDIT:
I've updated all my dependencies and error still appears. 

Now I think about it the problem is that you have object literal property value shorthand which is ES6. I guess my uglifyjs is setup in a way that it expects es5 and I could change that but giving that the name of the file is `react-pixi.development.es5.js` it should be fixed somewhere within `react-pixi` build setup.

**Comment by inlet** [comment]
Hi @smith-chris,

I accidentally pushed a modified reconciler to v0.1.3 😱

Just pushed a new version, please update react-pixi to `0.1.4` and try again.
Let me know if this solved it, thanks!

**Comment by smith-chris** [comment]
Tested, uglifying works now :) thanks @inlet
Still *.es5* files are not es5 compatible. This is what es-check gives as a reason:
```error: SyntaxError: The keyword 'import' is reserved (1:0)
          · see the printed err.stack below for context```

If thats not intended then it's worth looking at pr I raised https://github.com/inlet/react-pixi/pull/36

**Comment by inlet** [comment]
Hi @smith-chris,

I think we need to redefine the output formats. Get rid of the es5 format as the umd versions is basically the same. Only having these:

- cjs
- umd
- es (module)

What do you think?

**Comment by smith-chris** [comment]
Just tested and it seems like umd can be used as a script tag (for those 1% of people) so yeah, I think its a good idea :)
