### ISSUE TITLE
Discussion about be able to use Stage in Stage?

### ISSUE THREAD

**Issue by EloB** [inlet/react-pixi#39]
It would be kind of interesting to be able to use a `Stage` within a `Stage`. By doing so you should be able to turn off `raf` on a specific branch on your React tree. What do you think? 😃

**Comment by inlet** [comment]
Hi @EloB,

Do you have a certain use case for it? Right now this doesn't work as the `<Stage>` renders a canvas element and use the React reconciler to inject the PIXI components.

A PIXI application regularly has one stage instance to render from. I think that the current Stage object will fit 99% of all use cases. If you need some custom logic like multiple stage objects or have custom behavior perhaps it's better to write a custom Stage component using `import { render } from '@inlet/react-pixi'`. See https://reactpixi.org/#/#install (Without React-DOM). 

Or use the `PixiFiber`, for example:

```jsx
import React from 'react'
import * as PIXI from 'pixi.js'
import { PixiFiber } from '@inlet/react-pixi'

const { createContainer, updateContainer } = PixiFiber

export default class Stage extends React.Component {
  stage = new PIXI.Container()
  renderer = null
  mountNode = null
  canvas = React.createRef()

  componentDidMount() {
    this.renderer = new PIXI.autoDetectRenderer(800, 600, { view: this.canvas })
    this.mountNode = createContainer(this.stage)

    updateContainer(this.props.children, this.mountNode, this)
  }

  componentWillUnmount() {
    updateContainer(null, this.mountNode, this)
    this.renderer.destroy()
  }

  render() {
    return <canvas ref={this.canvas} />
  }
}
```

Please let me know what you think.

Thanks!

**Comment by EloB** [comment]
This could work 😃

I'm working on low CPU/GPU and on legacy webkit devices. So to be able to turn off the ticker on certain parts of the view would increase the performance a bit. Right now I use the `cacheAsBitmap` but I think the reconciliation is still inside there because some of my component listen to the ticker.

**Comment by EloB** [comment]
My idea is that you can take any Component and easily render anywhere.

```jsx
const Sidebar = props => (
  <Stage {...props}>
    <Text text="This is sidebar" />
  </Stage>
);
Sidebar.defaultProps = {
  width: 300,
  height: 1080,
};

const Content = props => (
  <Stage {...props}>
    <Text text="This is sidebar" />
  </Stage>  
);
Content.defaultProps = {
  width: 1920,
  height: 1080,
};

const App = ({ sidebar, ...props }) => (
  <Stage {...props}>
    <Lerp value={sidebar ? Sidebar.defaultProps.width : 0}>
      {value =>
        <Fragment>
          <Sidebar x={value - Sidebar.defaultProps.width} raf={value !== 0} />
          <Content x={value} />
        </Fragment>
      }
    </Lerp>
  </Stage>
);
```

**Comment by inlet** [comment]
Thanks @EloB for your kind words! Well, this library is a team effort. Together with people like you we can make it better. Thanks for contributing!

Now I see what you are trying to accomplish. 

Problem is that the Stage object handles the reconciler and having this kind of setup mix up the renderers, which, I'm afraid, will fail. 
And the default behaviour of a PIXI.Application is that it clears the complete canvas and runs a ticker when set (or having a shared one). Nested tickers will lead to performance issues. 

The only possible solution would be to separate the canvas elements (and have multiple renderers) and stack them on top of each other (like in your example).

Example (pseudo code, not tested 😄):

```jsx
import Sidebar from './Sidebar' // returns Container
import Content from './Content' // returns Container
import App from './App'         // returns Container

// ticker to update all
ReactDOM.render((
  <Stage>
    <App />
  </Stage>
), document.getElementById('fullApp'));

// only update stage on prop change
ReactDOM.render((
  <Stage raf={false}>
    <Sidebar />
  </Stage>
), document.getElementById('onlySidebar'));

// only update stage on prop change
ReactDOM.render((
  <Stage raf={false}>
    <Content />
  </Stage>
), document.getElementById('onlyContent'));
```

Feel free to create a PR and fiddle around, would love to see what you come up with 😊
