### ISSUE TITLE
TypeScript complains when using HTML attributes on a <Stage>

### ISSUE THREAD

**Issue by binary-koan** [inlet/react-pixi#47]
### Description

As I understand it, any HTML attributes can be passed to a `Stage` and will become attributes on the canvas it creates. However, this isn't reflected in the TypeScript type definitions so the compiler raises an error when I try to add a classname to my stage.

(Note: I'm currently working around the problem with `const HackyFixedStage = Stage as any` and the classname is correctly set on the canvas)

### Steps to reproduce

1. Add react-pixi to a TypeScript project
2. Try to add HTML attributes to a `<Stage>` element, for example: `<Stage className="some-class" />`
3. The compiler will complain that `Property 'className' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Stage> & Readonly<{ children?: ReactNode; }> & Readonly<IStageProps>'`

### Additional info

- `@inlet/react-pixi` version: 0.1.6
- `React` version: 16.5.1
- `ReactDOM` version: 16.5.1

I seems like adding `CanvasHTMLAttributes` to the Stage class definition in `index.d.ts` solves the problem:

`class Stage extends React.Component<_ReactPixi.IStageProps & React.CanvasHTMLAttributes<HTMLCanvasElement>> {}`

Or I guess you could make `IStageProps` extend `CanvasHTMLAttributes`? I don't know TypeScript's type system super well ...

Thanks for making this and including type definitions btw! I'm having a lot of fun 😄

**Comment by inlet** [comment]
Hi @binary-koan,

Thanks! You're totally right, extending the `CanvasHTMLAttributes` might solve this issue. Will fix this soon.. 

> Thanks for making this and including type definitions btw! I'm having a lot of fun 😄

Awesome!

**Comment by inlet** [comment]
Hi @binary-koan ,

I just pushed a fix (`v0.1.7`). It's working now 🙌 thanks for the help!

**Comment by binary-koan** [comment]
Awesome, can confirm it works. Thanks for the quick fix!
