### ISSUE TITLE
Feature request to add zIndex

### ISSUE THREAD

**Issue by EloB** [inlet/react-pixi#51]
I was thinking about `pixi-display`... Is there a easy way to use it?

https://github.com/pixijs/pixi-display

Right now I don't have that issue but it would be really good just be able to change zIndex without rearrange the react tree...

I'm not sure if this needs to be in core but it would be good to have some thoughts about it :)

**Comment by EloB** [comment]
I was thinking about array key solutions but what I've understand is that `pixi-display` is the more performant solution.

**Comment by inlet** [comment]
We could add `<Display>`, `<Layer>`, etc into `react-pixi`, but this definitely is a major update on the reconciliation. The idea behind React is that it handles the components in an ordered list (tree) and it defines in what order it should be rendered.

I think if we are considering implementing the `pixi.display` into `react-pixi`, there must first determine what problem we need to solve and in what manner. 

I can imagine that it could be handy to use it for portals; render a subset of components directly into something else. Or use these as container elements and add props like `zOrder` and `zIndex`.

Here's an idea:

```jsx
import { Stage, Layer, Sprite } from '@inlet/react-pixi'

function onSort(element) {
  console.log('element sorted', element)
}

const App = (
  <Stage>
    <Layer onSort={onSort} enableSort={true} respectDisplayChildrenBounds={true}>
      <Sprite image="image.png" zIndex={1} />
      <Sprite image="image.png" zIndex={3} />
      <Sprite image="image.png" zIndex={2} />
      <Sprite image="image.png" zIndex={4} />
    </Layer>
  </Stage>
)
```

**Comment by animify** [comment]
+1 for this. Adding props to the sprites sounds like a good idea

**Comment by naranjamecanica** [comment]
Just to let you know, zIndex is supported from `pixi v5`, see: https://github.com/pixijs/pixi.js/pull/5204

**Comment by inlet** [comment]
Thanks @naranjamecanica! Feel free to create a PR with the implementation.

**Comment by EloB** [comment]
> Just to let you know, zIndex is supported from `pixi v5`, see: [pixijs/pixi.js#5204](https://github.com/pixijs/pixi.js/pull/5204)

I've just read that is only changes the order and I'm not sure this would be good for react-pixi. It would be the same to change order of react elements. Looking into react-display might be necessary.
http://pixijs.download/dev/docs/PIXI.Container.html#sortableChildren

**Comment by inlet** [comment]
I agree with @EloB regarding the z-index. 

However maybe it’s an idea to implement the layering, it has some similarities with React portal, but instead it can render display items into another layer.

Just thinking out loud. Suggestions are welcome! Thanks

**Comment by EloB** [comment]
I might have to look into zIndex right now. I fade images over each other and adding/removing sprites on demand is not an option when it comes to smart tv:s. I think the most performant solution for me would be to have a pool of sprites that I have hide with `visible` and changing order with pixi-display.

Will start to investigating zIndex...

**Comment by inlet** [comment]
Btw, the current version of react-pixi works with Pixi `v5`, you can use `zIndex` and `zOrder`. I've created an example here: https://codepen.io/inlet/pen/mvzzLb

**Comment by EloB** [comment]
> Btw, the current version of react-pixi works with Pixi `v5`, you can use `zIndex` and `zOrder`. I've created an example here: https://codepen.io/inlet/pen/mvzzLb

Cool :) I've already have a similar solution right now but getting rate drops when adding/removing to simulate zIndex reordering... Will see if `pixi-display` can improve the performance...

**Comment by inlet** [comment]
We now support pixi v5 🎉
