### ISSUE TITLE
Sprite does not show on stage

### ISSUE THREAD

**Issue by rabiaasif** [inlet/react-pixi#52]
<Stage width={800} height={700} options={{ antialias: true }}>

< Sprite
      x={100}
      y={100}
      image={marble} scale={scale} />

  < /Stage>

I have this inside my stage, where scale is 1:1, and marble is  
const marble = 'https://s3.ca-central-1.amazonaws.com/cryptomibs/baby+marble.png'
- `@inlet/react-pixi` version: 
- `React` version:
- `ReactDOM` version:
- `PIXI` version:

**Comment by inlet** [comment]
Hi @rabiaasif,

Make sure to enable CORS for that image

```
Access to Image at 'https://s3.ca-central-1.amazonaws.com/cryptomibs/baby+marble.png' from origin 'https://s.codepen.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. 
```

Here's an example with another image: 

https://codepen.io/inlet/pen/eeb943234413cb665b22104509c5f75e

**Comment by rabiaasif** [comment]
Is this allowed to be used for production purposes?

**Comment by ArielFrischer** [comment]
I'm running into this issue as well, it seems like `react-pixi` is making an `XMLHttpRequest` to the image url without any `Access-Control-Allow-Origin` header. For most requests this works fine in my application but only react-pixi is giving this error. 

We use react-pixi as shown below, imgSrc is just the s3 url to a jpg. We've tried allowing any origin, that did not work.
```
 <Sprite
      x={position.x}
      y={position.y}
      height={pixiApp ? pixiApp.view.height * scale : undefined}
      width={pixiApp ? pixiApp.view.width * scale : undefined}
      image={imgSrc}
    />
```
### Error Messages:
`Access to XMLHttpRequest at 'https://someImage.jpg' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

![image](https://user-images.githubusercontent.com/19893395/82278469-215db480-993f-11ea-96fb-58df6eed7908.png)

### S3 Cors configuration:
```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
</CORSRule>
</CORSConfiguration>
```
