### ISSUE TITLE
AppConsumer does not work if Pixi application not has been created using Stage

### ISSUE THREAD

**Issue by bichotll** [inlet/react-pixi#54]
### Description

The AppConsumer returns { app: undefined } when the app is not created using <Stage /> component.

### Steps to reproduce

See example one: https://codepen.io/anon/pen/YJYxRZ?editors=0010 (Notice console.log on line 19)
See example two (original example): https://codepen.io/inlet/pen/aYLvrZ?editors=0010

### Additional info

- `@inlet/react-pixi` version: 
- `React` version:
- `ReactDOM` version:
- `PIXI` version:
^ All from https://codepen.io/inlet/pen/cb74b4dcdae3c8c621a29c43f5967dd9 dependencies

**Comment by inlet** [comment]
Hi @bichotll,

If you're using a custom renderer (= without the `Stage`), make sure to wrap your stuff in the `AppProvider`:

```jsx
<AppProvider value={app}>
   ...
</AppProvider>
```

You can see that the `Stage` does exactly the same: 
https://github.com/inlet/react-pixi/blob/cf8c89bcfd6620cdba0d4efc43650b8389c047d1/src/stage/index.js#L150

Here's an updated version of your codepen:

https://codepen.io/inlet/pen/0d6625478cc5abb53f783e571e91b612/

**Comment by inlet** [comment]
> See example two (original example): https://codepen.io/inlet/pen/aYLvrZ?editors=0010

Is this not working? Seems to work here :wink:

**Comment by inlet** [comment]
Maybe we should update the docs with an example of `AppProvider`

**Comment by bichotll** [comment]
> > See example two (original example): https://codepen.io/inlet/pen/aYLvrZ?editors=0010
> 
> Is this not working? Seems to work here 😉

I just wanted to show the original example 👍 It works.


> Maybe we should update the docs with an example of `AppProvider`

That could be useful in case someone comes across this issue.

**Comment by inlet** [comment]
👍 thanks!

I'll update the docs
