### ISSUE TITLE
Can you provide more examples?

### ISSUE THREAD

**Issue by EloB** [inlet/react-pixi#6]
This isn't a direct issue but I would love to see some more examples. Right now I have a hard time figuring about how to use `mask`.

**Comment by inlet** [comment]
There are quite some examples on https://codepen.io/collection/XPpGdb

You can easily create [custom PIXI components](https://github.com/inlet/react-pixi#custom-components) and extend custom behaviour.

Here's an example of using mask:
https://codepen.io/inlet/pen/c2034d53f6f68faf8bf19e87a3e45663/?editors=0110

I've used the requestAnimationFrame only for demo-purpose, do not use that in your code ;)
