### ISSUE TITLE
Differences from https://github.com/michalochman/react-pixi-fiber?

### ISSUE THREAD

**Issue by unformatt** [inlet/react-pixi#60]
How does this module compare with https://github.com/michalochman/react-pixi-fiber? Implementation appears almost identical. Not sure which was first or if one inspired the other.

Thanks

**Comment by inlet** [comment]
Hi @unformatt,

This repo started as a private project and I was inspired by other reconcilers (as I was and still am learning about how reconcilers work). I did review the codebase of multiple React PIXI implementations and at that time they all seem to lack in features, performance, testing, and more.. and I believed I could do better.

**TLDR;** how this lib compares to his (and others)? They both serve the same goal, which is augmenting the imperative PIXI API into the React paradigm. I haven't been watching his progress on the project, but at that time it didn't support events, props handling could be better and no way to access the `PIXI.Application` via render props or a higher order component.  I tried to be as complete as can be to included a bunch of PIXI components right out of the box (Sprite, Container, Rope, Mesh, TilingSprite, Text, BitmapText, etc) and of course the ability to create your own custom ones that the reconciler can interpret.

I hope this answers your questions.

Thanks!
