### ISSUE TITLE
Support React Hooks

### ISSUE THREAD

**Issue by animify** [inlet/react-pixi#64]
It looks like this library does not support the new React Hooks, is it possible to support them?

When using hooks like `useContext` this is the error we're getting:

![image](https://user-images.githubusercontent.com/10724744/49359993-86d4cb80-f6e0-11e8-866f-2ffe680162ea.png)

Thanks

**Comment by inlet** [comment]
Thanks, yes we need to update the reconciler. I’m planning on adding some custom hooks, which hooks do you think would be awesome to have?

An idea `useTick`:

```jsx
const MyComponent = () => {
  const [x, setX] = useState(0)

  useTick(
    delta => setX(x + 1 * delta)
  )

  return (
    <Container x={x} />
  )
}
```

**Comment by animify** [comment]
Cool! Yeah forked it and updated react, react-dom & react-reconciler and it seems to work fine, cheers.

`useTick` sounds like a good one, can't seem to think of anything else off the top of my head right now

**Comment by inlet** [comment]
Awesome 🙌 I’ll update the lib with the new reconciler soon. Thanks!

**Comment by inlet** [comment]
And add the test and implementation for the useTick hook

**Comment by inlet** [comment]
With example: https://codepen.io/inlet/pen/EOMBer

**Comment by animify** [comment]
@inlet doesn't seem to be exported when using Typescript? 🤔 Maybe an issue with the declaration file?

**Comment by inlet** [comment]
What exactly do you see/experience? I use react pixi in a Typescript project and it works as expected

**Comment by inlet** [comment]
Ah wait I need to update the type def for the hooks, that’s what you mean right?

**Comment by animify** [comment]
Yep for the hooks otherwise all good!

**Comment by inlet** [comment]
Awesome! I’ll add type def for hooks tomorrow

**Comment by animify** [comment]
Neat, cheers man!

**Comment by inlet** [comment]
And updated the docs accordingly: https://reactpixi.org/#/hooks 🙌

**Comment by inlet** [comment]
Hi @animify, I've updated the type def and hooks is now supported! 

Thanks for contrib.

**Comment by animify** [comment]
Tried it out, working beautifully! Great work, cheers 🎉
