### ISSUE TITLE
Stage never teardown it's application

### ISSUE THREAD

**Issue by EloB** [inlet/react-pixi#7]
I noticed that my app gets slower and slower. I've looked at your code and I can't see that you dont't destroy Pixi Application on unmount.

https://github.com/inlet/react-pixi/blob/master/src/stage/index.js#L155

Maybe change to?
```js
componentWillUnmount() {
    PixiFiber.updateContainer(null, this.mountNode, this)
    this.renderStage() // Do you have to render stage on unmount?
    this.app.destroy()
}
```

**Comment by inlet** [comment]
Ah thanks, seems like I totally forgot to destroy it on unmount. You can create a PR if you'd like?
The stage needs to be rendered manually on unmount as it clears the pixi stage.

**Comment by EloB** [comment]
Thanks for awesome library! Dreamed about this for a long time!

https://github.com/pixijs/pixi.js/issues/4028
