### ISSUE TITLE
How to use profiler?

### ISSUE THREAD

**Issue by EloB** [inlet/react-pixi#81]
I've discovered the profiler in React. https://reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html

Is this possible to use with `react-pixi`?

I don't use `react-dom` renderer.

**Comment by inlet** [comment]
I'm not quite sure, my guess is that it doesn't work if you're not using `react-dom` right?
One way to find out. And again, feel free to implement it 😄 

Cheers
