### ISSUE TITLE
Does react-pixi work with v5?

### ISSUE THREAD

**Issue by EloB** [inlet/react-pixi#82]
Hello

I've just saw that pixi.js has a release candidate for v5 now. :)

Do you know if it will work out of the box?

https://github.com/pixijs/pixi.js/tree/v5.0.0-rc

**Comment by inlet** [comment]
One way to find out ☺️

Let’s use the Github issues for code issues only to keep things organised. 

And of course feel free to email me for questions, suggestions, whatever.

**Comment by EloB** [comment]
Works according to https://github.com/inlet/react-pixi/issues/51#issuecomment-464060728

Just adds it here. If someone else have the same question ;)
