### ISSUE TITLE
Sprite doesn't change image on prop update

### ISSUE THREAD

**Issue by EloB** [inlet/react-pixi#9]
As topic says.

Here is a simple example.
http://jsbin.com/datowucebu/edit?js,console,output

**Comment by inlet** [comment]
Good one! Now it only converts the image once on creation. If you use texture it works:

http://jsbin.com/qiqebahepa/1/edit?js,console,output

A fix would be something like this:

src/components/Sprite.js

```js
import * as PIXI from 'pixi.js'
import { getTextureFromProps, applyDefaultProps } from '../utils/props'

const Sprite = (root, props) => {
  const sprite = new PIXI.Sprite(getTextureFromProps('Sprite', props))

  sprite.applyProps = (instance, oldProps, newProps) => {
    const { image, texture, ...props } = newProps
    applyDefaultProps(instance, oldProps, props)

    if (image || texture) {
      instance.texture = getTextureFromProps(newProps)
    }
  }
}

export default Sprite
```

Same applies to other components like for example `NineSlicePlane`

**Comment by inlet** [comment]
If you'd like you can create a PR with a fix or if you prefer I can fix it as well (would be probably somewhere next week) 😄

**Comment by EloB** [comment]
Yeah I noticed that Texture worked so continued with that. Just wanted to inform that image was more or less static :)

**Comment by inlet** [comment]
True, yes need to be fixed. I'll create a PR and fix this once I've time. 
Thanks for pointing out though!

**Comment by inlet** [comment]
Hi @EloB, I've just fixed the issue.

Now it updates on syntactical built-in PIXI components updates, like `image` and `draw` props.
