### ISSUE TITLE
How to click Sprite change state

### ISSUE THREAD

**Issue by namhd1992** [inlet/react-pixi#90]
I have a Sprite and i want to click it call function change state

**Comment by inlet** [comment]
See events: http://pixijs.download/dev/docs/PIXI.interaction.InteractionManager.html

Example: https://codepen.io/inlet/pen/NYazPq

**Comment by gp3098** [comment]
Based on your example, I successfully triggered the click event
By the way, the document  address has changed
https://pixijs.download/dev/docs/PIXI.InteractionManager.html
thank you !
