### ISSUE TITLE
Typing for withPixiApp HOC not accepting additional props

### ISSUE THREAD

**Issue by kresli** [inlet/react-pixi#91]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/3826097/54112423-0825b380-43de-11e9-8f0e-d2a0f296db65.png)

### Additional info

- `@inlet/react-pixi` version: "^0.5.1"
- `React` version: "^16.8.2"
- `ReactDOM` version: "^16.6.1"
- `PIXI` version: "^5.0.0-rc.2"

**Comment by kresli** [comment]
Maybe the type should be change to 
```
  // context HOC
  const withPixiApp: <P extends { app?: PIXI.Application }>(
    baseComponent: React.ComponentClass<P>
  ) => React.ComponentClass<P>;
```

**Comment by kresli** [comment]
However the above cannot be used as decorator. If you want support decorator style 
```
@withPixiApp
class RotatingBunny extends React.Component<{
  app: PIXI.Application;
  text: string;
}> {
  public render() {
    return <Sprite image="./bunny.png" />;
  }
}
```
then we change type to something similar to 
```
  type IReactComponent<P = any> =
    | React.StatelessComponent<P>
    | React.ComponentClass<P>
    | React.ClassicComponentClass<P>

  // context HOC
  const withPixiApp: <T extends IReactComponent>(
    baseComponent: T
  ) => T
```
I'm happy to create a PR

**Comment by inlet** [comment]
Hi @kresli,

Thanks! It seems the HOC typing is broken indeed. This would fix the problem:

```tsx
const withPixiApp: <P extends { app: PIXI.Application }>(
  WrappedComponent: React.ComponentType<P>
) => React.ComponentClass<_ReactPixi.Omit<P, 'app'>>;
```

`app` should be mandatory for the inner `WrapperComponent` as this is a required prop (passed down by the HOC).

**Note on decorators**

Unfortunately we cannot support decorators as they force the type to return `| void` and therefore cannot be used the classic way anymore, see:

https://medium.com/@jan.hesters/typescript-hoc-higher-order-component-and-decorators-in-react-586787f5a9e7

**Comment by inlet** [comment]
Let me know if this works and I'll create a patch with the fix :)

**Comment by kresli** [comment]
Thanks for quick respond. Above suggestion works like a charm.
![image](https://user-images.githubusercontent.com/3826097/54121160-a0796380-43f1-11e9-9b67-4f13d19ca1a5.png)
