### ISSUE TITLE
Wrong TS definition for anchor

### ISSUE THREAD

**Issue by kresli** [inlet/react-pixi#94]
![image](https://user-images.githubusercontent.com/3826097/54235436-26d49900-4509-11e9-9e94-49fc07612340.png)

Following works well
`anchor={[0.5, 0]}`
`anchor={0.5}` 
`anchor={[0.5]}` 

currently type comes from `pixi.js.d.ts` as `anchor: PIXI.ObservablePoint;`

### Additional info

- `@inlet/react-pixi` version: ^0.5.5
- `React` version: ^16.8.2
- `ReactDOM` version: ^16.6.1
- `PIXI` version: ^5.0.0-rc.2

**Comment by inlet** [comment]
Updated 🙌 

I've also added comments to improve type support:

![image](https://user-images.githubusercontent.com/232559/54268766-40fb8f00-457c-11e9-9fd9-b01714f216d6.png)

**Comment by kresli** [comment]
Amazing! Thank you for all your work. Side question, Is it ` | undefined` necessary here? Its already set as optional by `anchor?: `

**Comment by kresli** [comment]
also you wouldn't be better to change `number[]` to `[number, number] | [number]`?

**Comment by kresli** [comment]
actually I think we could ditch `[number]` anyway

**Comment by inlet** [comment]
> Amazing! Thank you for all your hard work. Side question, Is it ` | undefined` necessary here? Its already set as optional by `anchor?: `

I think it's actually VSCode that explicitly show this to identify `undefined` as a valid value. It's not in the type declaration though:

https://github.com/inlet/react-pixi/blob/244becd038f8969cdcd20e434bf09e66d72e9c1a/index.d.ts#L14

> also wouldn't be better to change `number[]` to `[number, number] | [number]`?

Yes you are right. I'll change that as well.

> actually I think we could ditch [number] anyway

I agree, but it can be a valid type.

Thanks for your collab!

**Comment by inlet** [comment]
Update on the `PointLike` type, see:

https://github.com/inlet/react-pixi/blob/ff148e9b81ba35f0110e2238dd3a720e8d7579a3/index.d.ts#L14-L17
