### ISSUE TITLE
Use Pixi Geometry in PixiComponent

### ISSUE THREAD

**Issue by kresli** [inlet/react-pixi#96]
Is it possible to feed PixiComponent with other then Graphics type?

![image](https://user-images.githubusercontent.com/3826097/54421840-243e9300-4705-11e9-8748-183f5e2e6e01.png)

### Additional info

- `@inlet/react-pixi` version: "^0.5.5"
- `React` version: "^16.8.2"
- `ReactDOM` version: "^16.6.1"
- `PIXI` version: "^5.0.0-rc.2"

**Comment by inlet** [comment]
Yes you can return anything as long it is a `PIXI.DisplayObject`. 

A `PIXI.RoundedRectangle` is a shape, this cannot be added directly to a parent container.
