### ISSUE TITLE
react-devtools support

### ISSUE THREAD

**Issue by RodrigoHamuy** [inlet/react-pixi#97]
Alo. Any plans to support react-devtools? 

Currently it only shows up to the canvas element.

![image](https://user-images.githubusercontent.com/2405611/54722639-d2f72f00-4b5c-11e9-9f8f-59bd881800d4.png)

I think Izzimach version of react-pixi does support this:
![react-pixi-devshot](https://github.com/Izzimach/react-pixi/raw/master/docs/react-pixi-devshot.png)

More info: https://github.com/facebook/react-devtools/issues/160

Keep it up with the great work!

**Comment by Foxhunt** [comment]
Did you try the pixi chrome Dev tool?

**Comment by inlet** [comment]
Feel free to create a PR 😊

**Comment by RodrigoHamuy** [comment]
Hi guys, thanks for the answers. Not sure why but this is working fine now! (Sometimes you just need to restart DevTools, that's all). It says "TODO_NOT_IMPLEMENTED_YET", which I am not sure what it means, but this works perfectly for me. Thanks!

Also, Pixi Dev Tools is amazing, never saw that one before.

**Comment by inlet** [comment]
Yes I noticed that the `react-reconciler` now supports injecting the devtools correctly, finally 🙌

Great to see it working now, I'll close this issue.
