### ISSUE TITLE
Running CRA throw error of missing "extras" from pixi.js v5

### ISSUE THREAD

**Issue by kresli** [inlet/react-pixi#98]
### Description

```
./node_modules/@inlet/react-pixi/dist/react-pixi.module-dev.js
Attempted import error: 'extras' is not exported from 'pixi.js'.
```

- Works in Storybook
- Works with pixi.js 4
- Doesn't work with CRA (create-react-app)

### Steps to reproduce

1. `git clone https://github.com/kresli/cra-react-pixi`
2. `yarn` or `npm install`
3. `yarn start`

### Additional info (please refer to provided repository)

-  "@types/pixi.js": "^4.8.6"
-    "@inlet/react-pixi": "^0.5.7",
-    "@types/react": "16.8.8",
-    "@types/react-dom": "16.8.3",
-    "pixi.js": "^5.0.0-rc.2",
-    "react": "^16.8.5"

**Comment by inlet** [comment]
Ah yes, Pixi v5 is not fully supported yet. (nothing to do with create-react-app though)

Feel free to create a PR, should be easy to fix. Some namespaces and implementations have slightly changed.

**Comment by chrisella** [comment]
I've got the same issue with PIXI v5, I assume this hasn't be tackled yet ?

**Comment by inlet** [comment]
Hi @chrisella, I haven't got the time to make this lib PIXI v5 compliant. On the other hand it should be fairly simple. Feel free to create a PR and we'll work on it together :)

**Comment by chrisella** [comment]
I did actually clone the repo and start taking a look last night, but quickly encountered issues just trying to install the npm dependencies with ```yarn``` :(
It seems you're using node-canvas-prebuilt which is 404'ing and from what I've read has been superseded, but unfortunately that means it's fairly hard for me to begin taking look without some significant time poking at the internals I suspect.
That said, if you know a reason I'd be getting this and any work-around etc then please do let me know and I can keep pressing forward.

**Comment by inlet** [comment]
Ah I see, `canvas-prebuilt` is only needed to support canvas in jsdom. It seems that replacing this with `canvas` package should fix the issue, see https://github.com/jsdom/jsdom#canvas-support. Haven't tested it though.

I'm currently busy working on another project, but I'll give it a proper look when I have time. In meantime feel free to fiddle around and see if you get it working ☺️

**Comment by inlet** [comment]
Btw, you can use PIXI v5 stuff by using [custom components](https://reactpixi.org/#/#custom-components). Here's an example https://codepen.io/inlet/pen/feddc8fa71e3b5afc6c3e4eda9cc83df

**Comment by rluncasu** [comment]
should be fixed by this PR https://github.com/inlet/react-pixi/pull/109
I've tested with pixijs 5.0.4 & 4.8.5 and both seem to work correctly

**Comment by inlet** [comment]
@rluncasu just check out the [docs](http://pixijs.download/dev/docs/index.html), you can find tuts and demos there.

**Comment by human-a** [comment]
This worked for me:
```javascript
import * as PIXI from "pixi.js";
window.PIXI = PIXI;
import 'pixi-projection'; // or require("pixi-projection");
```
The only exception is if you wanna call ```PIXI.projection``` you have to call it like ```window.PIXI.projection```

I hope this gets fixed soon, I guess the Pixi plugins should also support ES6 modules.

**Comment by inlet** [comment]
Hi @human-a,

This seems not related to react-pixi, see: 
https://github.com/pixijs/pixi-projection#angularjs

**Comment by human-a** [comment]
Oops, sorry I commented on the wrong repo :D

**Comment by inlet** [comment]
No worries 😉
